services:
  - type: web
    name: contagest-backend
    env: node
    rootDir: backend
    buildCommand: npm install --include=dev && npx prisma generate && npm run build
    startCommand: node dist/src/server.js
    plan: free
