import logoUrl from '../../assets/img/contagest-mark.svg';
import { bs } from '../core/formatters.js';
import { modulesByArea, BUSINESS_MODES, MODULE_TIERS, MODULE_CATALOG } from '../data/moduleCatalog.js';
import { SUPPORT_WIDGET_OPTIONS, THEME_OPTIONS } from '../data/themeCatalog.js';
import { escapeHtml } from '../utils/dom.js';
import { AccessControlService } from '../services/accessControlService.js';
import { LANGUAGE_OPTIONS } from '../i18n/locales.js';

const MenuSvg = () => `<svg class="hf-menu-svg" viewBox="0 0 24 24" aria-hidden="true"><path d="M4 7h16M4 12h16M4 17h16" /></svg>`;
const ThemeSvg = (dark = false) => dark
  ? `<svg class="hf-theme-svg" viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="3.5" fill="none" stroke="currentColor" stroke-width="1.8"/><path d="M12 2.5v2M12 19.5v2M4.6 4.6l1.4 1.4M18 18l1.4 1.4M2.5 12h2M19.5 12h2M4.6 19.4L6 18M18 6l1.4-1.4" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"/></svg>`
  : `<svg class="hf-theme-svg" viewBox="0 0 24 24" aria-hidden="true"><path d="M20.2 15.2A8.5 8.5 0 0 1 8.8 3.8a8.7 8.7 0 1 0 11.4 11.4Z" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round"/></svg>`;
const compactRate = (value) => {
  const numeric = Number(value);
  if (!Number.isFinite(numeric)) return '—';
  return new Intl.NumberFormat('es-VE', { minimumFractionDigits:2, maximumFractionDigits:2 }).format(numeric);
};
const areaIcon = (area) => ({ Inicio:'fa-house', Ventas:'fa-cash-register', Operaciones:'fa-bell-concierge', Inventario:'fa-boxes-stacked', Compras:'fa-cart-shopping', Contabilidad:'fa-scale-balanced', Fiscal:'fa-landmark', RRHH:'fa-users-gear', Salud:'fa-heart-pulse', Fitness:'fa-dumbbell', Comunicación:'fa-comments', Analítica:'fa-chart-line', Administración:'fa-user-shield', Soporte:'fa-headset' }[area] || 'fa-layer-group');
const AREA_I18N = { Inicio:'areaHome', Ventas:'areaSales', Operaciones:'areaOperations', Inventario:'areaInventory', Compras:'areaPurchases', Contabilidad:'areaAccounting', Fiscal:'areaTax', RRHH:'areaHr', Salud:'areaHealth', Fitness:'areaFitness', Comunicación:'areaCommunication', Analítica:'areaAnalytics', Administración:'areaAdministration', Soporte:'areaSupport' };
const moduleIcon = (route) => ({ dashboard:'fa-chart-pie', mobile:'fa-mobile-screen-button', ventas:'fa-receipt', cotizacion:'fa-file-invoice-dollar', clientes:'fa-users', historial:'fa-clock-rotate-left', pedidos:'fa-bell-concierge', 'pos-sede':'fa-cash-register', 'tracking-pedidos':'fa-timeline', 'delivery-mapa':'fa-map-location-dot', tasks:'fa-list-check', inventario:'fa-boxes-stacked', 'inventario-scan':'fa-barcode', kardex:'fa-clipboard-list', qr:'fa-qrcode', proveedores:'fa-truck-field', compras:'fa-cart-shopping', contabilidad:'fa-book', 'plan-cuentas':'fa-sitemap', 'libro-mayor':'fa-book-open-reader', 'balance-sumas-saldos':'fa-scale-balanced', 'hoja-trabajo':'fa-table-columns', 'estados-financieros':'fa-file-invoice-dollar', 'cierre-contable':'fa-lock', bancos:'fa-building-columns', 'normativa-contable':'fa-globe', tributos:'fa-scale-balanced', 'libro-ventas':'fa-book-open', normativa:'fa-book-open', nomina:'fa-users-gear', rrhh:'fa-user-tie', salud:'fa-stethoscope', veterinaria:'fa-paw', psicologia:'fa-brain', odontologia:'fa-tooth', gimnasio:'fa-dumbbell', rutinas:'fa-person-running', nutricion:'fa-apple-whole', mensajes:'fa-comments', analytics:'fa-chart-line', reportes:'fa-chart-simple', auditoria:'fa-shield-halved', configuracion:'fa-gear', backend:'fa-plug', admin:'fa-user-shield', marca:'fa-swatchbook', 'demo-control':'fa-user-lock', licencias:'fa-key', 'importacion-data':'fa-file-import', 'reglas-negocio':'fa-gears', 'modulos-madurez':'fa-cubes', pretesting:'fa-shield-check', vistas:'fa-layer-group', profile:'fa-user', 'asistente-ia':'fa-robot', soporte:'fa-headset', ayuda:'fa-circle-question' }[route] || 'fa-circle-dot');
const DEFAULT_PRIMARY_ROUTES = ['dashboard','ventas','inventario','contabilidad','reportes'];
const routeLabel = (route) => ({ dashboard:'Dashboard', 'libro-ventas':'Libro de ventas', inventario:'Inventario', kardex:'Kardex', ventas:'Ventas', pedidos:'Pedidos', contabilidad:'Libro diario', 'libro-mayor':'Libro mayor', 'balance-sumas-saldos':'Balance de sumas y saldos', 'hoja-trabajo':'Hoja de trabajo', 'estados-financieros':'Estados financieros', 'cierre-contable':'Cierre contable', 'plan-cuentas':'Plan de cuentas', 'importacion-data':'Carga masiva', licencias:'Licencias', analytics:'Analítica', reportes:'Reportes', soporte:'Soporte', pretesting:'Estado del sistema', salud:'Clínica', veterinaria:'Clínica veterinaria', psicologia:'Psicología y agenda', odontologia:'Odontología', gimnasio:'Gimnasio', mensajes:'Mensajes', vistas:'Galería de módulos' }[route] || route);
const whatsappDigits = (value = '') => String(value || '').replace(/\D/g, '');
const whatsappSupportUrl = (state = {}) => { const phone=whatsappDigits(state.settings?.whatsappBusinessNumber || state.support?.whatsapp || state.settings?.companyPhone || ''); const text=encodeURIComponent('Hola, necesito soporte técnico con ContaGest-VE'); return phone ? `https://api.whatsapp.com/send?phone=${phone}&text=${text}` : `https://api.whatsapp.com/send?text=${text}`; };
function routeMeta(route){return MODULE_CATALOG.find((item)=>item.route===route)||{route,name:routeLabel(route),area:'Inicio',tier:'demo'};}
function breadcrumbItems(activeRoute){const meta=routeMeta(activeRoute);return[{label:meta.name||routeLabel(activeRoute),route:activeRoute,current:true}];}
function commandPaletteItems(state){const seen=new Set();const priority=['dashboard','ventas','clientes','inventario','kardex','libro-ventas','contabilidad','libro-mayor','balance-sumas-saldos','hoja-trabajo','estados-financieros','reportes','salud','veterinaria','psicologia','odontologia','gimnasio','configuracion','admin','backend'];return[...priority.map(routeMeta),...MODULE_CATALOG].filter((item)=>item?.route&&!seen.has(item.route)&&seen.add(item.route)).filter((item)=>AccessControlService.canAccessRoute(state,item.route)).map((item)=>({route:item.route,label:item.name||routeLabel(item.route),area:item.area||'Sistema',tier:item.tier||'core',icon:moduleIcon(item.route),keywords:[item.name,item.area,item.route,item.description].filter(Boolean).join(' ')})).slice(0,96);}
function moduleButton(item,activeRoute,state){
  const locked=!AccessControlService.canAccessRoute(state,item.route);
  return `<button type="button" class="menu-link hf-menu-item ${activeRoute===item.route?'active':''} ${locked?'is-locked':''}" data-route="${item.route}" title="${locked?'Bloqueado por rol, licencia o plan activo':escapeHtml(item.name)}" aria-disabled="${locked?'true':'false'}" ${activeRoute===item.route?'aria-current="page"':''}><span class="hf-menu-item-icon"><i class="fa-solid ${locked?'fa-lock':moduleIcon(item.route)}"></i></span><span data-i18n-route="${item.route}">${escapeHtml(item.name)}</span></button>`;
}
function primaryRoutes(state){
  const fromExperience=Array.isArray(state.experienceProfile?.quickRoutes)?state.experienceProfile.quickRoutes:[];
  return [...new Set((fromExperience.length?fromExperience:DEFAULT_PRIMARY_ROUTES).map(String))];
}
function primaryMenu(state){
  const available=primaryRoutes(state).map(routeMeta).filter((item)=>item&&AccessControlService.canAccessRoute(state,item.route));
  if(!available.length)return'';
  return `<section class="hf-primary-nav" aria-label="Accesos principales"><p class="hf-sidebar-label">Espacio de trabajo</p><div class="hf-primary-list">${available.map((item)=>moduleButton(item,state.route,state)).join('')}</div></section>`;
}
function menuSections(state){
  const byArea=modulesByArea(state.settings?.businessMode||'admin',{includeAll:false});
  const activeRoute=state.route;
  const activeArea=routeMeta(activeRoute).area;
  const promoted=new Set(primaryRoutes(state));
  return Object.entries(byArea).map(([area,rawItems])=>{
    const items=rawItems.filter((item)=>!promoted.has(item.route));
    if(!items.length)return'';
    const open=area===activeArea;
    return `<details name="cg-sidebar-modules" class="hf-menu-section" data-sidebar-section="${escapeHtml(area)}" ${open?'open':''}><summary class="cg-area-toggle"><span><span class="hf-area-icon"><i class="fa-solid ${areaIcon(area)}"></i></span><span data-i18n="${AREA_I18N[area]||''}">${escapeHtml(area)}</span></span><span class="hf-area-meta"><small>${items.length}</small><i class="fa-solid fa-chevron-down hf-section-chevron"></i></span></summary><div class="hf-menu-list">${items.map((item)=>moduleButton(item,activeRoute,state)).join('')}</div></details>`;
  }).join('');
}
const themeOptions=(current)=>THEME_OPTIONS.map((item)=>`<option value="${item.key}" ${current===item.key?'selected':''}>${escapeHtml(item.name)}</option>`).join('');
const supportWidgetOptions=(current)=>SUPPORT_WIDGET_OPTIONS.map((item)=>`<option value="${item.value}" ${current===item.value?'selected':''}>${escapeHtml(item.label)}</option>`).join('');

export const Shell=(state,pagesHtml)=>{
  const mode=state.experienceProfile?.mode||state.settings?.businessMode||'admin',lang=state.settings?.lang||'es',sidebarCollapsed=Boolean(state.settings?.sidebarCollapsed),sidebarStateClass=sidebarCollapsed?'is-collapsed -translate-x-full':'-translate-x-full lg:translate-x-0';
  const activeMeta=routeMeta(state.route),breadcrumbs=breadcrumbItems(state.route),commandItems=commandPaletteItems(state),avatarSrc=state.profile?.avatarDataUrl||'',avatarInitials=String(state.profile?.name||'A').split(' ').map((p)=>p[0]).join('').slice(0,2).toUpperCase()||'A',supportWidget=state.settings?.supportWidget||'peek',supportUrl=whatsappSupportUrl(state),rateSource=`${state.bcv.source||'Pendiente'}${state.bcv.stale?' · revisar':''}`,rateMobile=compactRate(state.bcv.rate),darkTheme=state.settings.theme==='dark';
  const modeLabel=state.experienceProfile?.label||BUSINESS_MODES[mode]?.label||'Modo Administrador';
  const experienceActionRoute=state.experienceProfile?.landingRoute||'dashboard';
  const experienceActionLabel=state.experienceProfile?.landingLabel||routeMeta(experienceActionRoute).name||'Inicio';
  return `<div id="sidebarBackdrop" class="fixed inset-0 z-40 hidden bg-black/45 lg:hidden"></div>
  <aside id="sidebar" class="hf-sidebar hf-app-sidebar cg-sidebar ${sidebarStateClass}">
    <div class="hf-brand hf-app-brand"><div class="hf-brand-mark" aria-hidden="true"><img src="${escapeHtml(logoUrl)}" alt="" /></div><div class="hf-sidebar-wordmark"><h1>ContaGest</h1><p>${escapeHtml(modeLabel)}</p></div><button id="btnCloseSidebar" class="hf-sidebar-collapse" type="button" aria-label="Contraer menú"><i class="fa-solid fa-chevron-left"></i></button></div>
    <nav class="cg-sidebar-nav hf-app-nav" id="mainMenu" aria-label="Navegación principal">${primaryMenu(state)}<div class="hf-module-nav"><p class="hf-sidebar-label">Módulos</p>${menuSections(state)}</div></nav>
    <div class="cg-sidebar-footer hf-sidebar-footer"><div class="hf-sidebar-mini-actions"><button type="button" data-route="configuracion" aria-label="Configuración"><i class="fa-solid fa-gear"></i></button><button type="button" data-route="ayuda" aria-label="Ayuda"><i class="fa-solid fa-circle-question"></i></button></div><button type="button" class="hf-sidebar-account" data-route="profile"><span class="hf-avatar">${avatarSrc?`<img src="${escapeHtml(avatarSrc)}" alt="Avatar de usuario" />`:avatarInitials}</span><span><strong>${escapeHtml(state.profile?.name||'Administrador')}</strong><small>${escapeHtml(state.profile?.role||modeLabel)}</small></span><i class="fa-solid fa-ellipsis"></i></button></div>
  </aside>
  <div class="hf-main hf-app-main">
    <header class="hf-topbar hf-app-topbar" data-header-responsive="v15">
      <div class="hf-topbar-left"><button id="btnOpenSidebar" class="hf-icon-button hf-menu-toggle" type="button" aria-label="${sidebarCollapsed?'Abrir menú':'Menú abierto'}">${MenuSvg()}</button><div class="hf-header-context"><span>${escapeHtml(activeMeta.area||'ContaGest')}</span><strong>${escapeHtml(activeMeta.name||routeLabel(state.route))}</strong></div></div>
      <button id="btnCommandPalette" class="hf-command-trigger" type="button" aria-label="Buscar módulos, clientes, documentos y reportes"><i class="fa-solid fa-magnifying-glass"></i><span>Buscar en ContaGest</span><kbd>Ctrl K</kbd></button>
      <div class="hf-topbar-actions hf-app-topbar-actions">
        <button class="hf-create-button" data-route="${escapeHtml(experienceActionRoute)}" data-experience-action="true" type="button"><i class="fa-solid ${moduleIcon(experienceActionRoute)}"></i><span>${escapeHtml(experienceActionLabel)}</span></button>
        <div class="hf-rate-compact" aria-label="Tasa BCV ${escapeHtml(bs(state.bcv.rate))} por USD. Fuente ${escapeHtml(rateSource)}" title="Tasa BCV · ${escapeHtml(rateSource)}"><span class="hf-rate-status-dot" aria-hidden="true"></span><span class="hf-rate-copy"><small>BCV</small><strong><span id="tasaHeader" class="hf-rate-full">${bs(state.bcv.rate)}</span><span id="tasaHeaderMobile" class="hf-rate-mobile" aria-hidden="true">${escapeHtml(rateMobile)}</span></strong></span></div>
        <button id="btnActualizarTasaTop" class="hf-icon-button hf-rate-update" type="button" aria-label="Actualizar tasa BCV" title="Actualizar tasa BCV"><i class="fa-solid fa-rotate"></i></button>
        <button id="btnTema" class="hf-icon-button" type="button" aria-label="Cambiar tema" title="Cambiar tema">${ThemeSvg(darkTheme)}</button>
        <div class="hf-user-menu"><button id="btnUserMenu" type="button" class="hf-user-trigger" aria-label="Abrir configuración de usuario" aria-haspopup="menu" aria-expanded="false" title="Usuario y configuración"><span class="hf-avatar">${avatarSrc?`<img src="${escapeHtml(avatarSrc)}" alt="Avatar de usuario" />`:avatarInitials}</span><i class="fa-solid fa-chevron-down hf-user-chevron" aria-hidden="true"></i></button><div id="userMenuPanel" class="hf-user-panel hidden" role="menu"><div class="hf-user-panel-head"><strong>${escapeHtml(state.profile?.name||'Administrador')}</strong><span>${escapeHtml(state.profile?.email||'admin@erp.local')}</span></div><button type="button" data-user-action="profile"><i class="fa-solid fa-user"></i><span>Perfil</span></button><button type="button" id="btnAvatarUpload"><i class="fa-solid fa-camera"></i><span>Cambiar foto</span></button><button type="button" data-user-action="settings"><i class="fa-solid fa-gear"></i><span>Configuración</span></button><label class="hf-user-select"><span><i class="fa-solid fa-language"></i> Idioma</span><select id="userMenuLang">${LANGUAGE_OPTIONS.map((item)=>`<option value="${item.value}" ${lang===item.value?'selected':''}>${escapeHtml(item.label)}</option>`).join('')}</select></label><label class="hf-user-select"><span><i class="fa-solid fa-palette"></i> Tema</span><select id="userMenuTheme">${themeOptions(state.settings?.theme||'light')}</select></label><label class="hf-user-select"><span><i class="fa-brands fa-whatsapp"></i> Soporte flotante</span><select id="userSupportWidget">${supportWidgetOptions(supportWidget)}</select></label><button type="button" data-user-action="support"><i class="fa-brands fa-whatsapp"></i><span>Soporte</span></button><button type="button" data-user-action="logout"><i class="fa-solid fa-right-from-bracket"></i><span>Cerrar sesión</span></button></div><input id="avatarFileInput" type="file" accept="image/*" class="hidden" /></div>
      </div>
    </header>
    <main class="hf-content hf-app-content"><div class="hf-breadcrumbs-host" data-mui-breadcrumbs data-items="${escapeHtml(JSON.stringify(breadcrumbs))}"><nav class="hf-breadcrumbs-fallback">${breadcrumbs.map((item)=>item.route&&!item.current?`<button type="button" class="hf-breadcrumb-link" data-route="${item.route}" data-breadcrumb-route="${item.route}">${escapeHtml(item.label)}</button>`:`<span class="hf-breadcrumb-current">${escapeHtml(item.label)}</span>`).join('<i class="fa-solid fa-chevron-right"></i>')}</nav><div class="mui-react-mount" data-mui-breadcrumb-mount></div></div><div id="pages" class="route-enter hf-route-panel">${pagesHtml}</div><a id="btnWhatsappSupport" class="cg-whatsapp-float cg-whatsapp-${escapeHtml(supportWidget)}" href="${escapeHtml(supportUrl)}" target="_blank" rel="noopener noreferrer" aria-label="Abrir soporte en WhatsApp"><i class="fa-brands fa-whatsapp"></i></a><div id="commandPalette" class="hf-command-layer hidden" role="dialog" aria-modal="true"><div class="hf-command-backdrop" data-command-close="true"></div><section class="hf-command-box"><header class="hf-command-head"><div><p class="hf-eyebrow">Navegación rápida</p><h2>Buscar en ContaGest</h2><p>Abre un módulo, reporte o flujo sin recorrer todo el menú.</p></div><button type="button" class="hf-icon-button" data-command-close="true" aria-label="Cerrar"><i class="fa-solid fa-xmark"></i></button></header><label class="hf-command-input"><i class="fa-solid fa-magnifying-glass"></i><input id="commandSearchInput" type="search" placeholder="Escribe cliente, venta, inventario, reporte…" autocomplete="off" /></label><div id="commandResults" class="hf-command-results">${commandItems.map((item)=>`<button type="button" class="hf-command-item" data-command-route="${escapeHtml(item.route)}" data-command-keywords="${escapeHtml(`${item.label} ${item.area} ${item.keywords}`.toLowerCase())}"><span class="hf-command-icon"><i class="fa-solid ${item.icon}"></i></span><span><strong>${escapeHtml(item.label)}</strong><small>${escapeHtml(item.area)} · ${escapeHtml(MODULE_TIERS[item.tier]?.label||'Módulo')}</small></span><i class="fa-solid fa-arrow-right"></i></button>`).join('')}</div></section></div></main>
  </div>`;
};