import React from 'react';
import { Avatar, Box, Card, CardContent, Chip, Stack, Typography } from '@mui/material';
import { STATUS_TONE, shortCode } from './veterinaryWorkspace.helpers.js';
import { verticalAsset } from '../../assets/verticalAssets.js';

export const Icon = ({ name, size = 14 }) => <i className={`fa-solid ${name}`} style={{ fontSize:size }} aria-hidden="true" />;

export function Metric({ icon,label,value,hint,tone='primary' }) {
  return <Card sx={{minHeight:78}}><CardContent sx={{p:'11px!important',display:'grid',gridTemplateColumns:'30px minmax(0,1fr)',gap:1,alignItems:'start'}}><Avatar variant="rounded" sx={{width:30,height:30,borderRadius:'8px',bgcolor:'action.hover',color:`${tone}.main`,border:'1px solid',borderColor:'divider',fontSize:13}}><Icon name={icon}/></Avatar><Box sx={{minWidth:0}}><Typography variant="caption" color="text.secondary" sx={{fontWeight:600}}>{label}</Typography><Typography sx={{fontWeight:700,fontSize:'1rem',lineHeight:1.12,fontVariantNumeric:'tabular-nums',whiteSpace:'nowrap',overflow:'visible'}}>{value??0}</Typography>{hint&&<Typography variant="caption" color="text.secondary" noWrap>{hint}</Typography>}</Box></CardContent></Card>;
}
export function StatusChip({value}) { return <Chip label={String(value||'pendiente').replaceAll('_',' ')} color={STATUS_TONE[value]||'default'} variant={value==='normal'?'outlined':'filled'}/>; }
export function EmptyState({icon='fa-folder-open',title='Sin registros',text='Crea el primer registro para comenzar.',assetKey='veterinary'}) { const asset=verticalAsset(assetKey); return <Box sx={{py:2.5,px:2,textAlign:'left',color:'text.secondary'}}>{asset?<Box component="img" className="cgx-empty-asset" src={asset} alt="" aria-hidden="true" sx={{mb:1}}/>:<Avatar variant="rounded" sx={{width:32,height:32,mb:1,borderRadius:'8px',bgcolor:'action.hover',color:'primary.main',border:'1px solid',borderColor:'divider'}}><Icon name={icon} size={14}/></Avatar>}<Typography variant="subtitle2" color="text.primary">{title}</Typography><Typography variant="caption">{text}</Typography></Box>; }
export function SectionCard({title,subtitle,action,children,sx={}}) { return <Card sx={sx}><CardContent sx={{p:'13px!important'}}><Stack direction="row" gap={1} sx={{justifyContent:'space-between',alignItems:'flex-start',mb:1.2,flexWrap:'wrap'}}><Box sx={{minWidth:0}}><Typography variant="h6">{title}</Typography>{subtitle&&<Typography variant="caption" color="text.secondary">{subtitle}</Typography>}</Box>{action}</Stack>{children}</CardContent></Card>; }
export function EntityLabel({primary,secondary,id}) { return <Box sx={{minWidth:0,py:.15}}><Typography component="span" sx={{display:'block',fontSize:'.8125rem',fontWeight:600,lineHeight:1.25,overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap'}}>{primary||'Sin nombre'}</Typography><Typography component="span" variant="caption" color="text.secondary" sx={{display:'block',letterSpacing:'.025em'}}>#{shortCode(id)}{secondary?` · ${secondary}`:''}</Typography></Box>; }
