import {Store} from '../state/store.js';
import {CommercialService} from './commercialService.js';

let installed=false;
const SUSPEND_REASONS=['SEC_TENANT_ESCAPE_ATTEMPT','SEC_MALWARE','SEC_ATTACK_ACTIVE','FRAUD_IDENTITY','FRAUD_PAYMENT','BILLING_PAST_DUE','CONTRACT_LIMIT_BYPASS','CONTRACT_AUP','LEGAL_ORDER'];
const TERMINATE_REASONS=['SEC_ATTACK_ACTIVE','FRAUD_IDENTITY','FRAUD_PAYMENT','BILLING_PAST_DUE','CONTRACT_LIMIT_BYPASS','CONTRACT_AUP','LEGAL_ORDER','CUSTOMER_CANCEL','PROVIDER_CONVENIENCE'];
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function subscription(id){return (Store.get().commercial?.subscriptions||[]).find(item=>item.id===id);}
function localDateTime(value=new Date()){const d=new Date(value);d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,16);}
function iso(value){return value?new Date(value).toISOString():undefined;}
function refreshSubscription(result){if(!result?.subscription)return;Store.update(draft=>{const rows=draft.commercial?.subscriptions||[];const index=rows.findIndex(item=>item.id===result.subscription.id);if(index>=0)rows[index]={...rows[index],...result.subscription};});}

function resultDialog(){
  let dialog=document.getElementById('cgProvisionResult');
  if(dialog)return dialog;
  dialog=document.createElement('dialog');dialog.id='cgProvisionResult';dialog.className='cg-device-dialog';
  dialog.innerHTML=`<header class="cg-device-dialog-head"><div><p class="cgx-eyebrow">Acceso multiempresa</p><h2>Credencial técnica creada</h2><p>La empresa quedó vinculada a la misma identidad global del usuario.</p></div><button type="button" class="cg-device-dialog-close" data-prov-close aria-label="Cerrar"><i class="fa-solid fa-xmark"></i></button></header><div class="cg-device-dialog-body" data-prov-body></div>`;
  document.body.appendChild(dialog);dialog.querySelector('[data-prov-close]')?.addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close();});return dialog;
}
function showResult(result){
  const dialog=resultDialog();const body=dialog.querySelector('[data-prov-body]');
  const lines=[`Empresa: ${result.tenant?.name||''} · ${result.tenant?.rif||''}`,`Correo: ${result.user?.email||''}`,`Licencia: ${result.licenseKey||''}`,result.temporaryPassword?`Contraseña temporal: ${result.temporaryPassword}`:'Contraseña: conserva la contraseña actual de esta identidad',`Módulos: ${(result.modules||[]).join(', ')}`];
  body.innerHTML=`<div class="panel-soft p-4 rounded-xl grid gap-3"><p><strong>${esc(result.user?.fullName||result.user?.email||'Usuario')}</strong></p><div class="cg-license-secret-grid"><span><small>Empresa</small><strong>${esc(result.tenant?.name||'')}</strong></span><span><small>RIF</small><strong>${esc(result.tenant?.rif||'')}</strong></span><span><small>Correo</small><strong>${esc(result.user?.email||'')}</strong></span><span><small>Licencia</small><code>${esc(result.licenseKey||'')}</code></span>${result.temporaryPassword?`<span><small>Contraseña temporal</small><code>${esc(result.temporaryPassword)}</code></span>`:''}</div><p class="cg-license-warning"><i class="fa-solid fa-shield-halved"></i> ${esc(result.note||'Guarda la licencia ahora.')}</p><button type="button" class="btn btn-primary" data-prov-copy><i class="fa-solid fa-copy"></i> Copiar credenciales</button></div>`;
  body.querySelector('[data-prov-copy]')?.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(lines.join('\n'));}catch{/* selección manual disponible */}});
  if(!dialog.open)dialog.showModal();
}

function governanceDialog(){
  let dialog=document.getElementById('cgRestrictionCaseDialog');
  if(dialog)return dialog;
  dialog=document.createElement('dialog');dialog.id='cgRestrictionCaseDialog';dialog.className='cg-device-dialog';
  dialog.innerHTML=`<header class="cg-device-dialog-head"><div><p class="cgx-eyebrow">Gobernanza comercial</p><h2 data-case-title>Expediente de restricción</h2><p>Las acciones restrictivas requieren motivo codificado, evidencia y trazabilidad.</p></div><button type="button" class="cg-device-dialog-close" data-case-close aria-label="Cerrar"><i class="fa-solid fa-xmark"></i></button></header><div class="cg-device-dialog-body" data-case-body></div>`;
  document.body.appendChild(dialog);dialog.querySelector('[data-case-close]')?.addEventListener('click',()=>dialog.close());return dialog;
}
function reasonOptions(values){return values.map(value=>`<option value="${value}">${value}</option>`).join('');}
function caseSummary({reasonCode,scope='subscription',evidenceRef,effectiveAt,noticeAt,cureDeadline,appealDeadline,targetStatus}){
  return `<div class="panel-soft p-4 rounded-xl grid gap-2" role="status"><strong>Revisa antes de ejecutar</strong><span><small>Motivo</small><br><code>${esc(reasonCode)}</code></span><span><small>Alcance</small><br>${esc(scope)}</span><span><small>Estado destino</small><br>${esc(targetStatus||'suspended')}</span><span><small>Evidencia</small><br>${esc(evidenceRef)}</span><span><small>Fecha efectiva</small><br>${esc(effectiveAt||'ahora')}</span>${noticeAt?`<span><small>Aviso</small><br>${esc(noticeAt)}</span>`:''}${cureDeadline?`<span><small>Subsanación</small><br>${esc(cureDeadline)}</span>`:''}${appealDeadline?`<span><small>Apelación</small><br>${esc(appealDeadline)}</span>`:''}</div>`;
}
function applyResult(result,message){refreshSubscription(result);const dialog=governanceDialog();const body=dialog.querySelector('[data-case-body]');body.innerHTML=`<div class="panel-soft p-4 rounded-xl grid gap-2"><strong>${esc(message)}</strong><span>Expediente: <code>${esc(result?.case?.id||result?.restrictionCaseId||'registrado')}</code></span></div><button type="button" class="btn btn-primary" data-case-done>Cerrar</button>`;body.querySelector('[data-case-done]')?.addEventListener('click',()=>{dialog.close();window.location.reload();});}
function showError(error){window.alert(error?.message||'No se pudo completar la operación gobernada.');}

async function openSuspend(id){
  const sub=subscription(id);if(!sub)return;const dialog=governanceDialog();dialog.querySelector('[data-case-title]').textContent=`Suspender · ${sub.customerName||'suscripción'}`;const body=dialog.querySelector('[data-case-body]');
  body.innerHTML=`<form data-restriction-form class="grid gap-3"><label>Motivo codificado<select class="input" name="reasonCode" required>${reasonOptions(SUSPEND_REASONS)}</select></label><label>Alcance<input class="input" value="subscription" disabled><input type="hidden" name="scope" value="subscription"></label><label>Referencia de evidencia<textarea class="input" name="evidenceRef" minlength="3" maxlength="1000" required placeholder="Ticket, incidente, pago conciliado, orden o referencia verificable"></textarea></label><label>Fecha efectiva<input class="input" name="effectiveAt" type="datetime-local" value="${localDateTime()}" required></label><label>Aviso previo (si aplica)<input class="input" name="noticeAt" type="datetime-local"></label><label>Fecha límite de subsanación (si aplica)<input class="input" name="cureDeadline" type="datetime-local"></label><label>Fecha límite de apelación (si aplica)<input class="input" name="appealDeadline" type="datetime-local"></label><button class="btn btn-danger" type="submit">Revisar suspensión</button></form><div data-case-confirm></div>`;
  const form=body.querySelector('[data-restriction-form]');form.addEventListener('submit',event=>{event.preventDefault();if(!form.reportValidity())return;const data=Object.fromEntries(new FormData(form));const payload={reasonCode:data.reasonCode,scope:'subscription',evidenceRef:data.evidenceRef,effectiveAt:iso(data.effectiveAt),noticeAt:iso(data.noticeAt),cureDeadline:iso(data.cureDeadline),appealDeadline:iso(data.appealDeadline)};const confirm=body.querySelector('[data-case-confirm]');confirm.innerHTML=`${caseSummary({...payload,targetStatus:'suspended'})}<button type="button" class="btn btn-danger" data-case-execute>Confirmar suspensión</button>`;confirm.querySelector('[data-case-execute]').addEventListener('click',async()=>{try{applyResult(await CommercialService.suspendSubscription(id,payload),'Suscripción suspendida con expediente auditable.');}catch(error){showError(error);}});});
  if(!dialog.open)dialog.showModal();
}

async function openReactivate(id){
  const sub=subscription(id);if(!sub)return;try{const cases=await CommercialService.restrictionCases(id);const original=(cases||[]).find(item=>item.action==='suspend'&&item.status==='open');if(!original){window.alert('No existe un expediente abierto de suspensión para reactivar.');return;}const dialog=governanceDialog();dialog.querySelector('[data-case-title]').textContent=`Reactivar · ${sub.customerName||'suscripción'}`;const body=dialog.querySelector('[data-case-body]');body.innerHTML=`${caseSummary({reasonCode:original.reasonCode,scope:original.scope,evidenceRef:original.evidenceRef,effectiveAt:original.effectiveAt,targetStatus:'active'})}<form data-reactivate-form class="grid gap-3"><label>Evidencia de corrección/reactivación<textarea class="input" name="evidenceRef" minlength="3" maxlength="1000" required placeholder="Pago conciliado, incidente cerrado o evidencia de subsanación"></textarea></label><label>Fecha efectiva<input class="input" name="effectiveAt" type="datetime-local" value="${localDateTime()}" required></label><button class="btn btn-primary" type="submit">Confirmar reactivación vinculada</button></form>`;body.querySelector('[data-reactivate-form]').addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget;if(!form.reportValidity())return;try{applyResult(await CommercialService.reactivateSubscription(id,{caseId:original.id,evidenceRef:form.elements.evidenceRef.value,effectiveAt:iso(form.elements.effectiveAt.value)}),'Suscripción reactivada y expediente original resuelto.');}catch(error){showError(error);}});if(!dialog.open)dialog.showModal();}catch(error){showError(error);}
}

async function openTerminate(id){
  const sub=subscription(id);if(!sub)return;try{const cases=await CommercialService.restrictionCases(id);const pending=(cases||[]).find(item=>item.action==='terminate'&&item.status==='pending_review');const dialog=governanceDialog();dialog.querySelector('[data-case-title]').textContent=`Terminar · ${sub.customerName||'suscripción'}`;const body=dialog.querySelector('[data-case-body]');
    if(pending){body.innerHTML=`<p class="cg-license-warning"><i class="fa-solid fa-user-shield"></i> Segunda revisión obligatoria. El backend rechazará al mismo actor que abrió el expediente.</p>${caseSummary({reasonCode:pending.reasonCode,scope:pending.scope,evidenceRef:pending.evidenceRef,effectiveAt:pending.effectiveAt,targetStatus:pending.targetStatus})}<button type="button" class="btn btn-danger" data-approve-termination>Aprobar terminación</button>`;body.querySelector('[data-approve-termination]').addEventListener('click',async()=>{try{applyResult(await CommercialService.terminateSubscription(id,{caseId:pending.id,confirm:true}),'Terminación aprobada por segundo revisor y auditada.');}catch(error){showError(error);}});}
    else {body.innerHTML=`<form data-terminate-form class="grid gap-3"><label>Motivo codificado<select class="input" name="reasonCode" required>${reasonOptions(TERMINATE_REASONS)}</select></label><label>Alcance<input class="input" value="subscription" disabled></label><label>Estado terminal<select class="input" name="terminalStatus"><option value="cancelled">cancelled</option><option value="expired">expired</option></select></label><label>Referencia de evidencia<textarea class="input" name="evidenceRef" minlength="3" maxlength="1000" required></textarea></label><label>Fecha efectiva<input class="input" name="effectiveAt" type="datetime-local" value="${localDateTime()}" required></label><label>Aviso previo (si aplica)<input class="input" name="noticeAt" type="datetime-local"></label><label>Fecha límite de subsanación (si aplica)<input class="input" name="cureDeadline" type="datetime-local"></label><label>Fecha límite de apelación (si aplica)<input class="input" name="appealDeadline" type="datetime-local"></label><button class="btn btn-danger" type="submit">Revisar solicitud de terminación</button></form><div data-case-confirm></div>`;const form=body.querySelector('[data-terminate-form]');form.addEventListener('submit',event=>{event.preventDefault();if(!form.reportValidity())return;const data=Object.fromEntries(new FormData(form));const payload={reasonCode:data.reasonCode,scope:'subscription',evidenceRef:data.evidenceRef,terminalStatus:data.terminalStatus,effectiveAt:iso(data.effectiveAt),noticeAt:iso(data.noticeAt),cureDeadline:iso(data.cureDeadline),appealDeadline:iso(data.appealDeadline)};const confirm=body.querySelector('[data-case-confirm]');confirm.innerHTML=`${caseSummary({...payload,targetStatus:payload.terminalStatus})}<p>Esta primera confirmación <strong>no termina</strong> la suscripción: abre un expediente pendiente de un segundo operador.</p><button type="button" class="btn btn-danger" data-case-execute>Crear expediente para segunda revisión</button>`;confirm.querySelector('[data-case-execute]').addEventListener('click',async()=>{try{applyResult(await CommercialService.terminateSubscription(id,payload),'Expediente de terminación abierto; requiere segundo revisor.');}catch(error){showError(error);}});});}
    if(!dialog.open)dialog.showModal();}catch(error){showError(error);}
}

async function provision(subscriptionId){
  const sub=subscription(subscriptionId);if(!sub)return;const tenants=(sub.tenants||[]).filter(item=>item.status==='active');if(!tenants.length){window.alert('Primero vincula al menos una empresa/RIF a esta suscripción.');return;}const choices=tenants.map(item=>`${item.rif} — ${item.name}`).join('\n');const rif=window.prompt(`RIF donde habilitar al usuario:\n\n${choices}`,tenants[0]?.rif||'');if(!rif)return;const tenant=tenants.find(item=>String(item.rif).trim().toUpperCase()===String(rif).trim().toUpperCase());if(!tenant){window.alert('Ese RIF no pertenece a las empresas activas de la suscripción.');return;}const email=window.prompt('Correo de la persona. Usa el mismo correo en los RIF que pertenezcan a la misma identidad:','');if(!email)return;const fullName=window.prompt('Nombre completo:','')||email;const devices=Number(window.prompt('Máximo de dispositivos para esta empresa:','2')||2);try{showResult(await CommercialService.provisionSubscriptionUser(subscriptionId,{tenantId:tenant.tenantId,email,fullName,maxDevices:Math.min(20,Math.max(1,devices))}));}catch(error){showError(error);}
}

function enhance(){
  document.querySelectorAll('[data-sub-tenant]').forEach(anchor=>{const cell=anchor.parentElement;if(!cell)return;if(!cell.querySelector('[data-sub-user]')){const button=document.createElement('button');button.type='button';button.className='btn btn-secondary';button.dataset.subUser=anchor.dataset.subTenant;button.title='Provisionar usuario en empresa contratada';button.innerHTML='<i class="fa-solid fa-user-plus"></i>';button.addEventListener('click',()=>provision(button.dataset.subUser));cell.insertBefore(button,anchor.nextSibling);}const id=anchor.dataset.subTenant;const sub=subscription(id);if(sub&&!['cancelled','expired'].includes(sub.status)&&!cell.querySelector('[data-sub-terminate]')){const terminate=document.createElement('button');terminate.type='button';terminate.className='btn btn-danger';terminate.dataset.subTerminate=id;terminate.title='Terminar con expediente y segunda revisión';terminate.setAttribute('aria-label','Terminar suscripción con expediente');terminate.innerHTML='<i class="fa-solid fa-file-circle-xmark"></i>';terminate.addEventListener('click',()=>openTerminate(id));cell.appendChild(terminate);}});
  document.querySelectorAll('[data-sub-toggle]:not([data-governance-bound])').forEach(oldButton=>{const id=oldButton.dataset.subToggle;const clone=oldButton.cloneNode(true);clone.dataset.governanceBound='true';clone.addEventListener('click',()=>{const sub=subscription(id);if(!sub)return;if(sub.status==='suspended')openReactivate(id);else openSuspend(id);});oldButton.replaceWith(clone);});
}

export function installCommercialAccessEnhancer(){if(installed||typeof document==='undefined')return;installed=true;const observer=new MutationObserver(()=>enhance());observer.observe(document.documentElement,{childList:true,subtree:true});queueMicrotask(enhance);}