import { FitnessRoutineService } from './fitnessRoutineService.js';
import { FitnessNutritionService } from './fitnessNutritionService.js';
import { FitnessClientTransferService } from './fitnessClientTransferService.js';
import { GymVerticalService } from './verticalService.js';
import { Store } from '../state/store.js';
import { Toast } from '../components/toast.js';
import { escapeHtml } from '../utils/dom.js';

const rows=(value)=>Array.isArray(value)?value:value?.data||[];
const option=(value,label)=>`<option value="${escapeHtml(value)}">${escapeHtml(label)}</option>`;
const copy=async(text)=>{if(navigator.clipboard?.writeText)return navigator.clipboard.writeText(text);const area=document.createElement('textarea');area.value=text;document.body.append(area);area.select();document.execCommand('copy');area.remove();};
const memberSelect=(members)=>`<select data-fast-client><option value="">Usuario test / sin registrar</option>${members.map((member)=>option(member.id,member.fullName)).join('')}</select>`;
const resultExercises=(routine)=>`<div class="cg-fast-result"><header><div><strong>${escapeHtml(routine.name)}</strong><small>${escapeHtml(routine.impact)}</small></div><span>${routine.totalSets} series</span></header><p><b>Calentamiento:</b> ${escapeHtml(routine.warmup)}</p><div class="cg-fast-exercises">${routine.exercises.map((item)=>`<article><div><strong>${escapeHtml(item.name)}</strong><small>${escapeHtml(item.muscle)} · ${escapeHtml(item.equipment)}</small></div><span>${item.sets} × ${escapeHtml(item.reps)} · ${item.restSeconds}s</span><p>${escapeHtml(item.cue)}</p></article>`).join('')}</div></div>`;
const resultNutrition=(plan)=>plan.blocked?`<div class="cg-fast-warning">${escapeHtml(plan.reason)}</div>`:`<div class="cg-fast-result"><header><div><strong>${escapeHtml(plan.goal)}</strong><small>${plan.calories} kcal · P ${plan.proteinG}g · C ${plan.carbsG}g · G ${plan.fatG}g · agua ${plan.waterMl} ml</small></div><span>${plan.days.length} día(s)</span></header><div class="cg-fast-meal-days">${plan.days.map((day)=>`<article><strong>Día ${day.day}</strong>${day.meals.map((meal)=>`<p><b>${escapeHtml(meal.type)}:</b> ${escapeHtml(meal.name)} · ~${meal.calories} kcal<br><small>${escapeHtml(meal.items)}</small></p>`).join('')}</article>`).join('')}</div><p class="cg-fast-disclaimer">${escapeHtml(plan.disclaimer)}</p></div>`;

function routineTool(state,{Toast}){
  const host=document.querySelector('[data-gym-panel="routines"]');if(!host||host.querySelector('[data-fast-routine]'))return;
  const members=rows(state.gymVertical?.members);const card=document.createElement('section');card.className='cg-gym-v1124-card cg-fast-coach';card.dataset.fastRoutine='true';
  card.innerHTML=`<header><div><h3>Rutina rápida del entrenador</h3><p>Usa “usuario test” para resolver una sesión cara a cara sin registrar al cliente. Selecciona músculos y nivel; ContaGest arma ejercicios, series, repeticiones, descanso e indicaciones.</p></div><span class="cg-fast-badge">Sin formulario largo</span></header><div class="cg-fast-grid"><label><span>Cliente opcional</span>${memberSelect(members)}</label><label><span>Nivel</span><select data-fast-level><option>Principiante</option><option selected>Intermedio</option><option>Avanzado</option></select></label><label><span>Objetivo</span><select data-fast-goal><option>Hipertrofia / volumen</option><option>Fuerza</option><option>Resistencia muscular</option><option>Potencia / acondicionamiento</option></select></label><label><span>Duración</span><select data-fast-duration><option value="40">40 min</option><option value="60" selected>60 min</option><option value="80">80 min</option><option value="100">100 min</option></select></label></div><div class="cg-fast-field"><span>Músculos de hoy</span><div class="cg-fast-chips">${FitnessRoutineService.muscles.map((muscle)=>`<label><input type="checkbox" value="${escapeHtml(muscle)}" data-fast-muscle ${['Pecho','Tríceps'].includes(muscle)?'checked':''}><span>${escapeHtml(muscle)}</span></label>`).join('')}</div></div><label class="cg-fast-field"><span>Nota rápida del entrenador</span><input data-fast-routine-note placeholder="Ej.: priorizar técnica, no superseries hoy"></label><div class="cg-fast-actions"><button type="button" class="cgx-btn cgx-btn-primary" data-fast-generate-routine>Generar sugerencia</button><button type="button" class="cgx-btn cgx-btn-secondary" data-fast-copy-routine disabled>Copiar para WhatsApp</button><button type="button" class="cgx-btn cgx-btn-secondary" data-fast-save-routine disabled>Guardar al cliente</button></div><div data-fast-routine-result></div>`;
  host.prepend(card);let generated=null;
  card.querySelector('[data-fast-generate-routine]').addEventListener('click',()=>{const muscles=[...card.querySelectorAll('[data-fast-muscle]:checked')].map((input)=>input.value);if(!muscles.length)return Toast.show('Selecciona al menos un grupo muscular.','warning');generated=FitnessRoutineService.generate({muscles,level:card.querySelector('[data-fast-level]').value,goal:card.querySelector('[data-fast-goal]').value,durationMin:card.querySelector('[data-fast-duration]').value,notes:card.querySelector('[data-fast-routine-note]').value});card.querySelector('[data-fast-routine-result]').innerHTML=resultExercises(generated);card.querySelector('[data-fast-copy-routine]').disabled=false;card.querySelector('[data-fast-save-routine]').disabled=!card.querySelector('[data-fast-client]').value;});
  card.querySelector('[data-fast-client]').addEventListener('change',(event)=>{card.querySelector('[data-fast-save-routine]').disabled=!generated||!event.target.value;});
  card.querySelector('[data-fast-copy-routine]').addEventListener('click',async()=>{if(!generated)return;const client=members.find((item)=>item.id===card.querySelector('[data-fast-client]').value);await copy(FitnessRoutineService.whatsapp(generated,{clientName:client?.fullName||'',guest:!client}));Toast.show('Rutina copiada. En usuario test no se incluye un nombre ficticio.','success');});
  card.querySelector('[data-fast-save-routine]').addEventListener('click',async()=>{if(!generated)return;const memberId=card.querySelector('[data-fast-client]').value;if(!memberId)return Toast.show('Selecciona un cliente real para guardar.','warning');try{await GymVerticalService.createRoutine({memberId,trainerId:null,name:generated.name,goal:generated.goal,level:generated.level.toLowerCase(),daysPerWeek:1,exercises:FitnessRoutineService.toApiExercises(generated),notes:generated.notes,active:true});Toast.show('Rutina guardada al cliente.','success');}catch(error){Toast.show(`No se pudo guardar: ${error.message}`,'error');}});
}

function nutritionTool(state,{Toast}){
  const host=document.querySelector('[data-gym-panel="nutrition"]');if(!host||host.querySelector('[data-fast-nutrition]'))return;const members=rows(state.gymVertical?.members);const card=document.createElement('section');card.className='cg-gym-v1124-card cg-fast-coach';card.dataset.fastNutrition='true';
  card.innerHTML=`<header><div><h3>Plan nutricional rápido</h3><p>Genera una propuesta editable por objetivos. El modo test funciona sin registrar al cliente y bloquea situaciones que requieren evaluación profesional.</p></div><span class="cg-fast-badge">1–7 días</span></header><div class="cg-fast-grid"><label><span>Cliente opcional</span>${memberSelect(members)}</label><label><span>Objetivo</span><select data-nut-goal><option>Pérdida de grasa</option><option>Mantenimiento</option><option>Ganancia de masa</option></select></label><label><span>Peso kg</span><input type="number" min="35" max="250" value="75" data-nut-weight></label><label><span>Altura cm</span><input type="number" min="130" max="230" value="175" data-nut-height></label><label><span>Edad</span><input type="number" min="18" max="90" value="30" data-nut-age></label><label><span>Sexo para estimación</span><select data-nut-sex><option value="other">No especificar</option><option value="female">Femenino</option><option value="male">Masculino</option></select></label><label><span>Actividad</span><select data-nut-activity><option value="light">Ligera</option><option value="moderate" selected>Moderada</option><option value="high">Alta</option></select></label><label><span>Preferencia</span><select data-nut-pref><option>Equilibrada</option><option>Vegetariana</option><option>Vegana</option></select></label><label><span>Días</span><select data-nut-days><option>1</option><option>3</option><option selected>7</option></select></label></div><label class="cg-fast-check"><input type="checkbox" data-nut-risk><span>Existe embarazo, trastorno alimentario, enfermedad renal/metabólica, medicación relevante o dieta terapéutica</span></label><div class="cg-fast-actions"><button type="button" class="cgx-btn cgx-btn-primary" data-fast-generate-nutrition>Generar plan</button><button type="button" class="cgx-btn cgx-btn-secondary" data-fast-copy-nutrition disabled>Copiar para WhatsApp</button><button type="button" class="cgx-btn cgx-btn-secondary" data-fast-save-nutrition disabled>Guardar al cliente</button></div><div data-fast-nutrition-result></div>`;
  host.prepend(card);let generated=null;
  card.querySelector('[data-fast-generate-nutrition]').addEventListener('click',()=>{generated=FitnessNutritionService.generate({goal:card.querySelector('[data-nut-goal]').value,weightKg:card.querySelector('[data-nut-weight]').value,heightCm:card.querySelector('[data-nut-height]').value,age:card.querySelector('[data-nut-age]').value,sex:card.querySelector('[data-nut-sex]').value,activity:card.querySelector('[data-nut-activity]').value,preference:card.querySelector('[data-nut-pref]').value,days:card.querySelector('[data-nut-days]').value,clinicalRisk:card.querySelector('[data-nut-risk]').checked});card.querySelector('[data-fast-nutrition-result]').innerHTML=resultNutrition(generated);card.querySelector('[data-fast-copy-nutrition]').disabled=false;card.querySelector('[data-fast-save-nutrition]').disabled=generated.blocked||!card.querySelector('[data-fast-client]').value;});
  card.querySelector('[data-fast-client]').addEventListener('change',(event)=>{card.querySelector('[data-fast-save-nutrition]').disabled=!generated||generated.blocked||!event.target.value;});
  card.querySelector('[data-fast-copy-nutrition]').addEventListener('click',async()=>{if(!generated)return;const client=members.find((item)=>item.id===card.querySelector('[data-fast-client]').value);await copy(FitnessNutritionService.whatsapp(generated,{clientName:client?.fullName||'',guest:!client}));Toast.show('Plan copiado para WhatsApp.','success');});
  card.querySelector('[data-fast-save-nutrition]').addEventListener('click',async()=>{if(!generated||generated.blocked)return;const memberId=card.querySelector('[data-fast-client]').value;if(!memberId)return;try{await GymVerticalService.createNutrition({memberId,trainerId:null,name:`Plan ${generated.goal} · ${generated.days.length} días`,goal:generated.goal,targetCalories:generated.calories,waterMl:generated.waterMl,meals:FitnessNutritionService.toApiMeals(generated),notes:generated.disclaimer,active:true});Toast.show('Plan nutricional guardado.','success');}catch(error){Toast.show(`No se pudo guardar: ${error.message}`,'error');}});
}

function fastBirthDate(){const input=document.querySelector('#gymMemberForm input[name="birthDate"]');if(!input||input.dataset.fastDob)return;input.dataset.fastDob='true';input.type='hidden';const current=String(input.value||'').split('-');const box=document.createElement('div');box.className='cg-fast-dob';box.innerHTML=`<span>Fecha de nacimiento</span><div><input type="number" min="1" max="31" inputmode="numeric" placeholder="Día" value="${escapeHtml(current[2]||'')}" data-dob-day><select data-dob-month><option value="">Mes</option>${['Ene','Feb','Mar','Abr','May','Jun','Jul','Ago','Sep','Oct','Nov','Dic'].map((name,index)=>`<option value="${String(index+1).padStart(2,'0')}" ${current[1]===String(index+1).padStart(2,'0')?'selected':''}>${name}</option>`).join('')}</select><input type="number" min="1900" max="2100" inputmode="numeric" placeholder="Año" value="${escapeHtml(current[0]||'')}" data-dob-year></div><small>Día / mes / año, sin recorrer un calendario por décadas.</small>`;input.after(box);const sync=()=>{const d=box.querySelector('[data-dob-day]').value.padStart(2,'0'),m=box.querySelector('[data-dob-month]').value,y=box.querySelector('[data-dob-year]').value;input.value=d&&m&&y.length===4?`${y}-${m}-${d}`:'';};box.addEventListener('input',sync);box.addEventListener('change',sync);}

function transferTool(state,{Store,Toast}){const host=document.querySelector('[data-gym-panel="members"]');if(!host||host.querySelector('[data-client-transfer]'))return;fastBirthDate();const members=rows(state.gymVertical?.members),card=document.createElement('section');card.className='cg-gym-v1124-card cg-client-transfer';card.dataset.clientTransfer='true';card.innerHTML=`<header><div><h3>Importar / exportar clientes</h3><p>Formato CSV compatible con Excel. Descarga la plantilla, complétala y vuelve a subirla para evitar registrar cliente por cliente.</p></div></header><div class="cg-fast-actions"><button type="button" class="cgx-btn cgx-btn-secondary" data-client-template>Descargar plantilla</button><button type="button" class="cgx-btn cgx-btn-secondary" data-client-export>Exportar ${members.length} clientes</button><label class="cgx-btn cgx-btn-primary cg-file-button">Importar lista<input type="file" accept=".csv,text/csv" data-client-import hidden></label></div><div data-client-import-status class="cg-fast-disclaimer"></div>`;host.prepend(card);
  card.querySelector('[data-client-template]').addEventListener('click',()=>FitnessClientTransferService.download('plantilla-clientes-gimnasio.csv',FitnessClientTransferService.template()));card.querySelector('[data-client-export]').addEventListener('click',()=>FitnessClientTransferService.download('clientes-gimnasio.csv',FitnessClientTransferService.export(members)));
  card.querySelector('[data-client-import]').addEventListener('change',async(event)=>{const file=event.target.files?.[0];if(!file)return;try{const parsed=FitnessClientTransferService.parse(await file.text());if(!parsed.length)return Toast.show('La plantilla no contiene clientes válidos.','warning');const created=[];for(const payload of parsed)created.push(await GymVerticalService.createMember(payload));Store.update((draft)=>{draft.gymVertical=draft.gymVertical||{};draft.gymVertical.members=[...created,...(draft.gymVertical.members||[])];});card.querySelector('[data-client-import-status]').textContent=`${created.length} cliente(s) importados correctamente.`;Toast.show(`${created.length} clientes importados.`,'success');}catch(error){Toast.show(`No se pudo importar: ${error.message}`,'error');}});
}

export const FitnessProductivityEnhancer={mount(state,context={}){const page=document.querySelector('.cg-gym-page');if(!page)return;const tab=document.querySelector('[data-gym-panel]')?.dataset.gymPanel;requestAnimationFrame(()=>{if(tab==='routines')routineTool(state,context);if(tab==='nutrition')nutritionTool(state,context);if(tab==='members')transferTool(state,context);});}};

let observerInstalled=false;
export function installFitnessProductivityEnhancer(){
  if(observerInstalled||typeof document==='undefined')return;observerInstalled=true;
  let queued=false;const mount=()=>{queued=false;FitnessProductivityEnhancer.mount(Store.get(),{Store,Toast});};
  const observer=new MutationObserver(()=>{if(queued)return;queued=true;requestAnimationFrame(mount);});
  observer.observe(document.documentElement,{childList:true,subtree:true});
  requestAnimationFrame(mount);
}
