const MEALS=[
  ['Avena proteica con yogur y fruta','Desayuno','Vegetariana',480,30,62,13,'Avena, yogur griego, fruta, canela y semillas.'],['Arepa con huevos y aguacate','Desayuno','Equilibrada',500,27,48,22,'Arepa medida, huevos/claras, aguacate y vegetales.'],['Tostadas integrales con pavo','Desayuno','Equilibrada',430,32,49,12,'Pan integral, pavo, queso ligero, tomate y fruta.'],
  ['Bowl de pollo, arroz y vegetales','Almuerzo','Equilibrada',620,47,72,17,'Pollo, arroz, vegetales y aceite medido.'],['Carne magra, papa y ensalada','Almuerzo','Equilibrada',610,44,64,19,'Carne magra, papa, ensalada y aceite medido.'],['Pasta integral con atún','Almuerzo','Equilibrada',590,42,73,14,'Pasta integral, atún, tomate y vegetales.'],['Lentejas con arroz y vegetales','Almuerzo','Vegana',540,24,92,9,'Lentejas, arroz, vegetales y aguacate medido.'],['Tofu salteado con arroz','Almuerzo','Vegana',560,29,69,19,'Tofu, arroz y vegetales.'],
  ['Merluza con papa y ensalada','Cena','Equilibrada',470,42,47,12,'Pescado blanco, papa y ensalada fresca.'],['Omelette de vegetales','Cena','Equilibrada',350,38,18,14,'Huevos, claras, champiñón, espinaca y tomate.'],['Ensalada tibia de pollo','Cena','Equilibrada',440,43,39,12,'Pollo, papa medida, hojas verdes, tomate y pepino.'],['Crema de calabaza con lentejas','Cena','Vegana',390,19,65,7,'Calabaza, lentejas, cebolla y especias.'],
  ['Yogur con fruta y nueces','Snack','Vegetariana',320,22,34,12,'Yogur griego, fruta y nueces medidas.'],['Banana con mantequilla de maní','Snack','Vegana',250,6,33,11,'Banana y mantequilla de maní medida.'],['Huevos cocidos con fruta','Snack','Equilibrada',260,13,25,12,'2 huevos y una fruta.'],['Hummus, vegetales y pita','Snack','Vegana',340,12,48,12,'Hummus, zanahoria, pepino y pita pequeña.']
];
const norm=(value)=>String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const clamp=(value,min,max)=>Math.min(max,Math.max(min,Number(value)||0));
const factor=(value)=>({low:1.25,light:1.4,moderate:1.55,high:1.72}[value]||1.4);
function guard(input){const age=Number(input.age||0);if(age&&age<18)return'El plan automático no se usa para menores de 18 años.';if(input.clinicalRisk)return'Embarazo, trastorno alimentario, enfermedad renal/metabólica, medicación relevante o dieta terapéutica requieren evaluación profesional.';return'';}
function targetCalories(input){const weight=clamp(input.weightKg,35,250),height=clamp(input.heightCm,130,230),age=clamp(input.age,18,90);if(!weight||!height||!age)return Number(input.targetCalories||0)||0;const base=10*weight+6.25*height-5*age+(input.sex==='male'?5:input.sex==='female'?-161:-78);const tdee=base*factor(input.activity),goal=norm(input.goal);const modifier=goal.includes('perd')||goal.includes('def')?.85:goal.includes('gan')||goal.includes('vol')?1.10:1;return Math.round(clamp(tdee*modifier,1200,5000));}
function compatible(meal,preference){const pref=norm(preference),type=norm(meal[2]);if(pref.includes('vegan'))return type.includes('vegana');if(pref.includes('veget'))return type.includes('veget')||type.includes('vegana');return true;}
function scale(meal,target){const ratio=clamp(target/meal[3],.65,1.55);return{name:meal[0],type:meal[1],calories:Math.round(meal[3]*ratio),protein:Math.round(meal[4]*ratio),carbs:Math.round(meal[5]*ratio),fat:Math.round(meal[6]*ratio),items:meal[7]};}

export const FitnessNutritionService={
  generate(input={}){
    const reason=guard(input);if(reason)return{blocked:true,reason};
    const calories=targetCalories(input)||Math.round(clamp(input.targetCalories||2000,1200,5000));const weight=clamp(input.weightKg||70,35,250),goal=String(input.goal||'Mantenimiento'),proteinG=Math.round(weight*(norm(goal).includes('gan')?1.8:1.6)),fatG=Math.round((calories*.28)/9),carbsG=Math.max(0,Math.round((calories-proteinG*4-fatG*9)/4)),waterMl=Math.round(clamp(weight*35,1500,5000)),dayCount=clamp(input.days||7,1,7),preference=String(input.preference||'Equilibrada'),pool=MEALS.filter((meal)=>compatible(meal,preference)),distribution={Desayuno:.25,Almuerzo:.35,Cena:.28,Snack:.12},days=[];
    for(let day=0;day<dayCount;day+=1){days.push({day:day+1,meals:['Desayuno','Almuerzo','Cena','Snack'].map((type,index)=>{const options=pool.filter((meal)=>norm(meal[1]).includes(norm(type))),meal=options[(day+index*2)%Math.max(1,options.length)]||pool[(day+index)%pool.length];return scale(meal,calories*distribution[type]);})});}
    return{blocked:false,goal,calories,proteinG,carbsG,fatG,waterMl,preference,days,disclaimer:'Plan orientativo para adultos generalmente sanos. Porciones reales, alergias, preferencias y evaluación profesional prevalecen sobre estas estimaciones.'};
  },
  toApiMeals(plan){return plan.days.flatMap((day)=>day.meals.map((meal,index)=>({dayOfWeek:day.day,sortOrder:index+1,mealType:meal.type,items:[meal.items],calories:meal.calories,proteinG:meal.protein,carbsG:meal.carbs,fatG:meal.fat,notes:'Sugerencia editable generada por ContaGest.'})));},
  whatsapp(plan,{clientName='',guest=true}={}){
    if(plan.blocked)return`⚠️ ${plan.reason}`;const lines=[`🥗 PLAN ORIENTATIVO · ${plan.goal}`,`Objetivo diario aprox.: ${plan.calories} kcal · ${plan.proteinG}g proteína · ${plan.carbsG}g carbohidratos · ${plan.fatG}g grasas · agua ~${plan.waterMl} ml`,''];
    plan.days.forEach((day)=>{lines.push(`DÍA ${day.day}`);day.meals.forEach((meal)=>lines.push(`• ${meal.type}: ${meal.name} · ~${meal.calories} kcal\n  ${meal.items}`));lines.push('');});lines.push(plan.disclaimer);if(!guest&&clientName)lines.unshift(`Para: ${clientName}`);return lines.join('\n');
  }
};
