-- #561 · Superseded compatibility migration.
--
-- The authoritative fiscal schema for this release is created by the immediately
-- preceding migration `20260927143000_fiscal_authority_v561`. An earlier parallel
-- implementation of #561 created the same table names with a different contract
-- (`code/payload`, UUID tenant ids, a second FiscalSequence shape, and trigger-based
-- close evidence). Applying both migrations cannot produce the repository's
-- canonical fiscal repository/routes contract.
--
-- Keep this migration directory as a no-op so Prisma migration history remains
-- ordered and deterministic without creating a second incompatible authority.
