-- ContaGest Supabase keepalive
-- Deployed in production on 2026-08-09.
-- Purpose: generate lightweight API + database activity without touching business tables.
--
-- The production project stores the project URL and publishable key in Supabase Vault
-- under these names:
--   contagest_project_url
--   contagest_publishable_key
--
-- Do not commit service-role credentials here.

create extension if not exists pg_cron with schema extensions;
create extension if not exists pg_net with schema extensions;
create extension if not exists supabase_vault with schema vault;

create table if not exists public.contagest_keepalive (
  id bigint generated by default as identity primary key,
  source text not null default 'manual',
  created_at timestamptz not null default now()
);

alter table public.contagest_keepalive enable row level security;

-- Schedule once per day at 03:17 UTC. The Edge Function performs the database write.
-- Vault secrets must already exist before running this block on a new project.
select cron.schedule(
  'contagest-daily-keepalive',
  '17 3 * * *',
  $$
  select net.http_post(
    url := (select decrypted_secret from vault.decrypted_secrets where name = 'contagest_project_url') || '/functions/v1/contagest-keepalive',
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'Authorization', 'Bearer ' || (select decrypted_secret from vault.decrypted_secrets where name = 'contagest_publishable_key'),
      'apikey', (select decrypted_secret from vault.decrypted_secrets where name = 'contagest_publishable_key')
    ),
    body := jsonb_build_object('source', 'pg_cron')
  );
  $$
);
