-- Control Hípico v1.13 RC2 — reproducible workspace sync and least privilege.
-- Apply after hipico_v12_operations.sql and hipico_v12_shadow_validation.sql.

create extension if not exists pgcrypto;

create table if not exists public.hipico_workspaces (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null unique,
  name text not null default 'Control Hípico',
  state jsonb not null default '{}'::jsonb check (jsonb_typeof(state) = 'object'),
  version bigint not null default 1 check (version > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.hipico_profiles (
  owner_id uuid primary key,
  display_name text not null default 'Administrador Hípico',
  role text not null default 'operator' check (role in ('operator', 'admin')),
  preferences jsonb not null default '{}'::jsonb check (jsonb_typeof(preferences) = 'object'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.hipico_audit_events (
  id bigint generated by default as identity primary key,
  owner_id uuid not null,
  workspace_id uuid references public.hipico_workspaces(id) on delete set null,
  action text not null,
  entity_type text not null,
  entity_id text,
  payload jsonb not null default '{}'::jsonb check (jsonb_typeof(payload) = 'object'),
  created_at timestamptz not null default now()
);

create index if not exists hipico_audit_owner_time_idx
  on public.hipico_audit_events(owner_id, created_at desc);

alter table public.hipico_workspaces enable row level security;
alter table public.hipico_profiles enable row level security;
alter table public.hipico_audit_events enable row level security;

drop policy if exists hipico_workspaces_select_own on public.hipico_workspaces;
drop policy if exists hipico_workspaces_insert_own on public.hipico_workspaces;
drop policy if exists hipico_workspaces_update_own on public.hipico_workspaces;
drop policy if exists hipico_workspaces_delete_own on public.hipico_workspaces;
create policy hipico_workspaces_select_own on public.hipico_workspaces
  for select to authenticated using (owner_id = (select auth.uid()));
create policy hipico_workspaces_insert_own on public.hipico_workspaces
  for insert to authenticated with check (owner_id = (select auth.uid()));
create policy hipico_workspaces_update_own on public.hipico_workspaces
  for update to authenticated using (owner_id = (select auth.uid()))
  with check (owner_id = (select auth.uid()));

drop policy if exists hipico_profiles_select_own on public.hipico_profiles;
drop policy if exists hipico_profiles_insert_own on public.hipico_profiles;
drop policy if exists hipico_profiles_update_own on public.hipico_profiles;
create policy hipico_profiles_select_own on public.hipico_profiles
  for select to authenticated using (owner_id = (select auth.uid()));
create policy hipico_profiles_insert_own on public.hipico_profiles
  for insert to authenticated with check (owner_id = (select auth.uid()));
create policy hipico_profiles_update_own on public.hipico_profiles
  for update to authenticated using (owner_id = (select auth.uid()))
  with check (owner_id = (select auth.uid()));

drop policy if exists hipico_audit_select_own on public.hipico_audit_events;
drop policy if exists hipico_audit_insert_own on public.hipico_audit_events;
create policy hipico_audit_select_own on public.hipico_audit_events
  for select to authenticated using (owner_id = (select auth.uid()));
create policy hipico_audit_insert_own on public.hipico_audit_events
  for insert to authenticated with check (owner_id = (select auth.uid()));

create or replace function public.hipico_get_workspace()
returns setof public.hipico_workspaces
language sql
stable
security invoker
set search_path = public, pg_temp
as $$
  select workspace.*
  from public.hipico_workspaces workspace
  where workspace.owner_id = (select auth.uid())
  order by workspace.updated_at desc
  limit 1;
$$;

create or replace function public.hipico_save_workspace(
  p_name text,
  p_state jsonb,
  p_expected_version bigint default 0
)
returns public.hipico_workspaces
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
  v_uid uuid := auth.uid();
  v_row public.hipico_workspaces;
  v_expected bigint := greatest(coalesce(p_expected_version, 0), 0);
begin
  if v_uid is null then
    raise exception 'HIPICO_AUTH_REQUIRED' using errcode = '42501';
  end if;
  if p_state is null or jsonb_typeof(p_state) <> 'object' then
    raise exception 'HIPICO_INVALID_STATE' using errcode = '22023';
  end if;

  select * into v_row
  from public.hipico_workspaces
  where owner_id = v_uid
  for update;

  if not found then
    insert into public.hipico_workspaces(owner_id, name, state, version, created_at, updated_at)
    values (v_uid, coalesce(nullif(trim(p_name), ''), 'Control Hípico'), p_state, 1, now(), now())
    returning * into v_row;
    return v_row;
  end if;

  if v_expected > 0 and v_row.version <> v_expected then
    raise exception 'HIPICO_VERSION_CONFLICT expected %, current %', v_expected, v_row.version
      using errcode = '40001';
  end if;

  update public.hipico_workspaces
  set name = coalesce(nullif(trim(p_name), ''), name),
      state = p_state,
      version = version + 1,
      updated_at = now()
  where id = v_row.id
  returning * into v_row;
  return v_row;
end;
$$;

create or replace function public.hipico_get_profile()
returns public.hipico_profiles
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
  v_uid uuid := auth.uid();
  v_profile public.hipico_profiles;
begin
  if v_uid is null then
    raise exception 'HIPICO_AUTH_REQUIRED' using errcode = '42501';
  end if;
  select * into v_profile from public.hipico_profiles where owner_id = v_uid;
  if not found then
    insert into public.hipico_profiles(owner_id, display_name, role)
    values (v_uid, coalesce(auth.jwt() -> 'user_metadata' ->> 'name', 'Operador Hípico'), 'operator')
    returning * into v_profile;
  end if;
  return v_profile;
end;
$$;

create or replace function public.hipico_append_audit(
  p_workspace_id uuid,
  p_action text,
  p_entity_type text,
  p_entity_id text,
  p_payload jsonb default '{}'::jsonb
)
returns bigint
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
  v_uid uuid := auth.uid();
  v_id bigint;
begin
  if v_uid is null then
    raise exception 'HIPICO_AUTH_REQUIRED' using errcode = '42501';
  end if;
  if p_workspace_id is not null and not exists (
    select 1 from public.hipico_workspaces
    where id = p_workspace_id and owner_id = v_uid
  ) then
    raise exception 'HIPICO_WORKSPACE_FORBIDDEN' using errcode = '42501';
  end if;
  insert into public.hipico_audit_events(owner_id, workspace_id, action, entity_type, entity_id, payload)
  values (
    v_uid,
    p_workspace_id,
    coalesce(nullif(trim(p_action), ''), 'unknown'),
    coalesce(nullif(trim(p_entity_type), ''), 'unknown'),
    nullif(trim(p_entity_id), ''),
    coalesce(p_payload, '{}'::jsonb)
  ) returning id into v_id;
  return v_id;
end;
$$;

revoke all on table public.hipico_workspaces, public.hipico_profiles, public.hipico_audit_events from anon, authenticated;
grant select, insert, update on table public.hipico_workspaces, public.hipico_profiles to authenticated;
grant select, insert on table public.hipico_audit_events to authenticated;
grant usage, select on sequence public.hipico_audit_events_id_seq to authenticated;

revoke all on table
  public.hipico_bot_channels,
  public.hipico_messages,
  public.hipico_operation_events,
  public.hipico_outbox,
  public.hipico_ledger_entries,
  public.hipico_reconciliations,
  public.hipico_shadow_evaluations
from anon, authenticated;
grant select on table
  public.hipico_bot_channels,
  public.hipico_messages,
  public.hipico_operation_events,
  public.hipico_reconciliations,
  public.hipico_shadow_evaluations
to authenticated;

revoke all on function public.hipico_get_workspace() from public, anon;
revoke all on function public.hipico_save_workspace(text, jsonb, bigint) from public, anon;
revoke all on function public.hipico_get_profile() from public, anon;
revoke all on function public.hipico_append_audit(uuid, text, text, text, jsonb) from public, anon;
grant execute on function public.hipico_get_workspace() to authenticated;
grant execute on function public.hipico_save_workspace(text, jsonb, bigint) to authenticated;
grant execute on function public.hipico_get_profile() to authenticated;
grant execute on function public.hipico_append_audit(uuid, text, text, text, jsonb) to authenticated;

comment on function public.hipico_save_workspace(text, jsonb, bigint)
  is 'Owner-scoped optimistic workspace sync for Control Hípico.';
