import { Router } from 'express';
import { prisma } from '../database/prisma.js';
import { requireTenant } from '../shared/middleware/context.js';
import { createCrudRouter } from './crud.factory.js';
import { clientSchema, supplierSchema, productSchema, bankAccountSchema, employeeSchema, taxPeriodSchema, tenantSchema } from './schemas.js';
import salesRoutes from './sales/sales.routes.js';
import purchasesRoutes from './purchases/purchases.routes.js';
import accountingRoutes from './accounting/accounting.routes.js';
import reportsRoutes from './reports/reports.routes.js';
import moduleRoutes from './modules/modules.routes.js';
import currencyRoutes from './currency/currency.routes.js';
import exportRoutes from './exports/exports.routes.js';
import chartAccountRoutes from './chart-accounts/chart-accounts.routes.js';
import hrRoutes from './hr/hr.routes.js';
import fiscalRoutes from './fiscal/fiscal.routes.js';
import analyticsRoutes from './analytics/analytics.routes.js';
import qrRoutes from './qr/qr.routes.js';
import foodRoutes from './food/food.routes.js';
import notificationRoutes from './notifications/notifications.routes.js';
import mapsRoutes from './maps/maps.routes.js';
import aiRoutes from './ai/ai.routes.js';
import demosRoutes from './demos/demos.routes.js';
import pretestingRoutes from './pretesting/pretesting.routes.js';
import licenseRoutes from './licenses/licenses.routes.js';
import importRoutes from './imports/imports.routes.js';
import regulatoryRoutes from './regulatory/regulatory.routes.js';
import rulesRoutes from './rules/rules.routes.js';
import rbacRoutes from './rbac/rbac.routes.js';

const router = Router();
router.use('/tenants', createCrudRouter({ model: 'tenant' as any, entity: 'tenant', permission: 'admin.manage', schema: tenantSchema, tenantScoped: false, searchFields: ['name','rif'] }));
router.use('/clients', createCrudRouter({ model: 'client' as any, entity: 'client', permission: 'clients.manage', schema: clientSchema, searchFields: ['name','rif'] }));
router.use('/suppliers', createCrudRouter({ model: 'supplier' as any, entity: 'supplier', permission: 'purchases.manage', schema: supplierSchema, searchFields: ['name','rif'] }));
router.use('/products', createCrudRouter({ model: 'product' as any, entity: 'product', permission: 'inventory.manage', schema: productSchema, searchFields: ['name','sku'] }));
router.use('/bank-accounts', createCrudRouter({ model: 'bankAccount' as any, entity: 'bankAccount', permission: 'banking.manage', schema: bankAccountSchema, searchFields: ['bankName','accountNo'] }));
router.use('/employees', createCrudRouter({ model: 'employee' as any, entity: 'employee', permission: 'payroll.manage', schema: employeeSchema, searchFields: ['fullName','idNumber'] }));
router.use('/tax-periods', createCrudRouter({ model: 'taxPeriod' as any, entity: 'taxPeriod', permission: 'taxes.export', schema: taxPeriodSchema, searchFields: ['period'] }));
router.use('/sales', salesRoutes);
router.use('/purchases', purchasesRoutes);
router.use('/accounting', accountingRoutes);
router.use('/reports', reportsRoutes);
router.use('/modules', moduleRoutes);
router.use('/currency', currencyRoutes);
router.use('/exports', exportRoutes);
router.use('/chart-accounts', chartAccountRoutes);
router.use('/hr', hrRoutes);
router.use('/fiscal', fiscalRoutes);
router.use('/analytics', analyticsRoutes);
router.use('/qr', qrRoutes);
router.use('/food', foodRoutes);
router.use('/notifications', notificationRoutes);
router.use('/maps', mapsRoutes);
router.use('/ai', aiRoutes);
router.use('/demos', demosRoutes);
router.use('/pretesting', pretestingRoutes);
router.use('/licenses', licenseRoutes);
router.use('/imports', importRoutes);
router.use('/regulatory', regulatoryRoutes);
router.use('/rules', rulesRoutes);
router.use('/rbac', rbacRoutes);
router.get('/health/db', requireTenant, async (_req, res, next) => {
  try {
    const result = await prisma.$queryRawUnsafe('select now() as now, current_database() as db, current_schema() as schema');
    res.json({ ok: true, data: { database: result } });
  } catch (error) {
    next(error);
  }
});
export default router;
