import { Router } from 'express';
import { prisma } from '../database/prisma.js';
import { requireTenant } from '../shared/middleware/context.js';
import { enforceCommercialSubscription } from '../shared/commercial/subscriptionMiddleware.js';
import { requireCurrentLegalAcceptance } from '../shared/legal/legalAcceptanceMiddleware.js';
import { createCrudRouter } from './crud.factory.js';
import { clientSchema, supplierSchema, productSchema, bankAccountSchema, taxPeriodSchema } from './schemas.js';
import tenantRoutes from './tenants/tenants.routes.js';
import legalRoutes from './legal/legal.routes.js';
import licenseDeviceRoutes from './license-devices/license-devices.routes.js';
import commercialAccessRoutes from './commercial-access/commercial-access.routes.js';
import salesRoutes from './sales/sales.routes.js';
import purchasesRoutes from './purchases/purchases.routes.js';
import payablesRoutes from './payables/payables.routes.js';
import approvalsRoutes from './approvals/approvals.routes.js';
import accountingRoutes from './accounting/accounting.routes.js';
import reportsRoutes from './reports/reports.routes.js';
import moduleRoutes from './modules/modules.routes.js';
import currencyRoutes from './currency/currency.routes.js';
import exportRoutes from './exports/exports.routes.js';
import chartAccountRoutes from './chart-accounts/chart-accounts.routes.js';
import hrRoutes from './hr/hr.routes.js';
import bankingRoutes from './banking/banking.routes.js';
import inventoryRoutes from './inventory/inventory.routes.js';
import payrollRoutes from './payroll/payroll.routes.js';
import tasksRoutes from './tasks/tasks.routes.js';
import employeesRoutes from './employees/employees.routes.js';
import fiscalRoutes from './fiscal/fiscal.routes.js';
import analyticsRoutes from './analytics/analytics.routes.js';
import qrRoutes from './qr/qr.routes.js';
import foodRoutes from './food/food.routes.js';
import notificationRoutes from './notifications/notifications.routes.js';
import mapsRoutes from './maps/maps.routes.js';
import aiRoutes from './ai/ai.routes.js';
import demosRoutes from './demos/demos.routes.js';
import pretestingRoutes from './pretesting/pretesting.routes.js';
import licenseRoutes from './licenses/licenses.routes.js';
import serviceRestrictionRoutes from './commercial/service-restrictions.routes.js';
import commercialRoutes from './commercial/commercial.routes.js';
import importRoutes from './imports/imports.routes.js';
import regulatoryRoutes from './regulatory/regulatory.routes.js';
import rulesRoutes from './rules/rules.routes.js';
import rbacRoutes from './rbac/rbac.routes.js';
import userSecurityRoutes from './user-security/user-security.routes.js';
import verticalRoutes from './verticals/verticals.routes.js';
import verticalExtendedRoutes from './verticals/verticals-extended.routes.js';
import veterinaryRoutes from './verticals/veterinary.routes.js';
import veterinaryCrudRoutes from './verticals/veterinary-crud.routes.js';
import mediaRoutes from './media/media.routes.js';

const router = Router();
router.use('/legal', legalRoutes);
router.use(requireCurrentLegalAcceptance);
router.use(enforceCommercialSubscription);
router.use('/tenants', tenantRoutes);
router.use('/clients', createCrudRouter({ model:'client' as any, entity:'client', permission:'clients.manage', schema:clientSchema, searchFields:['name','rif'] }));
router.use('/suppliers', createCrudRouter({ model:'supplier' as any, entity:'supplier', permission:'purchases.manage', schema:supplierSchema, searchFields:['name','rif'] }));
router.use('/products', createCrudRouter({ model:'product' as any, entity:'product', permission:'inventory.manage', schema:productSchema, searchFields:['name','sku'] }));
router.use('/bank-accounts', createCrudRouter({ model:'bankAccount' as any, entity:'bankAccount', permission:'banking.manage', schema:bankAccountSchema, searchFields:['bankName','accountNo'] }));
router.use('/employees', employeesRoutes);
router.use('/tax-periods', createCrudRouter({ model:'taxPeriod' as any, entity:'taxPeriod', permission:'taxes.export', schema:taxPeriodSchema, searchFields:['period'] }));
router.use('/sales', salesRoutes);
router.use('/purchases', purchasesRoutes);
router.use('/payables', payablesRoutes);
router.use('/approvals', approvalsRoutes);
router.use('/accounting', accountingRoutes);
router.use('/reports', reportsRoutes);
router.use('/modules', moduleRoutes);
router.use('/currency', currencyRoutes);
router.use('/exports', exportRoutes);
router.use('/chart-accounts', chartAccountRoutes);
router.use('/hr', hrRoutes);
router.use('/banking', bankingRoutes);
router.use('/inventory', inventoryRoutes);
router.use('/payroll', payrollRoutes);
router.use('/tasks', tasksRoutes);
router.use('/fiscal', fiscalRoutes);
router.use('/analytics', analyticsRoutes);
router.use('/qr', qrRoutes);
router.use('/food', foodRoutes);
router.use('/notifications', notificationRoutes);
router.use('/maps', mapsRoutes);
router.use('/ai', aiRoutes);
router.use('/demos', demosRoutes);
router.use('/pretesting', pretestingRoutes);
router.use('/licenses', licenseRoutes);
router.use('/license-devices', licenseDeviceRoutes);
router.use('/commercial', serviceRestrictionRoutes);
router.use('/commercial', commercialRoutes);
router.use('/commercial-access', commercialAccessRoutes);
router.use('/imports', importRoutes);
router.use('/regulatory', regulatoryRoutes);
router.use('/rules', rulesRoutes);
router.use('/rbac', rbacRoutes);
router.use('/user-security', userSecurityRoutes);
router.use('/verticals', verticalRoutes);
router.use('/verticals', veterinaryCrudRoutes);
router.use('/verticals', verticalExtendedRoutes);
router.use('/verticals/veterinary', veterinaryRoutes);
router.use('/media', mediaRoutes);
router.get('/health/db', requireTenant, async (_req,res,next)=>{
  try {
    const result=await prisma.$queryRaw<Array<{now:Date;db:string;schema:string}>>`select now() as now, current_database() as db, current_schema() as schema`;
    res.json({ok:true,data:{database:result}});
  } catch(error) { next(error); }
});
export default router;
