#!/usr/bin/env bash
set -euo pipefail
: "${POSTGRES_DB:?}"
: "${POSTGRES_USER:?}"
: "${CONTAGEST_APP_PASSWORD:?}"
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" --set=db_name="$POSTGRES_DB" --set=owner_role="$POSTGRES_USER" --set=app_password="$CONTAGEST_APP_PASSWORD" <<'SQL'
SELECT 'CREATE ROLE anon NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS' WHERE NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='anon')\gexec
SELECT 'CREATE ROLE authenticated NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS' WHERE NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='authenticated')\gexec
SELECT 'CREATE ROLE service_role NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS' WHERE NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='service_role')\gexec
SELECT format('CREATE ROLE contagest_app LOGIN PASSWORD %L NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS INHERIT', :'app_password') WHERE NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='contagest_app')\gexec
ALTER ROLE contagest_app PASSWORD :'app_password';
GRANT service_role TO contagest_app;
GRANT CONNECT ON DATABASE :"db_name" TO contagest_app;
GRANT USAGE ON SCHEMA public TO service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE :"owner_role" IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE :"owner_role" IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE :"owner_role" IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO service_role;
SQL
