import express, { Router, type Request, type Response } from 'express';
import { z } from 'zod';
import { hipicoError } from './hipico-domain.js';
import { DOCUMENT_CLASSIFICATIONS, DocumentIngestionService, type DocumentAuthority } from './document-engine.js';
import { createPdfJsDocumentExtractor, documentExtractorCapability } from './document-extractor.js';
import { PostgresDocumentStore } from './document.store.js';
import { operatorTokenValid } from '../hipico-bot/hipico-operator-security.js';

const router=Router();const store=new PostgresDocumentStore();const service=new DocumentIngestionService(store,createPdfJsDocumentExtractor());
const groupSchema=z.string().trim().min(3).max(120).regex(/^[A-Za-z0-9._:-]+$/);const uuidSchema=z.string().uuid();const classificationSchema=z.enum(DOCUMENT_CLASSIFICATIONS);const authoritySchema=z.enum(['official','trusted','operator','group_evidence','unknown']);
function requestId(req:Request){return String((req as any).requestId||'').trim()||null;}
function ownerId(){const value=String(process.env.HIPICO_OWNER_ID||'').trim();if(!uuidSchema.safeParse(value).success)throw Object.assign(new Error('HIPICO_OWNER_NOT_CONFIGURED'),{code:'HIPICO_OWNER_NOT_CONFIGURED'});return value;}
function groupKey(req:Request){const parsed=groupSchema.safeParse(req.header('x-hipico-group-key')||req.query.groupKey);if(!parsed.success)throw Object.assign(new Error('HIPICO_DOCUMENT_GROUP_INVALID'),{code:'HIPICO_DOCUMENT_GROUP_INVALID'});return parsed.data;}
function header(req:Request,name:string,max=320){const value=String(req.header(name)||'').trim();return value?value.slice(0,max):null;}
function officialChannels(){return new Set(String(process.env.HIPICO_OFFICIAL_DOCUMENT_CHANNELS||'').split(',').map((item)=>item.trim()).filter(Boolean));}
function requestedAuthority(req:Request,sourceChannel:string):DocumentAuthority{const raw=String(req.header('x-hipico-document-authority')||'operator').trim();const parsed=authoritySchema.safeParse(raw);if(!parsed.success)throw Object.assign(new Error('HIPICO_DOCUMENT_AUTHORITY_INVALID'),{code:'HIPICO_DOCUMENT_AUTHORITY_INVALID'});if(parsed.data==='official'&&!officialChannels().has(sourceChannel))throw Object.assign(new Error('HIPICO_DOCUMENT_OFFICIAL_SOURCE_NOT_ALLOWLISTED'),{code:'HIPICO_DOCUMENT_OFFICIAL_SOURCE_NOT_ALLOWLISTED'});return parsed.data;}
function statusFor(code:string){if(code==='HIPICO_DOCUMENT_NOT_FOUND'||code==='HIPICO_DOCUMENT_SUPERSEDES_NOT_FOUND')return 404;if(code==='PDF_TOO_LARGE'||code==='PDF_PAGE_LIMIT_EXCEEDED'||code==='entity.too.large')return 413;if(code.includes('REPLAY_MISMATCH'))return 409;if(code==='HIPICO_DOCUMENT_EXTRACTOR_NOT_CONFIGURED'||code==='HIPICO_DOCUMENT_OCR_NOT_CONFIGURED')return 503;if(code==='HIPICO_OWNER_NOT_CONFIGURED')return 503;if(code==='HIPICO_DOCUMENT_OFFICIAL_SOURCE_NOT_ALLOWLISTED'||code==='HIPICO_DOCUMENT_OFFICIAL_AUTHORITY_REQUIRED')return 403;return 400;}
function sendError(req:Request,res:Response,error:any){const code=String(error?.code||error?.type||error?.message||'HIPICO_DOCUMENT_ERROR').slice(0,120);return res.status(statusFor(code)).json(hipicoError({code,message:code.startsWith('PDF_')?'Documento PDF rechazado por la política de seguridad.':'No se pudo procesar el documento hípico.',requestId:requestId(req),retryable:code==='HIPICO_DOCUMENT_EXTRACTOR_NOT_CONFIGURED'||code==='HIPICO_DOCUMENT_OCR_NOT_CONFIGURED'}));}
router.use((req,res,next)=>{res.setHeader('Cache-Control','no-store, max-age=0');if(!operatorTokenValid(req.header('x-hipico-operator-token')||undefined))return res.status(401).json(hipicoError({code:'HIPICO_OPERATOR_UNAUTHORIZED',message:'Operador no autenticado.',requestId:requestId(req)}));next();});
router.get('/capabilities',(_req,res)=>res.json({ok:true,data:documentExtractorCapability()}));
router.post('/',(req,res,next)=>{const mime=String(req.header('content-type')||'').split(';',1)[0].trim().toLowerCase();if(mime!=='application/pdf')return sendError(req,res,Object.assign(new Error('PDF_MIME_INVALID'),{code:'PDF_MIME_INVALID'}));next();},express.raw({type:'application/pdf',limit:'10mb'}),async(req,res)=>{
  try{const pdf=Buffer.isBuffer(req.body)?req.body:Buffer.alloc(0);const sourceChannel=header(req,'x-hipico-source-channel',120)||'operator-upload';const authority=requestedAuthority(req,sourceChannel);const receivedAt=header(req,'x-hipico-received-at',80)||new Date().toISOString();const supersedes=header(req,'x-hipico-supersedes-id',80);if(supersedes&&!uuidSchema.safeParse(supersedes).success)throw Object.assign(new Error('HIPICO_DOCUMENT_SUPERSEDES_INVALID'),{code:'HIPICO_DOCUMENT_SUPERSEDES_INVALID'});
    const result=await service.ingest({ownerId:ownerId(),groupKey:groupKey(req),pdf,filename:header(req,'x-hipico-filename',180)||'document.pdf',mimeType:req.header('content-type')||'',provenance:{sourceChannel,sourceMessageId:header(req,'x-hipico-source-message-id'),sender:header(req,'x-hipico-sender',220),receivedAt,authority},supersedesId:supersedes});return res.status(result.duplicate?200:201).json({ok:true,data:result});
  }catch(error){return sendError(req,res,error);}
});
router.get('/',async(req,res)=>{try{return res.json({ok:true,data:await store.list(ownerId(),groupKey(req),Number(req.query.limit)||50)});}catch(error){return sendError(req,res,error);}});
router.get('/:id',async(req,res)=>{try{const id=uuidSchema.parse(req.params.id),group=groupKey(req),owner=ownerId();const document=await store.get(owner,group,id);if(!document)throw Object.assign(new Error('HIPICO_DOCUMENT_NOT_FOUND'),{code:'HIPICO_DOCUMENT_NOT_FOUND'});const [sources,events]=await Promise.all([store.sources(owner,group,id),store.events(owner,group,id)]);return res.json({ok:true,data:{...document,sources,events}});}catch(error){return sendError(req,res,error);}});
router.get('/:id/extraction',async(req,res)=>{try{const id=uuidSchema.parse(req.params.id);const document=await store.get(ownerId(),groupKey(req),id);if(!document)throw Object.assign(new Error('HIPICO_DOCUMENT_NOT_FOUND'),{code:'HIPICO_DOCUMENT_NOT_FOUND'});return res.json({ok:true,data:{id:document.id,status:document.status,classification:document.classification,confidence:document.confidence,parserVersion:document.parserVersion,extraction:document.extraction}});}catch(error){return sendError(req,res,error);}});
router.post('/:id/reprocess',async(req,res)=>{try{return res.json({ok:true,data:await service.reprocessExisting({id:uuidSchema.parse(req.params.id),ownerId:ownerId(),groupKey:groupKey(req)})});}catch(error){return sendError(req,res,error);}});
router.post('/:id/approve',async(req,res)=>{try{const parsed=z.object({classification:classificationSchema,operatorId:z.string().trim().min(1).max(220)}).parse(req.body||{});await store.approve(ownerId(),groupKey(req),uuidSchema.parse(req.params.id),parsed.classification,parsed.operatorId);return res.json({ok:true,data:{id:req.params.id,classification:parsed.classification,status:'approved',financialAuthority:false,settlementApplied:false}});}catch(error){return sendError(req,res,error);}});
router.use((error:any,req:Request,res:Response,_next:any)=>sendError(req,res,error));
export default router;
