import { PageHeader, Field, Select, Button, Badge, MetricGrid, EmptyState, ErpButton, ErpCard, ErpDataTable, ErpGrid, ErpRow, ErpSection } from '../components/ui/index.js';
import { bs, usd, shortDate } from '../core/formatters.js';
import { escapeHtml, mountSubmit, qsa, today } from '../utils/dom.js';
import { BankingService } from '../services/enterpriseOperationsService.js';
import { BankReconciliationService } from '../services/bankReconciliationService.js';
import { t } from '../i18n/useTranslate.js';

let reconciliationKeyboardController=null;
let reconciliationSelectionRequest=0;
const safe=(value)=>escapeHtml(String(value??''));
const money=(currency,value)=>currency==='USD'?usd(value):bs(value);
const reconTone=(status)=>status==='reconciled'?'success':status==='conflict'?'danger':status==='suggested'?'brand':status==='partial'?'warning':'neutral';
const scrollBehavior=()=>globalThis.matchMedia?.('(prefers-reduced-motion: reduce)').matches?'auto':'smooth';
const moneyCents=(value)=>{const raw=String(value??'').trim();if(!/^\d+(?:\.\d{1,2})?$/.test(raw))return null;const [whole,fraction='']=raw.split('.');return BigInt(whole)*100n+BigInt(fraction.padEnd(2,'0'));};
const centsMoney=(value)=>`${value/100n}.${(value%100n).toString().padStart(2,'0')}`;
const minExactMoney=(left,right)=>{const a=moneyCents(left),b=moneyCents(right);if(a===null||b===null)return null;return centsMoney(a<b?a:b);};
const csvCell=(value)=>{let text=String(value??'');if(/^[=+\-@\t\r]/.test(text))text=`'${text}`;return `"${text.replace(/"/g,'""')}"`;};

export const BankingPage = {
  render(state,{query={}}={}) {
    const lang=state.settings?.lang||'es';
    const banking=state.banking||{accounts:[],movements:[]};
    const accounts=banking.accounts||[];
    const movements=banking.movements||[];
    const reconciliation=state.bankReconciliation||{lines:[],imports:[],models:[],selectedLineId:null,candidates:[],modelSuggestions:[],history:[],closing:null};
    const reconStatus=query.reconStatus||'unmatched';
    const selectedAccountId=query.reconAccount||accounts[0]?.id||'';
    const search=String(query.search||'').toLowerCase();
    const status=query.status||'all';
    const filtered=movements.filter((movement)=>{const account=accounts.find((item)=>item.id===movement.accountId)||{};const matches=!search||[movement.description,movement.reference,account.bank,account.account].some((value)=>String(value||'').toLowerCase().includes(search));return matches&&(status==='all'||(status==='reconciled'?movement.reconciled:!movement.reconciled));});
    const totalBs=accounts.filter((account)=>account.currency==='VES').reduce((sum,account)=>sum+Number(account.balance||0),0);
    const totalUsd=accounts.filter((account)=>account.currency==='USD').reduce((sum,account)=>sum+Number(account.balance||0),0);
    const pending=movements.filter((movement)=>!movement.reconciled).length;
    const reconciledPct=movements.length?Math.round(((movements.length-pending)/movements.length)*100):100;
    const accountOptions=accounts.map((account)=>({value:account.id,label:`${account.bank} · ${account.account} · ${account.currency}`}));
    const correctionOptions=movements.filter((movement)=>movement.lifecycle!=='reversal'&&!movement.reversedById).map((movement)=>({value:movement.id,label:`${shortDate(movement.date)} · ${movement.description} · ${money(movement.currency,movement.amount)}`}));

    const accountCards=accounts.map((account)=>{const integrity=account.integrity==='mismatch'?Badge('Revisar integridad','danger'):account.integrity==='legacy-baseline-required'?Badge('Baseline legacy','warning'):Badge('Conciliable','success');return ErpCard(`<div class="cg-ui-row"><span class="cgx-metric-icon"><i class="fa-solid fa-building-columns"></i></span><div class="cg-u-min-0"><p class="cg-ui-muted">${safe(account.bank)}</p><strong class="cg-ui-card-title cg-u-text-mono">${safe(money(account.currency,account.balance))}</strong><small>${safe(account.account)} · ${safe(account.type||'Cuenta bancaria')}</small><div class="cg-u-mt-xs">${integrity}</div></div></div>`,{tag:'article'});}).join('');
    const table=ErpDataTable({caption:'Movimientos bancarios',columns:[
      {key:'date',label:t('date',lang),render:(movement)=>safe(shortDate(movement.date))},
      {key:'account',label:t('account',lang),render:(movement)=>{const account=accounts.find((item)=>item.id===movement.accountId)||{};return `<strong>${safe(account.bank||'-')}</strong><br><small>${safe(account.account||'')}</small>`;}},
      {key:'description',label:t('description',lang),render:(movement)=>safe(movement.description)},
      {key:'reference',label:t('reference',lang),render:(movement)=>safe(movement.reference||'—')},
      {key:'type',label:t('type',lang),render:(movement)=>Badge(movement.type==='income'?'Ingreso':'Egreso',movement.type==='income'?'success':'warning')},
      {key:'amount',label:t('amount',lang),numeric:true,render:(movement)=>safe(money(movement.currency,movement.amount))},
      {key:'status',label:t('status',lang),render:(movement)=>movement.lifecycle==='reversal'?Badge('Reverso','info'):movement.lifecycle==='correction'?Badge('Corrección','brand'):movement.reversedById?Badge('Reversado','neutral'):Badge(movement.reconciled?'Conciliado':'Pendiente',movement.reconciled?'success':'warning')},
      {key:'actions',label:t('actions',lang),render:(movement)=>ErpRow(`${ErpButton('Cambiar conciliación',{variant:'secondary',icon:'fa-solid fa-check-double',iconOnly:true,data:{'toggle-reconcile':movement.id}})}${movement.lifecycle==='normal'&&!movement.reversedById?ErpButton('Reversar o corregir',{variant:'secondary',icon:'fa-solid fa-rotate-left',iconOnly:true,data:{'prepare-correction':movement.id}}):''}`,{wrap:true})}
    ],rows:filtered});

    const accountForm=`<form id="bankAccountForm" class="cg-ui-stack cg-ui-gap-sm">${Field({labelKey:'Banco',name:'bank',required:true})}${Field({labelKey:'Número de cuenta',name:'account',required:true})}${Select({labelKey:'Tipo',name:'accountType',options:['Corriente','Ahorro','Caja','Pasarela'].map((value)=>({value,label:value}))})}${Select({labelKey:'Moneda',name:'accountCurrency',options:[{value:'VES',label:'Bolívares'},{value:'USD',label:'Dólares'}]})}${Field({labelKey:'Saldo inicial controlado',name:'openingBalance',type:'number',attrs:'step="0.01"',value:'0'})}<small class="cg-ui-muted">Después de crear la cuenta el saldo queda de solo lectura y sólo cambia mediante movimientos, reversos o correcciones.</small>${Button({text:'Crear cuenta',icon:'fa-plus',type:'submit'})}</form>`;
    const movementForm=`<form id="bankForm" class="cg-ui-stack cg-ui-gap-sm">${Field({labelKey:'Fecha',name:'date',type:'date',value:today()})}${Select({labelKey:'Cuenta',name:'accountId',options:accountOptions})}${Field({labelKey:'Descripción',name:'description',required:true})}${Field({labelKey:'Referencia',name:'reference'})}<div class="cg-ui-grid cg-ui-grid-two">${Select({labelKey:'Tipo',name:'type',options:[{value:'income',label:'Ingreso'},{value:'expense',label:'Egreso'}]})}${Select({labelKey:'Moneda',name:'currency',options:[{value:'VES',label:'VES'},{value:'USD',label:'USD'}]})}</div>${Field({labelKey:'Monto',name:'amount',type:'number',attrs:'step="0.01" min="0.01"',value:'0'})}${Button({text:'Registrar movimiento',icon:'fa-building-columns',type:'submit'})}</form>`;
    const correctionForm=`<form id="bankCorrectionForm" class="cg-ui-stack cg-ui-gap-sm">${Select({labelKey:'Movimiento original',name:'movementId',options:correctionOptions})}${Select({labelKey:'Acción',name:'correctionAction',options:[{value:'reverse',label:'Reversar'},{value:'correct',label:'Corregir con movimiento sustituto'}]})}${Field({labelKey:'Motivo',name:'reason',required:true})}<div class="cg-ui-grid cg-ui-grid-two">${Select({labelKey:'Tipo corregido',name:'type',options:[{value:'income',label:'Ingreso'},{value:'expense',label:'Egreso'}]})}${Field({labelKey:'Monto corregido',name:'amount',type:'number',attrs:'step="0.01" min="0.01"',value:'0'})}</div>${Field({labelKey:'Descripción corregida',name:'description'})}${Field({labelKey:'Referencia corregida',name:'reference'})}<small class="cg-ui-muted">Un movimiento conciliado debe desconciliarse antes. El original nunca se elimina.</small>${Button({text:'Aplicar reverso/corrección',icon:'fa-rotate-left',type:'submit',variant:'secondary'})}</form>`;
    const toolbar=`<div class="cgx-toolbar"><strong>${filtered.length} movimientos</strong><label><i class="fa-solid fa-magnifying-glass"></i><input type="search" data-query-param="search" value="${safe(query.search||'')}" placeholder="Buscar banco, referencia o descripción"></label><select class="select" data-query-param="status"><option value="all">Todos</option><option value="pending" ${status==='pending'?'selected':''}>Pendientes</option><option value="reconciled" ${status==='reconciled'?'selected':''}>Conciliados</option></select><button type="button" class="btn btn-secondary" data-query-clear="search,status">Limpiar</button></div>`;

    const reconLines=(reconciliation.lines||[]).filter((line)=>!selectedAccountId||line.accountId===selectedAccountId);
    const selectedLine=reconLines.find((line)=>line.id===reconciliation.selectedLineId)||reconLines[0]||null;
    const reconTable=ErpDataTable({caption:'Líneas de extracto para conciliación',columns:[
      {key:'bookedAt',label:'Fecha',render:(line)=>safe(shortDate(line.bookedAt))},
      {key:'reference',label:'Referencia',render:(line)=>`<strong>${safe(line.reference||'—')}</strong><br><small>${safe(line.counterparty||line.memo||'Sin contraparte')}</small>`},
      {key:'amount',label:'Monto',numeric:true,render:(line)=>safe(money(line.currency,line.amount))},
      {key:'remaining',label:'Pendiente',numeric:true,render:(line)=>safe(money(line.currency,line.remaining))},
      {key:'status',label:'Estado',render:(line)=>Badge(line.status,reconTone(line.status))},
      {key:'action',label:'',render:(line)=>ErpButton('Revisar candidatos',{variant:line.id===selectedLine?.id?'primary':'secondary',icon:'fa-solid fa-link',data:{'select-recon-line':line.id}})}
    ],rows:reconLines});
    const candidateRows=(reconciliation.candidates||[]).map((candidate)=>`<article class="cg-ui-card cg-ui-stack cg-ui-gap-xs"><div class="cg-ui-row cg-ui-row-between"><strong>${safe(candidate.label)}</strong>${Badge(`${Math.round(Number(candidate.confidence||0)*100)}%`,candidate.blockedReason?'danger':Number(candidate.confidence)>=0.95?'success':Number(candidate.confidence)>=0.7?'warning':'neutral')}</div><small>${safe((candidate.reasons||[]).join(' · ')||'Sin coincidencias fuertes')}</small><small>${safe(candidate.currency)} · pendiente ${safe(candidate.remaining)}${candidate.blockedReason?` · ${safe(candidate.blockedReason)}`:''}</small>${candidate.blockedReason?'':`<button type="button" class="btn btn-secondary" data-reconcile-candidate="${safe(candidate.targetId)}" data-target-type="${safe(candidate.targetType)}" data-target-remaining="${safe(candidate.remaining)}">Conciliar con este candidato</button>`}</article>`).join('');
    const modelSuggestionRows=(reconciliation.modelSuggestions||[]).map((model)=>`<article class="cg-ui-card cg-ui-stack cg-ui-gap-xs"><div class="cg-ui-row cg-ui-row-between"><strong>${safe(model.name)} · v${safe(model.version)}</strong>${Badge(`${Math.round(Number(model.confidence||0)*100)}%`,'success')}</div><small>${safe(model.accountCode)} · ${safe(model.accountName)}</small><small>${safe((model.reasons||[]).join(' · '))}${model.autoApplyEligible?' · elegible por regla':''} · siempre requiere confirmación</small><button type="button" class="btn btn-secondary" data-apply-recon-model="${safe(model.modelId)}" data-model-account="${safe(model.accountCode)}" data-model-reason="${safe(model.reasonCode)}" data-model-name="${safe(model.name)}">Usar modelo en write-off</button></article>`).join('');
    const history=reconciliation.history||[];
    const activeReconciliations=[...new Map(history.filter((event)=>event.reconciliationId&&event.reconciliationStatus==='confirmed').map((event)=>[event.reconciliationId,event])).values()];
    const historyTable=history.length?ErpDataTable({caption:'Historial inmutable de conciliación',columns:[
      {key:'createdAt',label:'Fecha',render:(event)=>safe(shortDate(event.createdAt))},
      {key:'type',label:'Evento',render:(event)=>safe(event.type)},
      {key:'kind',label:'Tipo',render:(event)=>safe(event.kind||'—')},
      {key:'matchedAmount',label:'Monto',numeric:true,render:(event)=>safe(event.matchedAmount??'—')},
      {key:'reconciliationStatus',label:'Estado',render:(event)=>event.reconciliationStatus?Badge(event.reconciliationStatus,event.reconciliationStatus==='reversed'?'neutral':'success'):'—'}
    ],rows:history}):'';
    const reversalForm=activeReconciliations.length?`<form id="bankReconciliationReverseForm" class="cg-ui-stack cg-ui-gap-xs"><strong>Deshacer conciliación</strong><small class="cg-ui-muted">Conserva el evento original. Si existe write-off, genera el reverso contable enlazado.</small>${Select({labelKey:'Conciliación',name:'reconciliationId',options:activeReconciliations.map((event)=>({value:event.reconciliationId,label:`${event.kind||'match'} · ${event.matchedAmount||''} · ${String(event.reconciliationId).slice(0,8)}`}))})}<div class="cg-ui-grid cg-ui-grid-two">${Field({labelKey:'Motivo',name:'reason',required:true})}${Field({labelKey:'Período fiscal',name:'fiscalPeriod',value:String(selectedLine?.bookedAt||'').slice(0,7)})}</div>${Button({text:'Reversar conciliación',icon:'fa-rotate-left',type:'submit',variant:'secondary'})}</form>`:'';
    const candidatePanel=selectedLine?`<div class="cg-ui-stack cg-ui-gap-sm"><div><strong>${safe(selectedLine.reference||selectedLine.memo||'Línea sin referencia')}</strong><br><small>Monto ${safe(selectedLine.amount)} ${safe(selectedLine.currency)} · pendiente ${safe(selectedLine.remaining)}</small></div>${reconciliation.candidatesLoading?'<p class="cg-ui-muted">Buscando candidatos…</p>':`${candidateRows||'<p class="cg-ui-muted">No hay candidatos financieros directos.</p>'}${modelSuggestionRows?`<div class="cg-ui-stack cg-ui-gap-xs"><strong>Modelos recurrentes sugeridos</strong>${modelSuggestionRows}</div>`:''}`}<form id="bankWriteoffForm" class="cg-ui-stack cg-ui-gap-xs"><strong>Write-off auditable</strong><small class="cg-ui-muted">No altera el saldo directamente: genera asiento contable. Si la política maker-checker aplica, requiere aprobación.</small><div class="cg-ui-grid cg-ui-grid-two">${Field({labelKey:'Monto',name:'amount',type:'number',attrs:'step="0.01" min="0.01"',value:selectedLine.remaining})}${Field({labelKey:'Período fiscal',name:'fiscalPeriod',value:String(selectedLine.bookedAt||'').slice(0,7)})}${Field({labelKey:'Cuenta write-off',name:'writeoffAccountCode',required:true})}${Field({labelKey:'Cuenta contable banco',name:'bankLedgerAccountCode',required:true})}</div>${Field({labelKey:'Motivo',name:'reason',required:true})}${Field({labelKey:'ID aprobación (si aplica)',name:'approvalRequestId'})}${Button({text:'Registrar write-off',icon:'fa-scale-balanced',type:'submit',variant:'secondary'})}</form>${reversalForm}${historyTable}</div>`:EmptyState({title:'Selecciona una línea',description:'Usa teclado o botón Revisar candidatos.',iconName:'fa-link'});
    const coverage=reconciliation.closing?.coverage;
    const closing=reconciliation.closing?`<div class="cg-ui-stack cg-ui-gap-xs"><div class="cg-ui-row cg-ui-row-wrap"><strong>Cierre ${safe(reconciliation.closing.closingBalance??'N/D')} ${safe(reconciliation.closing.currency||'')}</strong><span>Saldo ContaGest ${safe(reconciliation.closing.ledgerBalance??'N/D')}</span>${reconciliation.closing.difference!==null?Badge(`Diferencia ${safe(reconciliation.closing.difference)}`,reconciliation.closing.exact?'success':'warning'):Badge('Cierre no informado','neutral')}</div>${coverage?`<small class="cg-ui-muted">Cobertura: ${safe(coverage.lines)} líneas · ${safe(coverage.unmatched)} pendientes · ${safe(coverage.firstDate?shortDate(coverage.firstDate):'N/D')} → ${safe(coverage.lastDate?shortDate(coverage.lastDate):'N/D')}</small>`:''}</div>`:'';
    const importRows=(reconciliation.imports||[]);
    const importTable=importRows.length?ErpDataTable({caption:'Provenance de extractos',columns:[
      {key:'fileName',label:'Archivo',render:(item)=>`<strong>${safe(item.fileName)}</strong><br><small>${safe(item.format)}</small>`},
      {key:'parserVersion',label:'Parser',render:(item)=>`${safe(item.parserName)}<br><small>${safe(item.parserVersion)}</small>`},
      {key:'lineCount',label:'Líneas',numeric:true,render:(item)=>safe(item.lineCount)},
      {key:'createdAt',label:'Importado',render:(item)=>safe(shortDate(item.createdAt))},
      {key:'sourceHash',label:'SHA-256',render:(item)=>`<code title="${safe(item.sourceHash)}">${safe(String(item.sourceHash||'').slice(0,12))}…</code>`}
    ],rows:importRows}):EmptyState({title:'Sin extractos importados',description:'CSV, OFX/QFX y CAMT se conservan con parser/version/hash.',iconName:'fa-file-shield'});
    const reconciliationWorkspace=ErpSection({title:'Conciliación de extractos',description:'Raw inmutable → candidatos explicables → match/write-off → confirmado. Usa ↑/↓ o j/k para moverte y Enter para revisar.',content:`<div id="bankReconciliationWorkspace" class="cg-ui-stack cg-ui-gap-sm"><div class="cgx-toolbar"><label>Cuenta <select class="select" data-query-param="reconAccount">${accountOptions.map((item)=>`<option value="${safe(item.value)}" ${item.value===selectedAccountId?'selected':''}>${safe(item.label)}</option>`).join('')}</select></label><label>Estado <select class="select" data-query-param="reconStatus"><option value="unmatched" ${reconStatus==='unmatched'?'selected':''}>unmatched</option><option value="suggested" ${reconStatus==='suggested'?'selected':''}>suggested</option><option value="partial" ${reconStatus==='partial'?'selected':''}>partial</option><option value="reconciled" ${reconStatus==='reconciled'?'selected':''}>reconciled</option><option value="conflict" ${reconStatus==='conflict'?'selected':''}>conflict</option><option value="all" ${reconStatus==='all'?'selected':''}>todos</option></select></label><button id="btnReconRefresh" type="button" class="btn btn-secondary"><i class="fa-solid fa-rotate"></i> Actualizar</button></div>${closing}<div class="cg-ui-grid cg-ui-grid-two"><div>${reconLines.length?reconTable:EmptyState({title:'Sin líneas en este filtro',description:'Importa un extracto o cambia el estado.',iconName:'fa-file-circle-check'})}</div><div>${candidatePanel}</div></div>${importTable}</div>`});

    const models=reconciliation.models||[];
    const modelForm=`<form id="bankReconciliationModelForm" class="cg-ui-stack cg-ui-gap-sm">${Field({labelKey:'Nombre del modelo',name:'name',required:true})}${Field({labelKey:'Texto recurrente de memo/referencia',name:'memoPattern',required:true})}<div class="cg-ui-grid cg-ui-grid-two">${Field({labelKey:'Cuenta write-off',name:'accountCode',required:true})}${Field({labelKey:'Código de motivo',name:'reasonCode',required:true})}${Field({labelKey:'Confianza mínima',name:'minConfidence',type:'number',attrs:'min="0" max="1" step="0.01"',value:'0.95'})}${Select({labelKey:'Elegible por regla',name:'autoApply',options:[{value:'false',label:'No'},{value:'true',label:'Sí, pero confirmar siempre'}]})}</div><small class="cg-ui-muted">La cuenta debe existir y permitir posting. El nombre se toma del plan contable del tenant; el modelo nunca contabiliza desde una consulta.</small>${Button({text:'Crear nueva versión',icon:'fa-wand-magic-sparkles',type:'submit',variant:'secondary'})}</form>`;
    const modelList=models.length?models.map((model)=>`<article class="cg-ui-card cg-ui-stack cg-ui-gap-xs"><div class="cg-ui-row cg-ui-row-between"><strong>${safe(model.name)} · v${safe(model.version)}</strong>${Badge(model.active?'Activo':'Histórico',model.active?'success':'neutral')}</div><small>Patrón: ${safe(model.memoPattern)}</small><small>${safe(model.accountCode)} · ${safe(model.accountName)} · ${safe(model.reasonCode)}</small><small>Umbral ${safe(model.minConfidence)}${model.autoApply?' · elegible por regla':''}</small></article>`).join(''):EmptyState({title:'Sin modelos recurrentes',description:'Crea modelos para comisiones y ajustes repetitivos.',iconName:'fa-wand-magic-sparkles'});
    const modelWorkspace=ErpSection({title:'Modelos recurrentes de conciliación',description:'Versionados, explicables y auditables. Una nueva versión conserva las anteriores.',content:`<div class="cg-ui-grid cg-ui-grid-two">${modelForm}<div class="cg-ui-stack cg-ui-gap-xs">${modelList}</div></div>`});

    return `<section class="cg-page-stack">${PageHeader({eyebrowKey:'bankingEyebrow',titleKey:'bankingTitle',descKey:'bankingDesc',actions:`${Button({id:'btnBankRefresh',text:t('refresh',lang),icon:'fa-rotate',variant:'secondary'})}${Button({id:'btnBankImport',text:'Importar extracto',icon:'fa-file-import',variant:'secondary'})}${Button({id:'btnBankExport',text:t('exportCsv',lang),icon:'fa-file-csv',variant:'secondary'})}`})}<input id="bankStatementFile" type="file" accept=".csv,.ofx,.qfx,.xml,.camt,text/csv,application/xml" hidden>${MetricGrid([{label:'Saldo Bs',value:bs(totalBs),iconName:'fa-building-columns',tone:'neutral'},{label:'Saldo USD',value:usd(totalUsd),iconName:'fa-dollar-sign',tone:'brand'},{label:'Pendientes',value:String(pending),iconName:'fa-list-check',tone:pending?'warning':'success'},{label:'Conciliado',value:`${reconciledPct}%`,iconName:'fa-shield-check',tone:reconciledPct===100?'success':'brand'}])}${accounts.length?ErpGrid(accountCards,{columns:'four'}):EmptyState({title:'Sin cuentas bancarias',description:'Registra la primera cuenta.',iconName:'fa-building-columns'})}${reconciliationWorkspace}${modelWorkspace}<div class="cg-ui-grid cg-ui-grid-two">${ErpSection({title:'Nueva cuenta',description:'El saldo de apertura se registra dentro de un workflow auditable.',content:accountForm})}${ErpSection({title:'Nuevo movimiento',description:'El saldo se actualiza en una transacción auditable.',content:movementForm})}</div>${ErpSection({title:'Reversar o corregir',description:'Conserva el original y crea evidencia relacionada con motivo.',content:correctionOptions.length?correctionForm:EmptyState({title:'Sin movimientos corregibles',description:'Registra un movimiento para habilitar este flujo.',iconName:'fa-rotate-left'})})}${ErpSection({title:'Movimientos',description:'No existe borrado económico normal. Reversos y correcciones quedan relacionados con el movimiento original.',content:`${toolbar}${table}`})}</section>`;
  },
  mount(state,{Store,Toast,Loading}) {
    const load=async({silent=false}={})=>{try{if(!silent)Loading?.mount?.('Cargando bancos…');const summary=await BankingService.summary();Store.set({banking:{accounts:summary.accounts||[],movements:summary.movements||[]},bankingLoadedAt:new Date().toISOString()});}catch(error){Toast.show(`No se pudo cargar tesorería: ${error.message}`,'error');}finally{if(!silent)Loading?.unmount?.();}};
    const loadReconciliation=async({silent=false}={})=>{const current=Store.get();const accountId=current.route?.query?.reconAccount||current.banking?.accounts?.[0]?.id||'';const status=current.route?.query?.reconStatus||'unmatched';if(!accountId)return;try{if(!silent)Loading?.mount?.('Cargando conciliación…');const [lines,imports,models,closing]=await Promise.all([BankReconciliationService.lines({accountId,status,take:300}),BankReconciliationService.imports({accountId,take:30}),BankReconciliationService.models(),BankReconciliationService.closingBalance(accountId).catch(()=>null)]);Store.update((draft)=>{draft.bankReconciliation={...(draft.bankReconciliation||{}),lines,imports,models,closing,selectedLineId:(draft.bankReconciliation?.selectedLineId&&lines.some((line)=>line.id===draft.bankReconciliation.selectedLineId))?draft.bankReconciliation.selectedLineId:lines[0]?.id||null,candidates:[],modelSuggestions:[],history:[]};});}catch(error){Toast.show(`No se pudo cargar conciliación: ${error.message}`,'error');}finally{if(!silent)Loading?.unmount?.();}};
    const selectLine=async(lineId)=>{const requestId=++reconciliationSelectionRequest;Store.update((draft)=>{draft.bankReconciliation=draft.bankReconciliation||{};draft.bankReconciliation.selectedLineId=lineId;draft.bankReconciliation.candidates=[];draft.bankReconciliation.modelSuggestions=[];draft.bankReconciliation.history=[];draft.bankReconciliation.candidatesLoading=true;});try{const [result,history]=await Promise.all([BankReconciliationService.candidates(lineId),BankReconciliationService.history(lineId)]);if(requestId!==reconciliationSelectionRequest)return;Store.update((draft)=>{draft.bankReconciliation.candidates=result.candidates||[];draft.bankReconciliation.modelSuggestions=result.modelSuggestions||[];draft.bankReconciliation.history=history||[];draft.bankReconciliation.candidatesLoading=false;const line=(draft.bankReconciliation.lines||[]).find((item)=>item.id===lineId);if(line)line.status=result.status||line.status;});}catch(error){if(requestId!==reconciliationSelectionRequest)return;Store.update((draft)=>{if(draft.bankReconciliation)draft.bankReconciliation.candidatesLoading=false;});Toast.show(`No se calcularon candidatos: ${error.message}`,'error');}};
    const refreshReconciliation=async()=>{await loadReconciliation({silent:true});const selected=Store.get().bankReconciliation?.selectedLineId;if(selected)await selectLine(selected);};
    if(!state.bankingLoadedAt)load({silent:true});
    loadReconciliation({silent:true}).then(()=>{const selected=Store.get().bankReconciliation?.selectedLineId;if(selected)selectLine(selected);});
    document.getElementById('btnBankRefresh')?.addEventListener('click',async()=>{await load();await refreshReconciliation();});
    document.getElementById('btnReconRefresh')?.addEventListener('click',()=>refreshReconciliation());
    mountSubmit('#bankAccountForm',async(data,form)=>{const submit=form.querySelector('[type="submit"]');submit?.setAttribute('disabled','disabled');try{const payload={...data,type:data.accountType,currency:data.accountCurrency};delete payload.accountType;delete payload.accountCurrency;const account=await BankingService.createAccount(payload);Store.update((draft)=>{draft.banking=draft.banking||{accounts:[],movements:[]};draft.banking.accounts=[account,...(draft.banking.accounts||[]).filter((item)=>item.id!==account.id)];});form.reset();Toast.show('Cuenta y saldo de apertura registrados.','success');await load({silent:true});}catch(error){Toast.show(`No se creó la cuenta: ${error.message}`,'error');}finally{submit?.removeAttribute('disabled');}});
    mountSubmit('#bankForm',async(data,form)=>{if(!data.accountId)return Toast.show('Selecciona una cuenta.','error');const submit=form.querySelector('[type="submit"]');submit?.setAttribute('disabled','disabled');try{await BankingService.createMovement(data);form.reset();Toast.show('Movimiento registrado y saldo actualizado.','success');await load({silent:true});}catch(error){Toast.show(`No se registró el movimiento: ${error.message}`,'error');}finally{submit?.removeAttribute('disabled');}});
    mountSubmit('#bankCorrectionForm',async(data,form)=>{if(!data.movementId)return Toast.show('Selecciona el movimiento original.','error');if(String(data.reason||'').trim().length<5)return Toast.show('Indica un motivo de al menos 5 caracteres.','error');const submit=form.querySelector('[type="submit"]');submit?.setAttribute('disabled','disabled');try{if(data.correctionAction==='reverse'){await BankingService.reverse(data.movementId,data.reason);}else{if(!data.description||Number(data.amount||0)<=0)throw new Error('La corrección requiere descripción y monto mayor que cero.');await BankingService.correct(data.movementId,{reason:data.reason,type:data.type,amount:data.amount,description:data.description,reference:data.reference});}form.reset();Toast.show(data.correctionAction==='reverse'?'Movimiento reversado con trazabilidad.':'Movimiento corregido mediante reverso y sustitución.','success');await load({silent:true});}catch(error){Toast.show(`No se aplicó la corrección: ${error.message}`,'error');}finally{submit?.removeAttribute('disabled');}});
    qsa('[data-toggle-reconcile]').forEach((button)=>button.addEventListener('click',async()=>{const movement=(Store.get().banking?.movements||[]).find((item)=>item.id===button.dataset.toggleReconcile);if(!movement)return;try{const updated=await BankingService.reconcile(movement.id,!movement.reconciled);Store.update((draft)=>{draft.banking.movements=(draft.banking?.movements||[]).map((item)=>item.id===updated.id?updated:item);});Toast.show(updated.reconciled?'Movimiento conciliado.':'Conciliación revertida.','success');}catch(error){Toast.show(`No se actualizó la conciliación: ${error.message}`,'error');}}));
    qsa('[data-prepare-correction]').forEach((button)=>button.addEventListener('click',()=>{const form=document.getElementById('bankCorrectionForm');const select=form?.querySelector('[name="movementId"]');if(select){select.value=button.dataset.prepareCorrection||'';form.scrollIntoView({behavior:scrollBehavior(),block:'center'});form.querySelector('[name="reason"]')?.focus();}}));
    qsa('[data-select-recon-line]').forEach((button)=>button.addEventListener('click',()=>selectLine(button.dataset.selectReconLine)));
    qsa('[data-reconcile-candidate]').forEach((button)=>button.addEventListener('click',async()=>{const current=Store.get();const line=(current.bankReconciliation?.lines||[]).find((item)=>item.id===current.bankReconciliation?.selectedLineId);if(!line)return;const amount=minExactMoney(line.remaining,button.dataset.targetRemaining);if(!amount||moneyCents(amount)===0n)return Toast.show('No existe saldo conciliable.','error');button.setAttribute('disabled','disabled');try{await BankReconciliationService.reconcile(line.id,[{targetType:button.dataset.targetType,targetId:button.dataset.reconcileCandidate,amount}],{reasons:['human_confirmed_candidate']});Toast.show('Conciliación confirmada con trazabilidad.','success');await refreshReconciliation();}catch(error){Toast.show(`No se confirmó la conciliación: ${error.message}`,'error');}finally{button.removeAttribute('disabled');}}));
    qsa('[data-apply-recon-model]').forEach((button)=>button.addEventListener('click',()=>{const form=document.getElementById('bankWriteoffForm');if(!form)return;const account=form.querySelector('[name="writeoffAccountCode"]');const reason=form.querySelector('[name="reason"]');if(account)account.value=button.dataset.modelAccount||'';if(reason)reason.value=`Modelo ${button.dataset.modelName||'recurrente'}: ${button.dataset.modelReason||'AJUSTE'}`;form.scrollIntoView({behavior:scrollBehavior(),block:'center'});form.querySelector('[name="bankLedgerAccountCode"]')?.focus();Toast.show('Modelo aplicado al formulario; revisa cuenta banco, monto y aprobación antes de confirmar.','info');}));
    mountSubmit('#bankWriteoffForm',async(data,form)=>{const lineId=Store.get().bankReconciliation?.selectedLineId;if(!lineId)return;const submit=form.querySelector('[type="submit"]');submit?.setAttribute('disabled','disabled');try{await BankReconciliationService.writeOff(lineId,{amount:String(data.amount),writeoffAccountCode:data.writeoffAccountCode,bankLedgerAccountCode:data.bankLedgerAccountCode,reason:data.reason,fiscalPeriod:data.fiscalPeriod,approvalRequestId:data.approvalRequestId||undefined},{approvalRequestId:data.approvalRequestId||undefined});Toast.show('Write-off contabilizado y conciliado.','success');await refreshReconciliation();}catch(error){const code=error.payload?.code;Toast.show(code==='APPROVAL_REQUIRED'?'El write-off requiere aprobación maker-checker antes de ejecutarse.':`No se registró el write-off: ${error.message}`,'error');}finally{submit?.removeAttribute('disabled');}});
    mountSubmit('#bankReconciliationReverseForm',async(data,form)=>{const submit=form.querySelector('[type="submit"]');submit?.setAttribute('disabled','disabled');try{await BankReconciliationService.reverse(data.reconciliationId,{reason:data.reason,fiscalPeriod:data.fiscalPeriod||undefined});Toast.show('Conciliación reversada sin borrar el historial original.','success');await refreshReconciliation();}catch(error){Toast.show(`No se reversó la conciliación: ${error.message}`,'error');}finally{submit?.removeAttribute('disabled');}});
    mountSubmit('#bankReconciliationModelForm',async(data,form)=>{const submit=form.querySelector('[type="submit"]');submit?.setAttribute('disabled','disabled');try{await BankReconciliationService.createModel({name:data.name,memoPattern:data.memoPattern,accountCode:data.accountCode,reasonCode:data.reasonCode,minConfidence:String(data.minConfidence||'0.95'),autoApply:data.autoApply==='true'});form.reset();Toast.show('Nueva versión del modelo guardada y auditable.','success');await refreshReconciliation();}catch(error){Toast.show(`No se creó el modelo: ${error.message}`,'error');}finally{submit?.removeAttribute('disabled');}});
    const input=document.getElementById('bankStatementFile');
    document.getElementById('btnBankImport')?.addEventListener('click',()=>{if(!(Store.get().banking?.accounts||[]).length)return Toast.show('Crea una cuenta bancaria antes de importar.','warning');input?.click();});
    input?.addEventListener('change',async()=>{const file=input.files?.[0];if(!file)return;const accountId=Store.get().route?.query?.reconAccount||Store.get().banking?.accounts?.[0]?.id;if(!accountId){Toast.show('Selecciona una cuenta bancaria.','error');input.value='';return;}try{Loading?.mount?.('Validando e importando extracto…');const result=await BankReconciliationService.importStatement(accountId,file);Toast.show(result.duplicate?'El extracto ya estaba importado; no se duplicaron líneas.':`${result.inserted} líneas importadas; ${result.deduplicated} deduplicadas.`,'success');await refreshReconciliation();}catch(error){Toast.show(`No se pudo importar: ${error.message}`,'error');}finally{Loading?.unmount?.();input.value='';}});
    document.getElementById('btnBankExport')?.addEventListener('click',()=>{const rows=Store.get().banking?.movements||[];const csv=['date,accountId,description,reference,type,currency,amount,reconciled',...rows.map((row)=>[row.date,row.accountId,row.description||'',row.reference||'',row.type,row.currency,row.amount,row.reconciled].map(csvCell).join(','))].join('\n');const link=document.createElement('a');link.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));link.download='movimientos-bancarios.csv';link.click();URL.revokeObjectURL(link.href);Toast.show('Extracto exportado con celdas protegidas.','success');});
    reconciliationKeyboardController?.abort();
    reconciliationKeyboardController=new AbortController();
    document.addEventListener('keydown',(event)=>{if(!document.getElementById('bankReconciliationWorkspace')||event.defaultPrevented||['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName))return;const buttons=qsa('[data-select-recon-line]');if(!buttons.length)return;const active=document.activeElement;let index=buttons.indexOf(active);if(event.key==='ArrowDown'||event.key==='j'){event.preventDefault();index=Math.min(buttons.length-1,index<0?0:index+1);buttons[index]?.focus();}else if(event.key==='ArrowUp'||event.key==='k'){event.preventDefault();index=Math.max(0,index<0?0:index-1);buttons[index]?.focus();}else if(event.key==='Enter'&&active?.dataset?.selectReconLine){event.preventDefault();active.click();}},{signal:reconciliationKeyboardController.signal});
  }
};
