import { PageHeader, Field, Select, Button, Badge, EmptyState, ErpDataTable, ErpSection } from '../components/ui/index.js';
import { escapeHtml, mountSubmit, qsa } from '../utils/dom.js';
import { BusinessLocationsService } from '../services/businessLocationsService.js';
const safe=(value)=>escapeHtml(String(value??''));
const tone=(status)=>status==='active'?'success':status==='closed'?'danger':'warning';
const timezoneOptions=()=>{try{return Intl.supportedValuesOf('timeZone').map((value)=>({value,label:value}));}catch{return ['America/Caracas','America/New_York','UTC'].map((value)=>({value,label:value}));}};
const actions=(location)=>`<div class="cg-ui-row">${location.status==='active'?`<button type="button" class="btn btn-secondary" data-location-edit="${safe(location.id)}">Editar</button><button type="button" class="btn btn-danger" data-location-deactivate="${safe(location.id)}">Desactivar</button>`:`<button type="button" class="btn btn-secondary" data-location-reopen="${safe(location.id)}">Reabrir</button>`}</div>`;
export const BusinessLocationsPage={
  render(state,{query={}}={}){const rows=state.businessLocations||[];const selected=rows.find((item)=>item.id===query.edit)||null;const table=rows.length?ErpDataTable({caption:'Sedes operativas',columns:[{key:'code',label:'Código'},{key:'name',label:'Nombre'},{key:'timezone',label:'Zona horaria'},{key:'status',label:'Estado',render:(row)=>Badge(row.status,tone(row.status))},{key:'actions',label:'Acciones',render:actions}],rows}):EmptyState({title:'Sin sedes',description:'Crea la primera sede operativa del tenant.',iconName:'fa-location-dot'});const form=`<form id="businessLocationForm" class="cg-ui-stack cg-ui-gap-md"><input type="hidden" name="id" value="${safe(selected?.id||'')}">${Field({labelKey:'Código estable',name:'code',value:selected?.code||'',required:true,disabled:Boolean(selected)})}${Field({labelKey:'Nombre',name:'name',value:selected?.name||'',required:true})}${Select({labelKey:'Zona horaria IANA',name:'timezone',value:selected?.timezone||'America/Caracas',required:true,options:timezoneOptions()})}${Field({labelKey:'AddressGeocode ID',name:'addressGeocodeId',value:selected?.addressGeocodeId||'',placeholder:'UUID opcional de dirección geocodificada'})}${Field({labelKey:'Teléfono público',name:'phone',value:selected?.phone||''})}${Field({labelKey:'Email público',name:'email',type:'email',value:selected?.email||''})}${selected?`<label class="cg-ui-check"><input type="checkbox" name="confirmTimezoneChange" value="true"> Confirmo el cambio de zona horaria si fue modificado</label>`:''}${Button({text:selected?'Guardar cambios':'Crear sede',type:'submit',icon:selected?'fa-floppy-disk':'fa-plus'})}</form>`;return `<section class="cg-page-stack">${PageHeader({eyebrowKey:'Core',titleKey:'Sedes',descKey:'Autoridad única de sede operativa, timezone y alcance transversal.'})}<div class="cg-ui-grid cg-ui-grid-two">${ErpSection({title:selected?'Editar sede':'Nueva sede',description:'Warehouse, recursos y stock permanecen en sus bounded contexts.',content:form})}${ErpSection({title:'Sedes del tenant',description:'Desactivar conserva referencias históricas; no existe borrado duro desde esta pantalla.',content:table})}</div></section>`;},
  mount(state,{Store,Toast,UrlStateService,Loading}){const load=async()=>{try{Loading?.mount?.('Cargando sedes…');const businessLocations=await BusinessLocationsService.list();Store.set({businessLocations,businessLocationsLoadedAt:new Date().toISOString()});}catch(error){Toast.show(`No se pudieron cargar las sedes: ${error.message}`,'error');}finally{Loading?.unmount?.();}};if(!state.businessLocationsLoadedAt)load();mountSubmit('#businessLocationForm',async(data)=>{try{const id=data.id;delete data.id;if(data.confirmTimezoneChange==='true')data.confirmTimezoneChange=true;else delete data.confirmTimezoneChange;const saved=id?await BusinessLocationsService.update(id,data):await BusinessLocationsService.create(data);Store.update((draft)=>{draft.businessLocations=[saved,...(draft.businessLocations||[]).filter((item)=>item.id!==saved.id)];draft.businessLocationsLoadedAt=new Date().toISOString();});UrlStateService.setParams({edit:null});Toast.show(id?'Sede actualizada.':'Sede creada.','success');}catch(error){Toast.show(error.message,'error');}});qsa('[data-location-edit]').forEach((button)=>button.addEventListener('click',()=>UrlStateService.setParams({edit:button.dataset.locationEdit})));qsa('[data-location-deactivate]').forEach((button)=>button.addEventListener('click',async()=>{try{const saved=await BusinessLocationsService.deactivate(button.dataset.locationDeactivate);Store.update((draft)=>{draft.businessLocations=(draft.businessLocations||[]).map((item)=>item.id===saved.id?saved:item);});Toast.show('Sede desactivada sin borrar historial.','success');}catch(error){Toast.show(error.message,'error');}}));qsa('[data-location-reopen]').forEach((button)=>button.addEventListener('click',async()=>{try{const saved=await BusinessLocationsService.reopen(button.dataset.locationReopen);Store.update((draft)=>{draft.businessLocations=(draft.businessLocations||[]).map((item)=>item.id===saved.id?saved:item);});Toast.show('Sede reabierta.','success');}catch(error){Toast.show(error.message,'error');}}));}
};
