import { Store } from '../state/store.js';
import { uid } from '../utils/dom.js';
import { DS } from '../components/ui/index.js';
import { CHART_OF_ACCOUNTS, ACCOUNTING_POLICIES } from '../data/chartOfAccounts.js';
import { accountKpis, JournalTemplates } from '../core/accountingEngine.js';
import { ExportService } from '../services/exportService.js';
import { escapeHtml } from '../utils/dom.js';

export const ChartAccountsPage = {
  render(state) {
    const allAccounts = [...CHART_OF_ACCOUNTS, ...(state.customAccounts || [])];
    const k = { total: allAccounts.length, postable: allAccounts.filter(a=>a.allowPosting).length, assets: allAccounts.filter(a=>a.type==='activo').length, expenses: allAccounts.filter(a=>a.type==='gasto').length };
    const sampleSale = JournalTemplates.sale({ subtotal: 2500, iva: 400, igtf: 0, total: 2900 });
    const rows = allAccounts.slice(0, 260).map((account) => `<tr><td class="font-mono">${escapeHtml(account.code)}</td><td>${'&nbsp;'.repeat((account.level - 1) * 4)}${escapeHtml(account.name)}</td><td>${escapeHtml(account.type)}</td><td>${escapeHtml(account.nature)}</td><td>${account.allowPosting ? '<span class="pl-chip pl-chip-success">Movimiento</span>' : '<span class="pl-chip pl-chip-neutral">Grupo</span>'}</td></tr>`);
    return `<section class="pl-page">
      <div class="pl-header"><div><p class="pl-eyebrow">Contabilidad</p><h2>Plan de Cuentas VEN-NIF configurable</h2><p>${escapeHtml(ACCOUNTING_POLICIES.warning)}</p></div><div class="pl-actions"><button id="btnExportAccountsXlsx" class="pl-btn pl-btn-primary"><i class="fa-solid fa-file-excel"></i>XLSX</button><button id="btnExportAccountsTxt" class="pl-btn pl-btn-secondary"><i class="fa-solid fa-file-lines"></i>TXT</button></div></div>
      <div class="pl-grid pl-grid-4"><article class="pl-card pl-kpi"><div class="pl-kpi-top"><span>Cuentas</span><i class="fa-solid fa-sitemap"></i></div><strong>${k.total}</strong><p>Catálogo base</p></article><article class="pl-card pl-kpi"><div class="pl-kpi-top"><span>Imputables</span><i class="fa-solid fa-pen-nib"></i></div><strong>${k.postable}</strong><p>Permiten asientos</p></article><article class="pl-card pl-kpi"><div class="pl-kpi-top"><span>Activos</span><i class="fa-solid fa-building-columns"></i></div><strong>${k.assets}</strong><p>Cuentas de débito</p></article><article class="pl-card pl-kpi"><div class="pl-kpi-top"><span>Gastos</span><i class="fa-solid fa-chart-line"></i></div><strong>${k.expenses}</strong><p>Control operativo</p></article></div>
      <div class="pl-split"><article class="pl-card pl-card-pad"><h3 class="text-2xl font-black">Validación de partida doble</h3><p class="subtitle mt-2">Ejemplo de venta: débito clientes, crédito ventas e IVA. El motor rechaza diferencias, cuentas inexistentes o cuentas de agrupación.</p><div class="mt-4">${sampleSale.ok ? '<span class="pl-chip pl-chip-success">Asiento balanceado</span>' : '<span class="pl-chip pl-chip-danger">Error</span>'}</div><pre class="mt-4 overflow-auto rounded-xl bg-slate-950 p-4 text-xs text-slate-100">${escapeHtml(JSON.stringify(sampleSale.lines.map(({ account, errors, ...line }) => line), null, 2))}</pre></article><article class="pl-card pl-card-pad"><h3 class="text-2xl font-black">Política contable</h3><p class="subtitle mt-2">${escapeHtml(ACCOUNTING_POLICIES.standard)} · versión ${escapeHtml(ACCOUNTING_POLICIES.version)}</p><ul class="mt-4 grid gap-2 font-bold text-slate-600"><li>• Cierres por período para impedir edición histórica.</li><li>• Reversos en vez de eliminación.</li><li>• Plantillas por fuente: ventas, compras, nómina, bancos, impuestos.</li><li>• Personalizable por contador público.</li></ul></article></div>
      <div class="pl-table-wrap"><table id="chartAccountsTable" class="pl-table"><thead><tr><th>Código</th><th>Cuenta</th><th>Tipo</th><th>Naturaleza</th><th>Uso</th></tr></thead><tbody>${rows.join('')}</tbody></table></div>
    <form id="customAccountForm" class="pl-card pl-card-pad mt-5 grid gap-3 md:grid-cols-6"><input class="pl-input" name="code" placeholder="Código" required><input class="pl-input md:col-span-2" name="name" placeholder="Nombre de cuenta" required><select class="pl-input" name="type"><option value="activo">Activo</option><option value="pasivo">Pasivo</option><option value="patrimonio">Patrimonio</option><option value="ingreso">Ingreso</option><option value="costo">Costo</option><option value="gasto">Gasto</option></select><select class="pl-input" name="nature"><option value="debit">Débito</option><option value="credit">Crédito</option></select><button class="pl-btn pl-btn-primary"><i class="fa-solid fa-plus"></i>Agregar cuenta</button></form></section>`;
  },
  mount(_state, { Store, Toast }) {
    document.getElementById('customAccountForm')?.addEventListener('submit', (event) => { event.preventDefault(); const data = Object.fromEntries(new FormData(event.currentTarget).entries()); Store.update((draft) => { draft.customAccounts = [{ id: uid('acc'), ...data, level: String(data.code || '').split('.').length, allowPosting: true, active: true }, ...(draft.customAccounts || [])]; }); event.currentTarget.reset(); Toast.show('Cuenta contable agregada al catálogo configurable.', 'success'); });
    document.getElementById('btnExportAccountsTxt')?.addEventListener('click', () => { ExportService.downloadTxt('plan-cuentas-contagest', CHART_OF_ACCOUNTS, 'Plan de Cuentas ContaGest-VE'); Toast.show('TXT del plan de cuentas generado.', 'success'); });
    document.getElementById('btnExportAccountsXlsx')?.addEventListener('click', async () => { await ExportService.downloadXlsx('plan-cuentas-contagest', [{ name: 'Plan de Cuentas', rows: CHART_OF_ACCOUNTS }], 'Plan de Cuentas ContaGest-VE'); Toast.show('XLSX solicitado al backend. Si no está activo, se genera fallback.', 'info'); });
  }
};
