import { Badge, Button, EmptyState, Field, PageHeader, Select, StatCard, Textarea } from '../components/ui/index.js';
import { escapeHtml, mountSubmit, today } from '../utils/dom.js';
import { HealthVerticalService } from '../services/verticalService.js';

const patientName=(patient={})=>patient.displayName||patient.fullName||'Paciente';
const rows=(value)=>Array.isArray(value)?value:value?.data||[];
const statusTone=(status='')=>['completed','confirmed','checked_in'].includes(String(status).toLowerCase())?'success':['cancelled','no_show'].includes(String(status).toLowerCase())?'danger':'warning';
const statusLabel=(status='')=>({scheduled:'Programada',confirmed:'Confirmada',checked_in:'En sala',in_progress:'En atención',completed:'Completada',cancelled:'Cancelada',no_show:'No asistió'}[String(status).toLowerCase()]||status||'Programada');
const TOOTH_OPTIONS=['11','12','13','14','15','16','17','18','21','22','23','24','25','26','27','28','31','32','33','34','35','36','37','38','41','42','43','44','45','46','47','48'];
const PROCEDURES=['Evaluación','Profilaxis / limpieza','Restauración','Endodoncia','Extracción','Periodoncia','Ortodoncia','Prótesis','Implante','Radiografía / estudio','Control postoperatorio'];

function appointmentIso(date,time,duration=45){const start=new Date(`${date}T${time||'09:00'}:00`);if(Number.isNaN(start.getTime()))throw new Error('Fecha u hora inválida.');const end=new Date(start.getTime()+Math.max(15,Number(duration||45))*60000);return{startsAt:start.toISOString(),endsAt:end.toISOString()};}
function toothGrid(selected=''){return `<div class="cg-dental-tooth-grid" data-dental-teeth>${TOOTH_OPTIONS.map((tooth)=>`<button type="button" data-tooth="${tooth}" class="${selected===tooth?'is-selected':''}">${tooth}</button>`).join('')}</div>`;}
function appointmentList(items=[],patientById=new Map()){if(!items.length)return EmptyState({title:'Sin citas odontológicas',description:'Las nuevas citas aparecerán aquí.',iconName:'fa-tooth'});return `<div class="cg-dental-list">${items.slice(0,12).map((item)=>{const patient=patientById.get(item.patientId)||{};return `<article><div><strong>${escapeHtml(patientName(patient))}</strong><small>${new Date(item.startsAt).toLocaleString('es-VE',{dateStyle:'short',timeStyle:'short'})} · ${escapeHtml(item.reason||'Consulta odontológica')}</small></div>${Badge(statusLabel(item.status),statusTone(item.status))}</article>`;}).join('')}</div>`;}
function encounterList(items=[]){if(!items.length)return EmptyState({title:'Sin tratamientos registrados',description:'Selecciona un paciente y registra el primer procedimiento.',iconName:'fa-notes-medical'});return `<div class="cg-dental-list">${items.slice(0,12).map((item)=>`<article><div><strong>${escapeHtml(item.clinicalData?.procedure||item.type||'Atención odontológica')}</strong><small>${escapeHtml(item.clinicalData?.tooth?`Pieza ${item.clinicalData.tooth} · `:'')}${escapeHtml(item.assessment||item.subjective||'Sin diagnóstico resumido')}</small></div>${Badge(item.status==='signed'?'Firmado':'Borrador',item.status==='signed'?'success':'warning')}</article>`).join('')}</div>`;}

export const DentistryPracticePage={
  render(state){
    const data=state.dentistry||{};const patients=rows(data.patients);const professionals=rows(data.professionals).filter((item)=>/odont|dental/i.test(String(item.specialty||''))||!item.specialty);const appointments=rows(data.appointments).filter((item)=>String(item.type||'').toLowerCase()==='dentistry');const encounters=rows(data.encounters);const patientById=new Map(patients.map((item)=>[item.id,item]));
    const patientOptions=[{value:'',label:'Seleccionar paciente'},...patients.map((item)=>({value:item.id,label:patientName(item)}))];const professionalOptions=[{value:'',label:'Sin asignar'},...professionals.map((item)=>({value:item.id,label:item.fullName}))];
    const pending=appointments.filter((item)=>!['completed','cancelled'].includes(String(item.status||'').toLowerCase())).length;
    return `<section class="cg-page-stack cg-dentistry-workspace">
      ${PageHeader({eyebrow:'Salud · Odontología',title:'Consultorio odontológico',description:'Pacientes, agenda, odontograma operativo y registro de procedimientos en un mismo flujo.',actions:Button({id:'btnDentalRefresh',text:'Actualizar',icon:'fa-rotate',variant:'secondary'})})}
      <div class="grid gap-3 md:grid-cols-4">${StatCard({label:'Pacientes',value:String(patients.length),icon:'fa-user-group'})}${StatCard({label:'Citas activas',value:String(pending),icon:'fa-calendar-check',tone:pending?'warning':'success'})}${StatCard({label:'Profesionales',value:String(professionals.length),icon:'fa-user-doctor'})}${StatCard({label:'Tratamientos cargados',value:String(encounters.length),icon:'fa-tooth',tone:'brand'})}</div>
      <section class="cg-dental-grid">
        <form id="dentalPatientForm" class="cg-ui-card cg-ui-section"><header class="cg-ui-section-head"><div><h2 class="cg-ui-section-title">Nuevo paciente</h2><p class="cg-ui-muted">Registro rápido para agenda y ficha odontológica.</p></div></header><div class="cg-ui-section-body grid gap-3">${Field({labelKey:'Nombre completo',name:'displayName',required:true})}${Field({labelKey:'Correo',name:'email',type:'email'})}${Field({labelKey:'Teléfono',name:'phone',attrs:'inputmode="tel"'})}${Button({text:'Guardar paciente',icon:'fa-user-plus',type:'submit'})}</div></form>
        <form id="dentalProfessionalForm" class="cg-ui-card cg-ui-section"><header class="cg-ui-section-head"><div><h2 class="cg-ui-section-title">Profesional odontológico</h2><p class="cg-ui-muted">Crea el responsable que aparecerá en citas y tratamientos.</p></div></header><div class="cg-ui-section-body grid gap-3">${Field({labelKey:'Nombre completo',name:'fullName',required:true})}${Select({labelKey:'Especialidad',name:'specialty',options:[{value:'odontologia-general',label:'Odontología general'},{value:'ortodoncia',label:'Ortodoncia'},{value:'endodoncia',label:'Endodoncia'},{value:'periodoncia',label:'Periodoncia'},{value:'cirugia-bucal',label:'Cirugía bucal'},{value:'protesis',label:'Prótesis / rehabilitación'}]})}${Field({labelKey:'Matrícula / licencia',name:'licenseNumber'})}${Button({text:'Guardar profesional',icon:'fa-user-doctor',type:'submit'})}</div></form>
        <form id="dentalAppointmentForm" class="cg-ui-card cg-ui-section"><header class="cg-ui-section-head"><div><h2 class="cg-ui-section-title">Nueva cita</h2><p class="cg-ui-muted">Agenda sin salir del módulo.</p></div></header><div class="cg-ui-section-body grid gap-3">${Select({labelKey:'Paciente',name:'appointmentPatientId',options:patientOptions})}${Select({labelKey:'Profesional',name:'appointmentProfessionalId',options:professionalOptions})}<div class="cg-form-grid-2">${Field({labelKey:'Fecha',name:'date',type:'date',value:today(),required:true})}${Field({labelKey:'Hora',name:'time',type:'time',value:'09:00',required:true})}</div>${Field({labelKey:'Motivo',name:'reason',placeholder:'Evaluación, dolor, control…'})}${Button({text:'Agendar cita',icon:'fa-calendar-plus',type:'submit'})}</div></form>
      </section>
      <section class="cg-ui-card cg-ui-section"><header class="cg-ui-section-head"><div><h2 class="cg-ui-section-title">Odontograma y tratamiento rápido</h2><p class="cg-ui-muted">Selecciona la pieza y registra hallazgos/procedimiento sin escribir un formulario extenso.</p></div></header><form id="dentalEncounterForm" class="cg-ui-section-body cg-dental-treatment-form">${Select({labelKey:'Paciente',name:'patientId',options:patientOptions})}${Select({labelKey:'Profesional',name:'professionalId',options:professionalOptions})}<div><span class="cg-dental-field-label">Pieza dental</span>${toothGrid()}<input type="hidden" name="tooth" data-dental-tooth-input></div>${Select({labelKey:'Procedimiento',name:'procedure',options:PROCEDURES.map((value)=>({value,label:value}))})}<div class="cg-form-grid-2">${Field({labelKey:'Hallazgo',name:'finding',placeholder:'Caries, fractura, sensibilidad…'})}${Field({labelKey:'Diagnóstico resumido',name:'assessment'})}</div>${Textarea({labelKey:'Plan / indicaciones',name:'plan',placeholder:'Procedimiento realizado, próximos pasos y control.'})}${Button({text:'Registrar tratamiento',icon:'fa-floppy-disk',type:'submit'})}</form></section>
      <section class="cg-dental-grid"><article class="cg-ui-card cg-ui-section"><header class="cg-ui-section-head"><div><h2 class="cg-ui-section-title">Próximas citas</h2></div></header><div class="cg-ui-section-body">${appointmentList(appointments,patientById)}</div></article><article class="cg-ui-card cg-ui-section"><header class="cg-ui-section-head"><div><h2 class="cg-ui-section-title">Historia odontológica reciente</h2></div></header><div class="cg-ui-section-body">${encounterList(encounters)}</div></article></section>
    </section>`;
  },
  mount(state,{Store,Toast,Loading}){
    const load=async({silent=false}={})=>{try{if(!silent)Loading?.mount?.('Actualizando odontología…');const [patients,professionals,appointments]=await Promise.all([HealthVerticalService.patients({kind:'human'}),HealthVerticalService.professionals(),HealthVerticalService.appointments({})]);const currentPatient=rows(patients)[0];const encounters=currentPatient?await HealthVerticalService.encounters(currentPatient.id):[];Store.set({dentistry:{patients:rows(patients),professionals:rows(professionals),appointments:rows(appointments).filter((item)=>String(item.type||'').toLowerCase()==='dentistry'),encounters:rows(encounters),loadedAt:new Date().toISOString()}});}catch(error){if(!silent)Toast.show(`No se pudo actualizar odontología: ${error.message}`,'warning');}finally{if(!silent)Loading?.unmount?.();}};
    if(!state.dentistry?.loadedAt)load({silent:true});document.getElementById('btnDentalRefresh')?.addEventListener('click',()=>load());
    document.querySelector('[data-dental-teeth]')?.addEventListener('click',(event)=>{const button=event.target instanceof Element?event.target.closest('[data-tooth]'):null;if(!button)return;event.currentTarget.querySelectorAll('[data-tooth]').forEach((item)=>item.classList.toggle('is-selected',item===button));const input=document.querySelector('[data-dental-tooth-input]');if(input)input.value=button.dataset.tooth||'';});
    mountSubmit('#dentalPatientForm',async(data,form)=>{try{const patient=await HealthVerticalService.createPatient({kind:'human',displayName:data.displayName,email:data.email||'',phone:data.phone||''});Store.update((draft)=>{draft.dentistry=draft.dentistry||{};draft.dentistry.patients=[patient,...(draft.dentistry.patients||[])];});form.reset();Toast.show('Paciente odontológico guardado.','success');}catch(error){Toast.show(`No se guardó el paciente: ${error.message}`,'error');}});
    mountSubmit('#dentalProfessionalForm',async(data,form)=>{try{const professional=await HealthVerticalService.createProfessional({fullName:data.fullName,specialty:data.specialty||'odontologia-general',licenseNumber:data.licenseNumber||'',status:'active',schedule:{}});Store.update((draft)=>{draft.dentistry=draft.dentistry||{};draft.dentistry.professionals=[professional,...(draft.dentistry.professionals||[])];});form.reset();Toast.show('Profesional odontológico guardado.','success');}catch(error){Toast.show(`No se guardó el profesional: ${error.message}`,'error');}});
    mountSubmit('#dentalAppointmentForm',async(data,form)=>{if(!data.appointmentPatientId)return Toast.show('Selecciona un paciente.','warning');try{const {startsAt,endsAt}=appointmentIso(data.date,data.time,45);const item=await HealthVerticalService.createAppointment({patientId:data.appointmentPatientId,professionalId:data.appointmentProfessionalId||null,startsAt,endsAt,type:'dentistry',status:'scheduled',reason:data.reason||'',channel:'onsite',notes:''});Store.update((draft)=>{draft.dentistry=draft.dentistry||{};draft.dentistry.appointments=[item,...(draft.dentistry.appointments||[])];});Toast.show('Cita odontológica registrada.','success');}catch(error){Toast.show(`No se registró la cita: ${error.message}`,'error');}});
    mountSubmit('#dentalEncounterForm',async(data,form)=>{if(!data.patientId)return Toast.show('Selecciona un paciente.','warning');if(!data.tooth)return Toast.show('Selecciona una pieza dental.','warning');try{const item=await HealthVerticalService.createEncounter({patientId:data.patientId,professionalId:data.professionalId||null,specialty:'dentistry',type:'dental-treatment',subjective:data.finding||'',objective:`Pieza ${data.tooth}`,assessment:data.assessment||'',plan:data.plan||'',diagnosisCodes:[],clinicalData:{tooth:data.tooth,procedure:data.procedure||'Evaluación'},confidential:false,status:'signed'});Store.update((draft)=>{draft.dentistry=draft.dentistry||{};draft.dentistry.encounters=[item,...(draft.dentistry.encounters||[])];});form.reset();form.querySelectorAll('[data-tooth]').forEach((node)=>node.classList.remove('is-selected'));Toast.show('Tratamiento odontológico registrado.','success');}catch(error){Toast.show(`No se registró el tratamiento: ${error.message}`,'error');}});
  }
};