import { AuthService } from '../services/authService.js';
import { BackendApi } from '../services/backendApi.js';
import { Field, Button } from '../components/ui/index.js';

function input({name,label,type='text',value='',autocomplete='',required=true,placeholder=''}){return Field({name,labelKey:label,type,value,required,placeholder,attrs:autocomplete?`autocomplete="${autocomplete}"`:''});}
function captchaBlock(id){return `<section class="login-captcha" data-captcha-box="${id}" aria-labelledby="captchaTitle-${id}"><input type="hidden" name="captchaToken" data-captcha-token><header class="login-captcha-head"><span class="login-captcha-icon"><i class="fa-solid fa-shield-halved"></i></span><div><strong id="captchaTitle-${id}">Verificación humana</strong><small>Reto firmado y temporal</small></div><button type="button" class="login-captcha-refresh" data-captcha-refresh aria-label="Generar nuevo reto"><i class="fa-solid fa-rotate"></i></button></header><div class="login-captcha-body"><div class="login-captcha-question"><small>Resuelve</small><strong data-captcha-question>cargando…</strong></div><label class="login-captcha-answer"><span>Resultado</span><input name="captchaAnswer" type="text" inputmode="numeric" autocomplete="off" pattern="-?[0-9]+" placeholder="Escribe el resultado" required></label></div><footer><span><i class="fa-solid fa-lock"></i> Reto protegido</span><span data-captcha-expiry>Válido por 5 minutos</span></footer></section>`;}
function coordinateChallenge(challenge){
  if(!challenge?.mfaRequired)return'';
  return `<div class="coordinate-challenge-layer" role="dialog" aria-modal="true" aria-labelledby="coordinateChallengeTitle"><section class="coordinate-challenge-card"><header><span><i class="fa-solid fa-table-cells-large"></i></span><div><p class="cgx-eyebrow">Segundo factor</p><h2 id="coordinateChallengeTitle">Tarjeta de coordenadas</h2><p>Consulta tu tarjeta versión ${Number(challenge.cardVersion||1)} e ingresa las tres casillas solicitadas.</p></div></header><form id="coordinateChallengeForm"><input type="hidden" name="challengeId" value="${challenge.challengeId}"><div class="coordinate-answer-grid">${(challenge.coordinates||[]).map((coordinate)=>`<label><span>${coordinate}</span><input name="coordinate_${coordinate}" inputmode="numeric" autocomplete="one-time-code" pattern="[0-9]{4}" maxlength="4" placeholder="0000" required></label>`).join('')}</div><p class="coordinate-expiry"><i class="fa-solid fa-clock"></i> Expira a las ${new Date(challenge.expiresAt).toLocaleTimeString('es-VE',{hour:'2-digit',minute:'2-digit'})}. Máximo ${Number(challenge.maxAttempts||3)} intentos.</p><div class="coordinate-actions">${Button({id:'btnCancelCoordinates',label:'Cancelar',iconName:'fa-arrow-left',variant:'secondary',type:'button'})}${Button({label:'Verificar y entrar',iconName:'fa-shield-check',variant:'primary',type:'submit'})}</div></form></section></div>`;
}

export const LoginPage={
  standalone:true,
  render(state){return `<main class="login-shell login-shell-v111"><section class="login-card"><button type="button" class="login-brand" data-route="login" aria-label="Ir al inicio de sesión"><div class="login-mark">C</div><div><h1>ContaGest-VE</h1><p>Enterprise ERP / CRM</p></div></button><div class="login-copy"><h2>Acceso seguro al sistema</h2><p>Ingresa con las credenciales asignadas por el administrador de tu empresa.</p></div><form id="loginForm" class="login-form"><div class="login-fields-grid">${input({name:'tenantRif',label:'RIF empresa',placeholder:'Ej: 00000000',autocomplete:'organization'})}${input({name:'email',label:'Correo electrónico',type:'email',placeholder:'usuario@empresa.com',autocomplete:'email'})}${input({name:'password',label:'Contraseña',type:'password',placeholder:'••••••••',autocomplete:'current-password'})}</div><details class="login-license-details"><summary><span><i class="fa-solid fa-key"></i> Acceso de cliente con licencia</span><small>Pruebas y planes controlados</small></summary><div class="login-license-body">${input({name:'licenseKey',label:'Clave de licencia',type:'password',required:false,placeholder:'CGVE-GYM-…',autocomplete:'off'})}<p><i class="fa-solid fa-building-shield"></i> La licencia debe coincidir con RIF, correo y dispositivo.</p></div></details>${captchaBlock('login')}${Button({label:'Entrar al sistema',iconName:'fa-arrow-right-to-bracket',variant:'primary',type:'submit',className:'w-full login-submit'})}</form><details class="login-note login-tech-note"><summary>Acceso técnico / pruebas internas</summary><div class="login-tech-body"><p>Administrador de seed:</p><code>RIF: 00000000</code><br><code>Email: admin@erp.local</code><br><code>Clave: Adm1n$2026</code><div class="mt-3 flex gap-2 flex-wrap">${Button({id:'btnFillAdmin',label:'Rellenar admin',iconName:'fa-key',variant:'secondary',type:'button'})}${Button({id:'btnDemoLogin',label:'Demo local',iconName:'fa-flask',variant:'secondary',type:'button'})}</div><p class="mt-3"><strong>Backend:</strong> <span>${BackendApi.baseUrl}</span></p></div></details></section><section class="login-panel"><div><p class="pl-eyebrow">ERP empresarial</p><h2>Operación, administración y verticales especializados en una sola plataforma.</h2><ul><li>Acceso por empresa, usuario, rol, licencia y dispositivo.</li><li>Segundo factor con tarjeta de coordenadas.</li><li>Comercio, salud, veterinaria y gimnasios.</li><li>Experiencia responsive para escritorio, tablet y móvil.</li></ul></div></section>${coordinateChallenge(state.pendingMfa)}</main>`;},
  mount(state,{Store,Toast,navigate,SupabaseSyncService}){
    const failedKey='contagest_login_captcha_failures',lockKey='contagest_login_captcha_locked_until';
    const captchaLocked=()=>Number(localStorage.getItem(lockKey)||0)>Date.now();
    const registerFailure=()=>{const attempts=Number(localStorage.getItem(failedKey)||0)+1;localStorage.setItem(failedKey,String(attempts));if(attempts>=3){localStorage.setItem(lockKey,String(Date.now()+60000));localStorage.setItem(failedKey,'0');}};
    const clearFailures=()=>{localStorage.removeItem(failedKey);localStorage.removeItem(lockKey);};
    const loadCaptcha=async(form)=>{if(!form)return;const question=form.querySelector('[data-captcha-question]'),token=form.querySelector('[data-captcha-token]'),answer=form.querySelector('[name="captchaAnswer"]'),expiry=form.querySelector('[data-captcha-expiry]'),box=form.querySelector('[data-captcha-box]');box?.classList.add('is-loading');try{const captcha=await AuthService.captcha();if(question){question.textContent=`${captcha.question} = ?`;question.setAttribute('aria-label',captcha.prompt||captcha.question);}if(token)token.value=captcha.token;if(answer){answer.value='';answer.removeAttribute('disabled');}if(expiry)expiry.textContent=`Válido hasta ${new Date(captcha.expiresAt).toLocaleTimeString('es-VE',{hour:'2-digit',minute:'2-digit'})}`;box?.classList.remove('is-error');}catch{if(question)question.textContent='Servicio no disponible';answer?.setAttribute('disabled','disabled');box?.classList.add('is-error');}finally{box?.classList.remove('is-loading');}};
    const setSessionState=(session)=>{const licenseMode=session.license?.businessSector;Store.set({pendingMfa:null,route:'dashboard',profile:{name:session.user?.fullName||session.user?.name||'Usuario',email:session.user?.email||'',role:session.user?.role||'admin',branch:session.tenant?.name||'Empresa',plan:session.license?.plan||session.tenant?.plan||'Enterprise',avatarDataUrl:Store.get().profile?.avatarDataUrl||''},activeLicense:session.license||null,settings:{...Store.get().settings,companyName:session.tenant?.name||Store.get().settings.companyName,companyRif:session.tenant?.rif||Store.get().settings.companyRif,...(licenseMode?{businessMode:licenseMode}:{})}});};
    const finish=async(session)=>{setSessionState(session);Toast.show(session.license?'Licencia y seguridad verificadas.':'Sesión segura iniciada.','success');await SupabaseSyncService?.syncCore?.({Store,Toast,force:true,silent:true});navigate('dashboard');};
    const loginForm=document.getElementById('loginForm');loadCaptcha(loginForm);document.querySelectorAll('[data-captcha-refresh]').forEach((button)=>button.addEventListener('click',()=>loadCaptcha(button.closest('form'))));
    document.getElementById('btnFillAdmin')?.addEventListener('click',()=>{loginForm.tenantRif.value='00000000';loginForm.email.value='admin@erp.local';loginForm.password.value='Adm1n$2026';loginForm.licenseKey.value='';Toast.show('Credenciales administrativas cargadas.','success');});
    loginForm?.addEventListener('submit',async(event)=>{event.preventDefault();if(captchaLocked())return Toast.show('Verificación bloqueada por un minuto.','error');const data=Object.fromEntries(new FormData(event.currentTarget)),submit=event.currentTarget.querySelector('[type="submit"]');submit?.setAttribute('disabled','disabled');try{const result=await AuthService.login({...data,mode:'api'});clearFailures();if(result.mfaRequired){Store.set({pendingMfa:result});Toast.show('Contraseña correcta. Completa la tarjeta de coordenadas.','info');return;}await finish(result);}catch(error){registerFailure();Toast.show(error.message||'No se pudo iniciar sesión.','error');await loadCaptcha(event.currentTarget);}finally{submit?.removeAttribute('disabled');}});
    document.getElementById('coordinateChallengeForm')?.addEventListener('submit',async(event)=>{event.preventDefault();const form=event.currentTarget,challengeId=form.challengeId.value,answers=Object.fromEntries([...form.querySelectorAll('[name^="coordinate_"]')].map((input)=>[input.name.replace('coordinate_',''),input.value]));const submit=form.querySelector('[type="submit"]');submit?.setAttribute('disabled','disabled');try{await finish(await AuthService.completeCoordinateLogin(challengeId,answers));}catch(error){Toast.show(error.message,'error');submit?.removeAttribute('disabled');}});
    document.getElementById('btnCancelCoordinates')?.addEventListener('click',()=>Store.set({pendingMfa:null}));
    document.getElementById('btnDemoLogin')?.addEventListener('click',async()=>finish(await AuthService.login({email:'admin@erp.local',password:'Adm1n$2026',tenantRif:'00000000',mode:'demo'})));
  }
};
