import { PageHeader, Field, Select, Button, Badge, EmptyState, ErpDataTable, ErpSection } from '../components/ui/index.js';
import { escapeHtml, mountSubmit, qsa } from '../utils/dom.js';
import { PriceBooksService } from '../services/priceBooksService.js';
import { BusinessLocationsService } from '../services/businessLocationsService.js';

const safe=(value)=>escapeHtml(String(value??''));
const money=(value,currency)=>`${safe(currency)} ${Number(value||0).toFixed(2)}`;
const tone=(status)=>status==='active'?'success':'neutral';
const productOptions=(products)=>[{value:'',label:'Selecciona un producto'},...(products||[]).map((product)=>({value:product.id,label:`${product.sku} · ${product.name}`}))];
const locationOptions=(locations)=>[{value:'',label:'Global / sin sede específica'},...(locations||[]).filter((item)=>item.status==='active').map((item)=>({value:item.id,label:`${item.code} · ${item.name}`}))];

export const PriceBooksPage={
  render(state,{query={}}={}){
    const books=state.priceBooks||[];
    const products=state.priceBookProducts||[];
    const locations=state.businessLocations||[];
    const selected=books.find((book)=>book.id===query.book)||books.find((book)=>!book.isSystem)||null;
    const entries=state.priceBookEntries?.[selected?.id]||[];
    const preview=state.priceBookPreview||null;
    const rows=books.length?ErpDataTable({caption:'Listas de precio',columns:[{key:'code',label:'Código'},{key:'name',label:'Nombre'},{key:'currency',label:'Moneda'},{key:'priceMode',label:'Política'},{key:'priority',label:'Prioridad'},{key:'status',label:'Estado',render:(row)=>Badge(row.status,tone(row.status))},{key:'actions',label:'Acciones',render:(row)=>`<button type="button" class="btn btn-secondary" data-price-book="${safe(row.id)}">Ver</button>`}],rows:books}):EmptyState({title:'Sin listas de precio',description:'Crea una lista comercial; Product.price legacy se mantiene sólo como compatibilidad.',iconName:'fa-tags'});
    const entryRows=selected&&entries.length?ErpDataTable({caption:`Precios · ${safe(selected.code)}`,columns:[{key:'targetId',label:'Producto',render:(row)=>safe(products.find((p)=>p.id===row.targetId)?.name||row.targetId)},{key:'amount',label:'Monto',render:(row)=>money(row.amount,selected.currency)},{key:'effectiveFrom',label:'Desde',render:(row)=>safe(new Date(row.effectiveFrom).toLocaleString())},{key:'effectiveTo',label:'Hasta',render:(row)=>row.effectiveTo?safe(new Date(row.effectiveTo).toLocaleString()):'Vigente'},{key:'version',label:'Versión'}],rows:entries}):EmptyState({title:selected?'Sin precios configurados':'Selecciona una lista',description:selected?'Agrega la primera versión efectiva para un producto.':'Elige una lista para revisar su línea temporal.',iconName:'fa-receipt'});
    const bookForm=`<form id="priceBookForm" class="cg-ui-stack cg-ui-gap-md">${Field({labelKey:'Código',name:'code',required:true,placeholder:'MAYORISTA'})}${Field({labelKey:'Nombre',name:'name',required:true,placeholder:'Mayoristas'})}${Select({labelKey:'Moneda fijada / referencia',name:'currency',value:'VES',options:[{value:'VES',label:'VES'},{value:'USD',label:'USD'},{value:'EUR',label:'EUR'}]})}${Select({labelKey:'Política monetaria',name:'priceMode',value:'fixed',options:[{value:'fixed',label:'Precio fijo en la moneda de la lista'},{value:'fx_derived',label:'Derivado con evidencia FX del documento'}]})}${Field({labelKey:'Prioridad',name:'priority',type:'number',value:'100'})}${Select({labelKey:'Alcance',name:'locationScope',value:'global',options:[{value:'global',label:'Global'},{value:'specific_locations',label:'Sede específica'}]})}${Select({labelKey:'Sede',name:'locationId',options:locationOptions(locations)})}${Button({text:'Crear lista',type:'submit',icon:'fa-plus'})}</form>`;
    const entryForm=selected&&!selected.isSystem?`<form id="priceEntryForm" class="cg-ui-stack cg-ui-gap-md"><input type="hidden" name="bookId" value="${safe(selected.id)}">${Select({labelKey:'Producto',name:'targetId',options:productOptions(products)})}${Field({labelKey:'Monto exacto',name:'amount',value:'0.00',required:true})}${Field({labelKey:'Vigente desde',name:'effectiveFrom',type:'datetime-local',required:true})}${Button({text:'Agregar versión de precio',type:'submit',icon:'fa-plus'})}</form>`:`<p class="cg-ui-muted">${selected?.isSystem?'La lista LEGACY_PRODUCT se sincroniza únicamente desde Product.price.':'Selecciona una lista editable.'}</p>`;
    const previewForm=`<form id="pricePreviewForm" class="cg-ui-stack cg-ui-gap-md">${Select({labelKey:'Producto',name:'targetId',options:productOptions(products)})}${Select({labelKey:'Moneda del documento',name:'currency',value:'VES',options:[{value:'VES',label:'VES'},{value:'USD',label:'USD'},{value:'EUR',label:'EUR'}]})}${Select({labelKey:'Sede opcional',name:'businessLocationId',options:locationOptions(locations)})}${Field({labelKey:'Tasa FX externa (si aplica)',name:'fxRate',placeholder:'45.0000'})}${Field({labelKey:'Fuente FX (si aplica)',name:'fxRateSource',placeholder:'BCV / financial authority'})}${Button({text:'Resolver precio',type:'submit',icon:'fa-magnifying-glass-dollar'})}</form>${preview?`<div class="cg-ui-callout"><strong>${money(preview.amount,preview.currency)}</strong><div>${safe(preview.reason)}</div><small>Book ${safe(preview.priceBookId)} · Entry ${safe(preview.priceEntryId)} · v${safe(preview.priceEntryVersion)}</small></div>`:''}`;
    return `<section class="cg-page-stack">${PageHeader({eyebrowKey:'Core',titleKey:'Listas de precio',descKey:'Autoridad única de precio base: moneda, vigencia, precedencia y evidencia auditable.'})}<div class="cg-ui-grid cg-ui-grid-two">${ErpSection({title:'Nueva lista',description:'Impuestos, promociones y FX permanecen en sus autoridades separadas.',content:bookForm})}${ErpSection({title:'Resolver / explicar precio',description:'El navegador solicita una resolución; nunca envía source/version como authority.',content:previewForm})}</div>${ErpSection({title:'Listas del tenant',description:'Prioridad igual en candidatos efectivos produce error de configuración, no selección arbitraria.',content:rows})}<div class="cg-ui-grid cg-ui-grid-two">${ErpSection({title:selected?`Nueva versión · ${selected.code}`:'Nueva versión',description:'Las correcciones se versionan por intervalo efectivo.',content:entryForm})}${ErpSection({title:'Línea temporal',description:'Un precio ya usado conserva su snapshot histórico.',content:entryRows})}</div></section>`;
  },
  mount(state,{Store,Toast,UrlStateService,Loading}){
    const load=async()=>{try{Loading?.mount?.('Cargando pricing…');const [priceBooks,priceBookProducts,businessLocations]=await Promise.all([PriceBooksService.list(),PriceBooksService.products(),BusinessLocationsService.list()]);Store.set({priceBooks,priceBookProducts,businessLocations,priceBooksLoadedAt:new Date().toISOString()});}catch(error){Toast.show(`No se pudo cargar pricing: ${error.message}`,'error');}finally{Loading?.unmount?.();}};
    if(!state.priceBooksLoadedAt)load();
    const selected=(state.priceBooks||[]).find((book)=>book.id===new URLSearchParams(location.search).get('book'))||(state.priceBooks||[]).find((book)=>!book.isSystem);
    if(selected&&!state.priceBookEntries?.[selected.id])PriceBooksService.entries(selected.id).then((rows)=>Store.update((draft)=>{draft.priceBookEntries={...(draft.priceBookEntries||{}),[selected.id]:rows};})).catch((error)=>Toast.show(error.message,'error'));
    mountSubmit('#priceBookForm',async(data)=>{try{const payload={code:data.code,name:data.name,currency:data.currency,priceMode:data.priceMode,priority:Number(data.priority||100),locationScope:data.locationScope,locationIds:data.locationScope==='specific_locations'&&data.locationId?[data.locationId]:[]};const saved=await PriceBooksService.create(payload);Store.update((draft)=>{draft.priceBooks=[saved,...(draft.priceBooks||[])];});UrlStateService.setParams({book:saved.id});Toast.show('Lista de precios creada.','success');}catch(error){Toast.show(error.message,'error');}});
    mountSubmit('#priceEntryForm',async(data)=>{try{if(!data.targetId)throw new Error('Selecciona un producto.');const saved=await PriceBooksService.addEntry(data.bookId,{targetType:'product',targetId:data.targetId,amount:data.amount,effectiveFrom:data.effectiveFrom});Store.update((draft)=>{draft.priceBookEntries={...(draft.priceBookEntries||{}),[data.bookId]:[saved,...(draft.priceBookEntries?.[data.bookId]||[])]};});Toast.show('Versión de precio creada.','success');}catch(error){Toast.show(error.message,'error');}});
    mountSubmit('#pricePreviewForm',async(data)=>{try{if(!data.targetId)throw new Error('Selecciona un producto.');const payload={targetType:'product',targetId:data.targetId,currency:data.currency,businessLocationId:data.businessLocationId||null};if(data.fxRate){payload.fxRate=data.fxRate;payload.fxRateDate=new Date().toISOString();payload.fxRateSource=data.fxRateSource||'financial-authority';}const priceBookPreview=await PriceBooksService.preview(payload);Store.set({priceBookPreview});Toast.show('Precio resuelto con evidencia.','success');}catch(error){Toast.show(error.message,'error');}});
    qsa('[data-price-book]').forEach((button)=>button.addEventListener('click',()=>UrlStateService.setParams({book:button.dataset.priceBook})));
  }
};
