const es = {
  appTitle:'ERP empresarial', appSubtitle:'Gestión comercial, contable, fiscal y operativa',
  dashboard:'Dashboard', sales:'Ventas', quote:'Cotizador', clients:'Clientes', history:'Histórico', inventory:'Inventario', taxes:'Tributos', regulatory:'Normativa', reports:'Reportes', ledger:'Contabilidad', banking:'Bancos', payroll:'Nómina', suppliers:'Proveedores', purchases:'Compras', audit:'Auditoría', analytics:'Analítica', tasks:'Tareas', profile:'Perfil', settings:'Configuración', help:'Ayuda', supportCta:'Soporte', qrBarcode:'QR / Barcode', inventoryScanner:'Escáner de inventario', salesBook:'Libro de ventas', chartAccounts:'Plan de cuentas', generalLedger:'Libro mayor', trialBalance:'Balance de sumas y saldos', worksheet:'Hoja de trabajo', financialStatements:'Estados financieros', accountingClose:'Cierre contable', accountingStandards:'Normativa contable', dataImport:'Carga masiva', businessRules:'Reglas de negocio', moduleMaturity:'Módulos disponibles', licenses:'Licencias', aiAssistant:'Asistente IA', orders:'Pedidos', posCounter:'POS', orderTracking:'Seguimiento de pedidos', deliveryMap:'Mapa de entregas', healthcare:'Clínica', veterinary:'Clínica veterinaria', gym:'Gimnasio', routines:'Rutinas', nutrition:'Nutrición', messages:'Mensajes',
  dashboardEyebrow:'Centro ejecutivo', dashboardTitle:'Panel gerencial', dashboardDesc:'Indicadores de ventas, inventario, contabilidad, nómina y operación.',
  salesEyebrow:'Ventas', salesTitle:'Ventas y cobranza', salesDesc:'Registro de ventas, clientes, cobros y documentos comerciales.',
  quoteEyebrow:'Ventas', quoteTitle:'Cotizador y factura', quoteDesc:'Calcula impuestos, retenciones, totales en Bs/USD y genera documentos.',
  clientsEyebrow:'CRM', clientsTitle:'Clientes', clientsDesc:'Directorio comercial con datos fiscales y contacto.',
  inventoryEyebrow:'Operaciones', inventoryTitle:'Inventario y productos', inventoryDesc:'Control de existencias, costo, precio, margen y disponibilidad.',
  taxesEyebrow:'Fiscal', taxesTitle:'Tributos', taxesDesc:'Impuestos y retenciones configurables según la operación.',
  regulatoryEyebrow:'Legal', regulatoryTitle:'Normativa', regulatoryDesc:'Fuentes y actualizaciones regulatorias para consulta.',
  historyEyebrow:'Archivo', historyTitle:'Histórico comercial', historyDesc:'Consulta, exporta, duplica y regenera documentos.',
  reportsEyebrow:'Inteligencia empresarial', reportsTitle:'Reportes y análisis', reportsDesc:'Indicadores financieros, operativos y comerciales por período.',
  ledgerEyebrow:'Contabilidad', ledgerTitle:'Libro diario', ledgerDesc:'Registra asientos y valida la partida doble.',
  bankingEyebrow:'Tesorería', bankingTitle:'Bancos y conciliación', bankingDesc:'Movimientos, saldos y conciliación bancaria.',
  payrollEyebrow:'Talento humano', payrollTitle:'Nómina', payrollDesc:'Cálculo y control de pagos, deducciones y recibos.',
  suppliersEyebrow:'Compras', suppliersTitle:'Proveedores', suppliersDesc:'Directorio de proveedores y soporte al proceso de compras.',
  auditEyebrow:'Control interno', auditTitle:'Auditoría y riesgos', auditDesc:'Alertas, trazabilidad y controles operativos.',
  analyticsEyebrow:'Analítica', analyticsTitle:'Uso y rendimiento', analyticsDesc:'Actividad, navegación y calidad operativa del sistema.',
  tasksEyebrow:'Operaciones', tasksTitle:'Tareas y seguimiento', tasksDesc:'Responsables, fechas, prioridades, dependencias y estado.',
  settingsEyebrow:'Sistema', settingsTitle:'Configuración empresarial', settingsDesc:'Empresa, apariencia, idioma, integraciones y respaldo.',
  helpEyebrow:'Ayuda', helpTitle:'Centro de ayuda', helpDesc:'Guías y recursos para la operación del sistema.',
  supportEyebrow:'Soporte', supportTitle:'Soporte técnico', supportDesc:'Canales de atención, base de ayuda e incidencias.',
  healthcareEyebrow:'Gestión clínica', healthcareTitle:'Clínica y consultorio', healthcareDesc:'Pacientes, profesionales, agenda, historias clínicas y seguimiento.',
  veterinaryEyebrow:'Gestión veterinaria', veterinaryTitle:'Clínica veterinaria', veterinaryDesc:'Mascotas, tutores, agenda, historias, vacunas y seguimiento.',
  save:'Guardar', add:'Agregar', edit:'Editar', delete:'Eliminar', duplicate:'Duplicar', exportCsv:'Exportar CSV', exportJson:'Exportar JSON', generatePdf:'Generar PDF', saveHistory:'Guardar en histórico', clear:'Limpiar', search:'Buscar', refresh:'Actualizar', sync:'Sincronizar', print:'Imprimir', download:'Descargar', close:'Cerrar', cancel:'Cancelar', confirm:'Confirmar', newRecord:'Nuevo', noData:'Sin datos',
  name:'Nombre', rif:'RIF', email:'Correo', phone:'Teléfono', type:'Tipo', address:'Dirección', actions:'Acciones', client:'Cliente', date:'Fecha', amount:'Monto', currency:'Moneda', observation:'Observación', product:'Producto', qty:'Cantidad', price:'Precio', sku:'SKU', category:'Categoría', cost:'Costo', margin:'Margen', stock:'Existencia', reserved:'Reservado', minimum:'Mínimo', account:'Cuenta', description:'Descripción', debit:'Debe', credit:'Haber', employee:'Trabajador', salary:'Salario', days:'Días', overtimeHours:'Horas extra', bonus:'Bono', deductionsExtra:'Deducciones extra', supplier:'Proveedor', reference:'Referencia', bank:'Banco', status:'Estado', invoice:'Factura', method:'Método', title:'Título', module:'Módulo', priority:'Prioridad', role:'Rol', branch:'Sucursal', plan:'Plan', language:'Idioma', theme:'Tema', reportsCurrency:'Moneda de reportes', source:'Fuente', bcvRate:'Tasa del día',
  synced:'Sincronizado', pendingSync:'Pendiente de sincronización', active:'Activo', inactive:'Inactivo', pending:'Pendiente', completed:'Completado', cancelled:'Cancelado', all:'Todos', today:'Hoy', yes:'Sí', no:'No', light:'Claro', dark:'Oscuro',
  company:'Empresa', appearance:'Apariencia', integrations:'Integraciones', backup:'Respaldo', security:'Seguridad', privacy:'Privacidad', support:'Soporte', logout:'Cerrar sesión', changePhoto:'Cambiar foto', unifiedManagement:'Gestión empresarial unificada'
};

const en = {
  appTitle:'Business ERP', appSubtitle:'Commercial, accounting, tax and operations management',
  dashboard:'Dashboard', sales:'Sales', quote:'Quotes', clients:'Clients', history:'History', inventory:'Inventory', taxes:'Taxes', regulatory:'Regulations', reports:'Reports', ledger:'Accounting', banking:'Banking', payroll:'Payroll', suppliers:'Suppliers', purchases:'Purchases', audit:'Audit', analytics:'Analytics', tasks:'Tasks', profile:'Profile', settings:'Settings', help:'Help', supportCta:'Support', qrBarcode:'QR / Barcode', inventoryScanner:'Inventory scanner', salesBook:'Sales book', chartAccounts:'Chart of accounts', generalLedger:'General ledger', trialBalance:'Trial balance', worksheet:'Worksheet', financialStatements:'Financial statements', accountingClose:'Accounting close', accountingStandards:'Accounting standards', dataImport:'Bulk import', businessRules:'Business rules', moduleMaturity:'Available modules', licenses:'Licenses', aiAssistant:'AI assistant', orders:'Orders', posCounter:'POS', orderTracking:'Order tracking', deliveryMap:'Delivery map', healthcare:'Clinic', veterinary:'Veterinary clinic', gym:'Gym', routines:'Routines', nutrition:'Nutrition', messages:'Messages',
  dashboardEyebrow:'Executive center', dashboardTitle:'Management dashboard', dashboardDesc:'Sales, inventory, accounting, payroll and operations indicators.',
  salesEyebrow:'Sales', salesTitle:'Sales and collections', salesDesc:'Sales, clients, collections and commercial document management.',
  quoteEyebrow:'Sales', quoteTitle:'Quote and invoice', quoteDesc:'Calculate taxes, withholdings, Bs/USD totals and generate documents.',
  clientsEyebrow:'CRM', clientsTitle:'Clients', clientsDesc:'Commercial directory with tax and contact information.',
  inventoryEyebrow:'Operations', inventoryTitle:'Inventory and products', inventoryDesc:'Stock, cost, price, margin and availability control.',
  taxesEyebrow:'Tax', taxesTitle:'Taxes', taxesDesc:'Configurable taxes and withholdings for each transaction.',
  regulatoryEyebrow:'Legal', regulatoryTitle:'Regulations', regulatoryDesc:'Regulatory sources and updates for reference.',
  historyEyebrow:'Archive', historyTitle:'Commercial history', historyDesc:'Review, export, duplicate and regenerate documents.',
  reportsEyebrow:'Business intelligence', reportsTitle:'Reports and analytics', reportsDesc:'Financial, operational and commercial indicators by period.',
  ledgerEyebrow:'Accounting', ledgerTitle:'Journal', ledgerDesc:'Record entries and validate double-entry accounting.',
  bankingEyebrow:'Treasury', bankingTitle:'Banking and reconciliation', bankingDesc:'Transactions, balances and bank reconciliation.',
  payrollEyebrow:'People', payrollTitle:'Payroll', payrollDesc:'Payroll, deductions and payslip management.',
  suppliersEyebrow:'Purchasing', suppliersTitle:'Suppliers', suppliersDesc:'Supplier directory and purchasing support.',
  auditEyebrow:'Internal control', auditTitle:'Audit and risk', auditDesc:'Alerts, traceability and operational controls.',
  analyticsEyebrow:'Analytics', analyticsTitle:'Usage and performance', analyticsDesc:'System activity, navigation and operational quality.',
  tasksEyebrow:'Operations', tasksTitle:'Tasks and follow-up', tasksDesc:'Owners, dates, priorities, dependencies and status.',
  settingsEyebrow:'System', settingsTitle:'Business settings', settingsDesc:'Company, appearance, language, integrations and backup.',
  helpEyebrow:'Help', helpTitle:'Help center', helpDesc:'Guides and resources for operating the system.',
  supportEyebrow:'Support', supportTitle:'Technical support', supportDesc:'Support channels, knowledge base and incidents.',
  healthcareEyebrow:'Clinical management', healthcareTitle:'Clinic and practice', healthcareDesc:'Patients, professionals, scheduling, clinical records and follow-up.',
  veterinaryEyebrow:'Veterinary management', veterinaryTitle:'Veterinary clinic', veterinaryDesc:'Pets, guardians, scheduling, records, vaccines and follow-up.',
  save:'Save', add:'Add', edit:'Edit', delete:'Delete', duplicate:'Duplicate', exportCsv:'Export CSV', exportJson:'Export JSON', generatePdf:'Generate PDF', saveHistory:'Save to history', clear:'Clear', search:'Search', refresh:'Refresh', sync:'Sync', print:'Print', download:'Download', close:'Close', cancel:'Cancel', confirm:'Confirm', newRecord:'New', noData:'No data',
  name:'Name', rif:'Tax ID', email:'Email', phone:'Phone', type:'Type', address:'Address', actions:'Actions', client:'Client', date:'Date', amount:'Amount', currency:'Currency', observation:'Notes', product:'Product', qty:'Quantity', price:'Price', sku:'SKU', category:'Category', cost:'Cost', margin:'Margin', stock:'Stock', reserved:'Reserved', minimum:'Minimum', account:'Account', description:'Description', debit:'Debit', credit:'Credit', employee:'Employee', salary:'Salary', days:'Days', overtimeHours:'Overtime hours', bonus:'Bonus', deductionsExtra:'Extra deductions', supplier:'Supplier', reference:'Reference', bank:'Bank', status:'Status', invoice:'Invoice', method:'Method', title:'Title', module:'Module', priority:'Priority', role:'Role', branch:'Branch', plan:'Plan', language:'Language', theme:'Theme', reportsCurrency:'Report currency', source:'Source', bcvRate:'Daily rate',
  synced:'Synced', pendingSync:'Pending sync', active:'Active', inactive:'Inactive', pending:'Pending', completed:'Completed', cancelled:'Cancelled', all:'All', today:'Today', yes:'Yes', no:'No', light:'Light', dark:'Dark', company:'Company', appearance:'Appearance', integrations:'Integrations', backup:'Backup', security:'Security', privacy:'Privacy', support:'Support', logout:'Sign out', changePhoto:'Change photo', unifiedManagement:'Unified business management'
};

const zh = {
  appTitle:'企业 ERP', appSubtitle:'销售、会计、税务与运营管理', dashboard:'仪表板', sales:'销售', quote:'报价', clients:'客户', history:'历史记录', inventory:'库存', taxes:'税务', regulatory:'法规', reports:'报表', ledger:'会计', banking:'银行', payroll:'薪资', suppliers:'供应商', purchases:'采购', audit:'审计', analytics:'分析', tasks:'任务', profile:'个人资料', settings:'设置', help:'帮助', supportCta:'支持', qrBarcode:'二维码 / 条码', inventoryScanner:'库存扫描', salesBook:'销售账簿', chartAccounts:'会计科目表', generalLedger:'总账', trialBalance:'试算平衡', worksheet:'工作表', financialStatements:'财务报表', accountingClose:'会计结账', accountingStandards:'会计准则', dataImport:'批量导入', businessRules:'业务规则', moduleMaturity:'可用模块', licenses:'许可证', aiAssistant:'AI 助手', orders:'订单', posCounter:'POS', orderTracking:'订单跟踪', deliveryMap:'配送地图', healthcare:'诊所', veterinary:'兽医诊所', gym:'健身房', routines:'训练计划', nutrition:'营养', messages:'消息',
  dashboardEyebrow:'管理中心', dashboardTitle:'管理仪表板', dashboardDesc:'销售、库存、会计、薪资和运营指标。', salesEyebrow:'销售', salesTitle:'销售与收款', salesDesc:'管理销售、客户、收款和商业单据。', quoteEyebrow:'销售', quoteTitle:'报价与发票', quoteDesc:'计算税费、代扣款、Bs/USD 总额并生成单据。', clientsEyebrow:'CRM', clientsTitle:'客户', clientsDesc:'包含税务与联系信息的客户目录。', inventoryEyebrow:'运营', inventoryTitle:'库存与产品', inventoryDesc:'管理库存、成本、价格、利润和可用量。', reportsEyebrow:'商业智能', reportsTitle:'报表与分析', reportsDesc:'按期间查看财务、运营和商业指标。', healthcareEyebrow:'临床管理', healthcareTitle:'诊所管理', healthcareDesc:'患者、专业人员、预约、病历和随访。', veterinaryEyebrow:'兽医管理', veterinaryTitle:'兽医诊所', veterinaryDesc:'宠物、主人、预约、病历、疫苗和随访。', settingsEyebrow:'系统', settingsTitle:'企业设置', settingsDesc:'公司、外观、语言、集成与备份。',
  save:'保存', add:'添加', edit:'编辑', delete:'删除', duplicate:'复制', exportCsv:'导出 CSV', exportJson:'导出 JSON', generatePdf:'生成 PDF', clear:'清除', search:'搜索', refresh:'刷新', sync:'同步', print:'打印', download:'下载', close:'关闭', cancel:'取消', confirm:'确认', newRecord:'新建', noData:'暂无数据', name:'名称', rif:'税号', email:'电子邮件', phone:'电话', type:'类型', address:'地址', actions:'操作', client:'客户', date:'日期', amount:'金额', currency:'货币', product:'产品', qty:'数量', price:'价格', category:'类别', cost:'成本', margin:'利润', stock:'库存', account:'账户', description:'说明', debit:'借方', credit:'贷方', employee:'员工', salary:'薪资', supplier:'供应商', reference:'参考', bank:'银行', status:'状态', invoice:'发票', method:'方式', title:'标题', module:'模块', priority:'优先级', role:'角色', branch:'分支', plan:'套餐', language:'语言', theme:'主题', source:'来源', bcvRate:'当日汇率', synced:'已同步', pendingSync:'等待同步', active:'启用', inactive:'停用', pending:'待处理', completed:'已完成', cancelled:'已取消', all:'全部', today:'今天', light:'浅色', dark:'深色', company:'公司', appearance:'外观', integrations:'集成', backup:'备份', security:'安全', privacy:'隐私', support:'支持', logout:'退出登录', changePhoto:'更换照片', unifiedManagement:'统一企业管理'
};

const hi = {
  appTitle:'व्यावसायिक ERP', appSubtitle:'बिक्री, लेखांकन, कर और संचालन प्रबंधन', dashboard:'डैशबोर्ड', sales:'बिक्री', quote:'कोटेशन', clients:'ग्राहक', history:'इतिहास', inventory:'इन्वेंटरी', taxes:'कर', regulatory:'नियम', reports:'रिपोर्ट', ledger:'लेखांकन', banking:'बैंकिंग', payroll:'पेरोल', suppliers:'आपूर्तिकर्ता', purchases:'खरीद', audit:'ऑडिट', analytics:'विश्लेषण', tasks:'कार्य', profile:'प्रोफ़ाइल', settings:'सेटिंग्स', help:'सहायता', supportCta:'सहायता', qrBarcode:'QR / बारकोड', inventoryScanner:'इन्वेंटरी स्कैनर', salesBook:'बिक्री पुस्तक', chartAccounts:'खाता सूची', generalLedger:'महाबही', trialBalance:'ट्रायल बैलेंस', worksheet:'वर्कशीट', financialStatements:'वित्तीय विवरण', accountingClose:'लेखा समापन', accountingStandards:'लेखा मानक', dataImport:'बल्क इम्पोर्ट', businessRules:'व्यावसायिक नियम', moduleMaturity:'उपलब्ध मॉड्यूल', licenses:'लाइसेंस', aiAssistant:'AI सहायक', orders:'ऑर्डर', posCounter:'POS', orderTracking:'ऑर्डर ट्रैकिंग', deliveryMap:'डिलीवरी मैप', healthcare:'क्लिनिक', veterinary:'पशु चिकित्सालय', gym:'जिम', routines:'रूटीन', nutrition:'पोषण', messages:'संदेश',
  dashboardEyebrow:'कार्यकारी केंद्र', dashboardTitle:'प्रबंधन डैशबोर्ड', dashboardDesc:'बिक्री, इन्वेंटरी, लेखांकन, पेरोल और संचालन संकेतक।', salesEyebrow:'बिक्री', salesTitle:'बिक्री और वसूली', salesDesc:'बिक्री, ग्राहक, वसूली और व्यावसायिक दस्तावेज़ प्रबंधन।', quoteEyebrow:'बिक्री', quoteTitle:'कोटेशन और चालान', quoteDesc:'कर, कटौती, Bs/USD कुल और दस्तावेज़ तैयार करें।', clientsEyebrow:'CRM', clientsTitle:'ग्राहक', clientsDesc:'कर और संपर्क जानकारी सहित ग्राहक निर्देशिका।', inventoryEyebrow:'संचालन', inventoryTitle:'इन्वेंटरी और उत्पाद', inventoryDesc:'स्टॉक, लागत, मूल्य, मार्जिन और उपलब्धता नियंत्रण।', reportsEyebrow:'व्यावसायिक बुद्धिमत्ता', reportsTitle:'रिपोर्ट और विश्लेषण', reportsDesc:'अवधि के अनुसार वित्तीय, संचालन और व्यावसायिक संकेतक।', healthcareEyebrow:'क्लिनिकल प्रबंधन', healthcareTitle:'क्लिनिक प्रबंधन', healthcareDesc:'मरीज़, विशेषज्ञ, अपॉइंटमेंट, मेडिकल रिकॉर्ड और फॉलो-अप।', veterinaryEyebrow:'पशु चिकित्सा प्रबंधन', veterinaryTitle:'पशु चिकित्सालय', veterinaryDesc:'पालतू पशु, अभिभावक, अपॉइंटमेंट, रिकॉर्ड, टीके और फॉलो-अप।', settingsEyebrow:'सिस्टम', settingsTitle:'व्यावसायिक सेटिंग्स', settingsDesc:'कंपनी, रूप, भाषा, इंटीग्रेशन और बैकअप।',
  save:'सहेजें', add:'जोड़ें', edit:'संपादित करें', delete:'हटाएँ', duplicate:'प्रतिलिपि', exportCsv:'CSV निर्यात', exportJson:'JSON निर्यात', generatePdf:'PDF बनाएँ', clear:'साफ़ करें', search:'खोजें', refresh:'रीफ़्रेश', sync:'सिंक', print:'प्रिंट', download:'डाउनलोड', close:'बंद करें', cancel:'रद्द करें', confirm:'पुष्टि करें', newRecord:'नया', noData:'कोई डेटा नहीं', name:'नाम', rif:'कर आईडी', email:'ईमेल', phone:'फ़ोन', type:'प्रकार', address:'पता', actions:'कार्रवाई', client:'ग्राहक', date:'तारीख', amount:'राशि', currency:'मुद्रा', product:'उत्पाद', qty:'मात्रा', price:'मूल्य', category:'श्रेणी', cost:'लागत', margin:'मार्जिन', stock:'स्टॉक', account:'खाता', description:'विवरण', debit:'डेबिट', credit:'क्रेडिट', employee:'कर्मचारी', salary:'वेतन', supplier:'आपूर्तिकर्ता', reference:'संदर्भ', bank:'बैंक', status:'स्थिति', invoice:'चालान', method:'तरीका', title:'शीर्षक', module:'मॉड्यूल', priority:'प्राथमिकता', role:'भूमिका', branch:'शाखा', plan:'योजना', language:'भाषा', theme:'थीम', source:'स्रोत', bcvRate:'दैनिक दर', synced:'सिंक किया गया', pendingSync:'सिंक लंबित', active:'सक्रिय', inactive:'निष्क्रिय', pending:'लंबित', completed:'पूर्ण', cancelled:'रद्द', all:'सभी', today:'आज', light:'लाइट', dark:'डार्क', company:'कंपनी', appearance:'रूप', integrations:'इंटीग्रेशन', backup:'बैकअप', security:'सुरक्षा', privacy:'गोपनीयता', support:'सहायता', logout:'साइन आउट', changePhoto:'फ़ोटो बदलें', unifiedManagement:'एकीकृत व्यवसाय प्रबंधन'
};

const ar = {
  appTitle:'نظام ERP للأعمال', appSubtitle:'إدارة المبيعات والمحاسبة والضرائب والعمليات', dashboard:'لوحة التحكم', sales:'المبيعات', quote:'عروض الأسعار', clients:'العملاء', history:'السجل', inventory:'المخزون', taxes:'الضرائب', regulatory:'اللوائح', reports:'التقارير', ledger:'المحاسبة', banking:'البنوك', payroll:'الرواتب', suppliers:'الموردون', purchases:'المشتريات', audit:'التدقيق', analytics:'التحليلات', tasks:'المهام', profile:'الملف الشخصي', settings:'الإعدادات', help:'المساعدة', supportCta:'الدعم', qrBarcode:'QR / باركود', inventoryScanner:'ماسح المخزون', salesBook:'دفتر المبيعات', chartAccounts:'دليل الحسابات', generalLedger:'دفتر الأستاذ', trialBalance:'ميزان المراجعة', worksheet:'ورقة العمل', financialStatements:'القوائم المالية', accountingClose:'الإقفال المحاسبي', accountingStandards:'المعايير المحاسبية', dataImport:'استيراد جماعي', businessRules:'قواعد العمل', moduleMaturity:'الوحدات المتاحة', licenses:'التراخيص', aiAssistant:'مساعد الذكاء الاصطناعي', orders:'الطلبات', posCounter:'نقطة البيع', orderTracking:'تتبع الطلبات', deliveryMap:'خريطة التوصيل', healthcare:'العيادة', veterinary:'العيادة البيطرية', gym:'النادي الرياضي', routines:'التمارين', nutrition:'التغذية', messages:'الرسائل',
  dashboardEyebrow:'المركز التنفيذي', dashboardTitle:'لوحة الإدارة', dashboardDesc:'مؤشرات المبيعات والمخزون والمحاسبة والرواتب والعمليات.', salesEyebrow:'المبيعات', salesTitle:'المبيعات والتحصيل', salesDesc:'إدارة المبيعات والعملاء والتحصيل والمستندات التجارية.', quoteEyebrow:'المبيعات', quoteTitle:'عرض السعر والفاتورة', quoteDesc:'حساب الضرائب والاستقطاعات والإجماليات وإصدار المستندات.', clientsEyebrow:'إدارة العملاء', clientsTitle:'العملاء', clientsDesc:'دليل تجاري يتضمن البيانات الضريبية وبيانات الاتصال.', inventoryEyebrow:'العمليات', inventoryTitle:'المخزون والمنتجات', inventoryDesc:'إدارة المخزون والتكلفة والسعر والهامش والتوفر.', reportsEyebrow:'ذكاء الأعمال', reportsTitle:'التقارير والتحليلات', reportsDesc:'مؤشرات مالية وتشغيلية وتجارية حسب الفترة.', healthcareEyebrow:'الإدارة السريرية', healthcareTitle:'العيادة والمركز الطبي', healthcareDesc:'المرضى والاختصاصيون والمواعيد والسجلات الطبية والمتابعة.', veterinaryEyebrow:'الإدارة البيطرية', veterinaryTitle:'العيادة البيطرية', veterinaryDesc:'الحيوانات وأصحابها والمواعيد والسجلات واللقاحات والمتابعة.', settingsEyebrow:'النظام', settingsTitle:'إعدادات الأعمال', settingsDesc:'الشركة والمظهر واللغة والتكاملات والنسخ الاحتياطي.',
  save:'حفظ', add:'إضافة', edit:'تعديل', delete:'حذف', duplicate:'نسخ', exportCsv:'تصدير CSV', exportJson:'تصدير JSON', generatePdf:'إنشاء PDF', clear:'مسح', search:'بحث', refresh:'تحديث', sync:'مزامنة', print:'طباعة', download:'تنزيل', close:'إغلاق', cancel:'إلغاء', confirm:'تأكيد', newRecord:'جديد', noData:'لا توجد بيانات', name:'الاسم', rif:'الرقم الضريبي', email:'البريد الإلكتروني', phone:'الهاتف', type:'النوع', address:'العنوان', actions:'الإجراءات', client:'العميل', date:'التاريخ', amount:'المبلغ', currency:'العملة', product:'المنتج', qty:'الكمية', price:'السعر', category:'الفئة', cost:'التكلفة', margin:'الهامش', stock:'المخزون', account:'الحساب', description:'الوصف', debit:'مدين', credit:'دائن', employee:'الموظف', salary:'الراتب', supplier:'المورد', reference:'المرجع', bank:'البنك', status:'الحالة', invoice:'الفاتورة', method:'الطريقة', title:'العنوان', module:'الوحدة', priority:'الأولوية', role:'الدور', branch:'الفرع', plan:'الخطة', language:'اللغة', theme:'السمة', source:'المصدر', bcvRate:'سعر اليوم', synced:'تمت المزامنة', pendingSync:'بانتظار المزامنة', active:'نشط', inactive:'غير نشط', pending:'قيد الانتظار', completed:'مكتمل', cancelled:'ملغى', all:'الكل', today:'اليوم', light:'فاتح', dark:'داكن', company:'الشركة', appearance:'المظهر', integrations:'التكاملات', backup:'النسخ الاحتياطي', security:'الأمان', privacy:'الخصوصية', support:'الدعم', logout:'تسجيل الخروج', changePhoto:'تغيير الصورة', unifiedManagement:'إدارة أعمال موحدة'
};

export const translations = Object.freeze({
  es:Object.freeze(es),
  en:Object.freeze({ ...es, ...en }),
  zh:Object.freeze({ ...es, ...zh }),
  hi:Object.freeze({ ...es, ...hi }),
  ar:Object.freeze({ ...es, ...ar })
});

export const routeTranslations = Object.freeze({
  es:{ dashboard:'Dashboard', mobile:'Vista móvil', ventas:'Ventas', cotizacion:'Cotizador', clientes:'Clientes', historial:'Histórico', pedidos:'Pedidos', 'pos-sede':'POS', 'tracking-pedidos':'Seguimiento de pedidos', 'delivery-mapa':'Mapa de entregas', tasks:'Tareas', inventario:'Inventario', 'inventario-scan':'Escáner de inventario', kardex:'Kardex', qr:'QR / Barcode', proveedores:'Proveedores', compras:'Compras', contabilidad:'Libro diario', 'plan-cuentas':'Plan de cuentas', 'libro-mayor':'Libro mayor', 'balance-sumas-saldos':'Balance de sumas y saldos', 'hoja-trabajo':'Hoja de trabajo', 'estados-financieros':'Estados financieros', 'cierre-contable':'Cierre contable', bancos:'Bancos', 'normativa-contable':'Normativa contable', tributos:'Tributos', 'libro-ventas':'Libro de ventas', normativa:'Normativa', nomina:'Nómina', rrhh:'Recursos humanos', salud:'Clínica', veterinaria:'Clínica veterinaria', gimnasio:'Gimnasio', rutinas:'Rutinas', nutricion:'Nutrición', mensajes:'Mensajes', analytics:'Analítica', reportes:'Reportes', auditoria:'Auditoría', configuracion:'Configuración', backend:'Integraciones', admin:'Administración', marca:'Marca', 'demo-control':'Accesos comerciales', licencias:'Licencias', 'importacion-data':'Carga masiva', pretesting:'Estado del sistema', ayuda:'Ayuda', soporte:'Soporte', 'asistente-ia':'Asistente IA', vistas:'Galería de módulos' },
  en:{ dashboard:'Dashboard', mobile:'Mobile view', ventas:'Sales', cotizacion:'Quotes', clientes:'Clients', historial:'History', pedidos:'Orders', 'pos-sede':'POS', 'tracking-pedidos':'Order tracking', 'delivery-mapa':'Delivery map', tasks:'Tasks', inventario:'Inventory', 'inventario-scan':'Inventory scanner', kardex:'Kardex', qr:'QR / Barcode', proveedores:'Suppliers', compras:'Purchases', contabilidad:'Journal', 'plan-cuentas':'Chart of accounts', 'libro-mayor':'General ledger', 'balance-sumas-saldos':'Trial balance', 'hoja-trabajo':'Worksheet', 'estados-financieros':'Financial statements', 'cierre-contable':'Accounting close', bancos:'Banking', 'normativa-contable':'Accounting standards', tributos:'Taxes', 'libro-ventas':'Sales book', normativa:'Regulations', nomina:'Payroll', rrhh:'Human resources', salud:'Clinic', veterinaria:'Veterinary clinic', gimnasio:'Gym', rutinas:'Routines', nutricion:'Nutrition', mensajes:'Messages', analytics:'Analytics', reportes:'Reports', auditoria:'Audit', configuracion:'Settings', backend:'Integrations', admin:'Administration', marca:'Brand', 'demo-control':'Commercial access', licencias:'Licenses', 'importacion-data':'Bulk import', pretesting:'System status', ayuda:'Help', soporte:'Support', 'asistente-ia':'AI assistant', vistas:'Module gallery' },
  zh:{ dashboard:'仪表板', mobile:'移动视图', ventas:'销售', cotizacion:'报价', clientes:'客户', historial:'历史记录', pedidos:'订单', 'pos-sede':'POS', 'tracking-pedidos':'订单跟踪', 'delivery-mapa':'配送地图', tasks:'任务', inventario:'库存', 'inventario-scan':'库存扫描', kardex:'库存明细', qr:'QR / 条码', proveedores:'供应商', compras:'采购', contabilidad:'日记账', 'plan-cuentas':'会计科目表', 'libro-mayor':'总账', 'balance-sumas-saldos':'试算平衡', 'hoja-trabajo':'工作表', 'estados-financieros':'财务报表', 'cierre-contable':'会计结账', bancos:'银行', 'normativa-contable':'会计准则', tributos:'税务', 'libro-ventas':'销售账簿', normativa:'法规', nomina:'薪资', rrhh:'人力资源', salud:'诊所', veterinaria:'兽医诊所', gimnasio:'健身房', rutinas:'训练计划', nutricion:'营养', mensajes:'消息', analytics:'分析', reportes:'报表', auditoria:'审计', configuracion:'设置', backend:'集成', admin:'管理', marca:'品牌', 'demo-control':'商业访问', licencias:'许可证', 'importacion-data':'批量导入', pretesting:'系统状态', ayuda:'帮助', soporte:'支持', 'asistente-ia':'AI 助手', vistas:'模块库' },
  hi:{ dashboard:'डैशबोर्ड', mobile:'मोबाइल दृश्य', ventas:'बिक्री', cotizacion:'कोटेशन', clientes:'ग्राहक', historial:'इतिहास', pedidos:'ऑर्डर', 'pos-sede':'POS', 'tracking-pedidos':'ऑर्डर ट्रैकिंग', 'delivery-mapa':'डिलीवरी मैप', tasks:'कार्य', inventario:'इन्वेंटरी', 'inventario-scan':'इन्वेंटरी स्कैनर', kardex:'कार्डेक्स', qr:'QR / बारकोड', proveedores:'आपूर्तिकर्ता', compras:'खरीद', contabilidad:'जर्नल', 'plan-cuentas':'खाता सूची', 'libro-mayor':'महाबही', 'balance-sumas-saldos':'ट्रायल बैलेंस', 'hoja-trabajo':'वर्कशीट', 'estados-financieros':'वित्तीय विवरण', 'cierre-contable':'लेखा समापन', bancos:'बैंकिंग', 'normativa-contable':'लेखा मानक', tributos:'कर', 'libro-ventas':'बिक्री पुस्तक', normativa:'नियम', nomina:'पेरोल', rrhh:'मानव संसाधन', salud:'क्लिनिक', veterinaria:'पशु चिकित्सालय', gimnasio:'जिम', rutinas:'रूटीन', nutricion:'पोषण', mensajes:'संदेश', analytics:'विश्लेषण', reportes:'रिपोर्ट', auditoria:'ऑडिट', configuracion:'सेटिंग्स', backend:'इंटीग्रेशन', admin:'प्रशासन', marca:'ब्रांड', 'demo-control':'व्यावसायिक एक्सेस', licencias:'लाइसेंस', 'importacion-data':'बल्क इम्पोर्ट', pretesting:'सिस्टम स्थिति', ayuda:'सहायता', soporte:'सहायता', 'asistente-ia':'AI सहायक', vistas:'मॉड्यूल गैलरी' },
  ar:{ dashboard:'لوحة التحكم', mobile:'عرض الجوال', ventas:'المبيعات', cotizacion:'عروض الأسعار', clientes:'العملاء', historial:'السجل', pedidos:'الطلبات', 'pos-sede':'نقطة البيع', 'tracking-pedidos':'تتبع الطلبات', 'delivery-mapa':'خريطة التوصيل', tasks:'المهام', inventario:'المخزون', 'inventario-scan':'ماسح المخزون', kardex:'حركة المخزون', qr:'QR / باركود', proveedores:'الموردون', compras:'المشتريات', contabilidad:'دفتر اليومية', 'plan-cuentas':'دليل الحسابات', 'libro-mayor':'دفتر الأستاذ', 'balance-sumas-saldos':'ميزان المراجعة', 'hoja-trabajo':'ورقة العمل', 'estados-financieros':'القوائم المالية', 'cierre-contable':'الإقفال المحاسبي', bancos:'البنوك', 'normativa-contable':'المعايير المحاسبية', tributos:'الضرائب', 'libro-ventas':'دفتر المبيعات', normativa:'اللوائح', nomina:'الرواتب', rrhh:'الموارد البشرية', salud:'العيادة', veterinaria:'العيادة البيطرية', gimnasio:'النادي الرياضي', rutinas:'التمارين', nutricion:'التغذية', mensajes:'الرسائل', analytics:'التحليلات', reportes:'التقارير', auditoria:'التدقيق', configuracion:'الإعدادات', backend:'التكاملات', admin:'الإدارة', marca:'العلامة التجارية', 'demo-control':'الوصول التجاري', licencias:'التراخيص', 'importacion-data':'استيراد جماعي', pretesting:'حالة النظام', ayuda:'المساعدة', soporte:'الدعم', 'asistente-ia':'مساعد الذكاء الاصطناعي', vistas:'معرض الوحدات' }
});

export const customerCopyReplacements = Object.freeze({
  'Shell único · listo para Supabase':'Gestión empresarial unificada',
  'Core real':'Operativo',
  'Módulo avanzado':'Especializado',
  'Módulo demo/comercial':'Opcional',
  'Módulos operativos requeridos para producción.':'Funciones esenciales para la operación diaria.',
  'Módulos especializados con alcance empresarial.':'Herramientas especializadas según el área.',
  'Módulos de preventa o personalización.':'Extensiones disponibles según el plan y la configuración.',
  'Prototipos Stitch':'Galería de módulos',
  'Pretesting QA':'Estado del sistema',
  'Respaldo y QA':'Respaldo y seguridad',
  'Guardado, respaldo y QA':'Guardado, respaldo y seguridad',
  'Probar backend':'Verificar conexión',
  'Reiniciar demo':'Restaurar datos de ejemplo',
  'Solo desarrollo':'Pendiente',
  'Usuario Demo Comercial':'Acceso comercial temporal',
  'Demo limitado':'Acceso temporal',
  'Modo Demo Comercial':'Modo comercial'
});
